/**
 * Real exercise content for Python Master 12.
 * 150 unique exercises across 10 levels, 3 per lesson.
 * Each exercise has unique problem, test cases, starter code, and hints.
 * 
 * FILE 1: Exercises 1-75 (Levels 1-3, Lessons 1-15)
 */

export interface ExerciseContent {
  id: number;
  lesson_id: number;
  title: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard';
  starter_code: string;
  test_cases: Array<{ input: string; expected_output: string; is_hidden: boolean }>;
  hints: string[];
  order_index: number;
  xp_reward: number;
}

export const EXERCISES: ExerciseContent[] = [
  // ============================================================
  // LEVEL 1: GIỚI THIỆU PYTHON (Lessons 1-5)
  // ============================================================

  // --- Lesson 1: Python là gì (print basics, string output, multi-line) ---
  {
    id: 1,
    lesson_id: 1,
    title: 'Chào thế giới',
    description: 'Viết chương trình in ra dòng chữ "Xin chao Python!" (không có dấu ngoặc kép).',
    difficulty: 'easy',
    starter_code: '# In ra dong chu "Xin chao Python!"\n',
    test_cases: [
      { input: '', expected_output: 'Xin chao Python!', is_hidden: false },
    ],
    hints: ['Sử dụng hàm print()', 'Cú pháp: print("nội dung")'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 2,
    lesson_id: 1,
    title: 'In thông tin cá nhân',
    description: 'Viết chương trình in ra 3 dòng:\nDòng 1: Tên của bạn (dùng "Nguyen Van A")\nDòng 2: Tuổi (dùng "18")\nDòng 3: Trường (dùng "THPT Cau Giay")',
    difficulty: 'medium',
    starter_code: '# In ra thong tin ca nhan tren 3 dong\nprint("Nguyen Van A")\n# Tiep tuc in tuoi va truong\n',
    test_cases: [
      { input: '', expected_output: 'Nguyen Van A\n18\nTHPT Cau Giay', is_hidden: false },
    ],
    hints: ['Mỗi lệnh print() sẽ in trên một dòng mới', 'Bạn cần 3 lệnh print()'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 3,
    lesson_id: 1,
    title: 'Vẽ hình chữ nhật bằng dấu sao',
    description: 'Viết chương trình in ra hình chữ nhật 3x5 bằng dấu * như sau:\n*****\n*****\n*****',
    difficulty: 'hard',
    starter_code: '# Ve hinh chu nhat 3 dong, moi dong 5 dau *\n',
    test_cases: [
      { input: '', expected_output: '*****\n*****\n*****', is_hidden: false },
    ],
    hints: ['Mỗi dòng có 5 dấu *', 'Dùng print("*****") cho mỗi dòng', 'Hoặc dùng print("*" * 5) để lặp ký tự'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 2: Biến và kiểu dữ liệu ---
  {
    id: 4,
    lesson_id: 2,
    title: 'Hoán đổi giá trị hai biến',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng). Hãy hoán đổi giá trị của chúng rồi in ra a và b (mỗi số trên một dòng).',
    difficulty: 'easy',
    starter_code: 'a = int(input())\nb = int(input())\n# Hoan doi a va b\n\nprint(a)\nprint(b)\n',
    test_cases: [
      { input: '3\n5', expected_output: '5\n3', is_hidden: false },
      { input: '10\n-2', expected_output: '-2\n10', is_hidden: false },
      { input: '0\n0', expected_output: '0\n0', is_hidden: true },
    ],
    hints: ['Dùng biến tạm: temp = a', 'Hoặc Python cho phép: a, b = b, a'],
    order_index: 1,
    xp_reward: 15,
  },
  {
    id: 5,
    lesson_id: 2,
    title: 'Kiểm tra kiểu dữ liệu',
    description: 'Cho một biến x = 3.14. Hãy in ra tên kiểu dữ liệu của x (chỉ in tên kiểu, ví dụ: float).\nGợi ý: dùng hàm type() và lấy thuộc tính __name__.',
    difficulty: 'medium',
    starter_code: 'x = 3.14\n# In ra ten kieu du lieu cua x\n# Goi y: type(x).__name__\n',
    test_cases: [
      { input: '', expected_output: 'float', is_hidden: false },
    ],
    hints: ['type(x) trả về <class \'float\'>', 'type(x).__name__ trả về chuỗi "float"'],
    order_index: 2,
    xp_reward: 20,
  },
  {
    id: 6,
    lesson_id: 2,
    title: 'Chuyển đổi nhiệt độ',
    description: 'Cho nhiệt độ Celsius (số thực) nhập từ bàn phím. Hãy chuyển sang Fahrenheit theo công thức F = C * 9/5 + 32 và in kết quả làm tròn 1 chữ số thập phân.',
    difficulty: 'hard',
    starter_code: 'c = float(input())\n# Tinh nhiet do Fahrenheit\n\n# In ket qua lam tron 1 chu so thap phan\n',
    test_cases: [
      { input: '0', expected_output: '32.0', is_hidden: false },
      { input: '100', expected_output: '212.0', is_hidden: false },
      { input: '37.5', expected_output: '99.5', is_hidden: true },
    ],
    hints: ['Công thức: F = C * 9/5 + 32', 'Dùng round(f, 1) để làm tròn 1 chữ số'],
    order_index: 3,
    xp_reward: 25,
  },

  // --- Lesson 3: Nhập/xuất dữ liệu ---
  {
    id: 7,
    lesson_id: 3,
    title: 'Chào hỏi theo tên',
    description: 'Nhập tên người dùng từ bàn phím và in ra lời chào theo định dạng: "Xin chao, [tên]!".\nVí dụ: nếu nhập "An" thì in ra "Xin chao, An!"',
    difficulty: 'easy',
    starter_code: 'ten = input()\n# In ra loi chao\n',
    test_cases: [
      { input: 'An', expected_output: 'Xin chao, An!', is_hidden: false },
      { input: 'Binh', expected_output: 'Xin chao, Binh!', is_hidden: false },
      { input: 'Minh Anh', expected_output: 'Xin chao, Minh Anh!', is_hidden: true },
    ],
    hints: ['Dùng f-string: f"Xin chao, {ten}!"', 'Hoặc nối chuỗi: "Xin chao, " + ten + "!"'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 8,
    lesson_id: 3,
    title: 'Thông tin học sinh',
    description: 'Nhập lần lượt: tên (chuỗi), tuổi (số nguyên), điểm trung bình (số thực). In ra theo định dạng:\n"Ho ten: [tên]"\n"Tuoi: [tuổi]"\n"DTB: [điểm]"\nĐiểm in ra giữ nguyên (không làm tròn).',
    difficulty: 'medium',
    starter_code: 'ten = input()\ntuoi = int(input())\ndtb = float(input())\n# In ra thong tin\n',
    test_cases: [
      { input: 'Nguyen Van A\n17\n8.5', expected_output: 'Ho ten: Nguyen Van A\nTuoi: 17\nDTB: 8.5', is_hidden: false },
      { input: 'Tran Thi B\n18\n9.0', expected_output: 'Ho ten: Tran Thi B\nTuoi: 18\nDTB: 9.0', is_hidden: false },
    ],
    hints: ['Dùng f-string cho mỗi dòng', 'f"Ho ten: {ten}"'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 9,
    lesson_id: 3,
    title: 'Tính tiền mua hàng',
    description: 'Nhập số lượng sản phẩm (số nguyên) và đơn giá (số thực). Tính tổng tiền = số lượng × đơn giá. In ra theo định dạng: "Tong tien: [tổng] VND" với tổng tiền làm tròn 0 chữ số thập phân (in số nguyên).',
    difficulty: 'hard',
    starter_code: 'so_luong = int(input())\ndon_gia = float(input())\n# Tinh tong tien\n\n# In ket qua\n',
    test_cases: [
      { input: '3\n25000.0', expected_output: 'Tong tien: 75000 VND', is_hidden: false },
      { input: '5\n12500.5', expected_output: 'Tong tien: 62502 VND', is_hidden: false },
      { input: '1\n99999.9', expected_output: 'Tong tien: 100000 VND', is_hidden: true },
    ],
    hints: ['tong = so_luong * don_gia', 'Dùng int(round(tong)) hoặc round(tong) để làm tròn', 'f"Tong tien: {int(round(tong))} VND"'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 4: Toán tử ---
  {
    id: 10,
    lesson_id: 4,
    title: 'Phép chia lấy dư',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng, b ≠ 0). In ra thương nguyên (phép chia lấy phần nguyên) và số dư khi chia a cho b, mỗi kết quả trên một dòng.',
    difficulty: 'easy',
    starter_code: 'a = int(input())\nb = int(input())\n# In thuong nguyen va so du\n',
    test_cases: [
      { input: '17\n5', expected_output: '3\n2', is_hidden: false },
      { input: '20\n4', expected_output: '5\n0', is_hidden: false },
      { input: '7\n3', expected_output: '2\n1', is_hidden: true },
    ],
    hints: ['Thương nguyên: a // b', 'Số dư: a % b'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 11,
    lesson_id: 4,
    title: 'Tính lũy thừa và căn bậc hai',
    description: 'Cho số nguyên dương n. In ra:\nDòng 1: n bình phương (n²)\nDòng 2: n lập phương (n³)\nDòng 3: căn bậc hai của n (làm tròn 2 chữ số thập phân)',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# Tinh n^2, n^3, va can bac hai cua n\n',
    test_cases: [
      { input: '4', expected_output: '16\n64\n2.0', is_hidden: false },
      { input: '9', expected_output: '81\n729\n3.0', is_hidden: false },
      { input: '7', expected_output: '49\n343\n2.65', is_hidden: true },
    ],
    hints: ['Lũy thừa: n**2, n**3', 'Căn bậc hai: n**0.5 hoặc import math rồi math.sqrt(n)', 'Làm tròn: round(x, 2)'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 12,
    lesson_id: 4,
    title: 'Tách các chữ số',
    description: 'Cho một số nguyên dương có đúng 3 chữ số (100-999). Hãy in ra hàng trăm, hàng chục, hàng đơn vị, mỗi số trên một dòng.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Tach cac chu so hang tram, hang chuc, hang don vi\n',
    test_cases: [
      { input: '456', expected_output: '4\n5\n6', is_hidden: false },
      { input: '103', expected_output: '1\n0\n3', is_hidden: false },
      { input: '999', expected_output: '9\n9\n9', is_hidden: true },
    ],
    hints: ['Hàng trăm: n // 100', 'Hàng chục: (n // 10) % 10 hoặc (n % 100) // 10', 'Hàng đơn vị: n % 10'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 5: Chuỗi cơ bản ---
  {
    id: 13,
    lesson_id: 5,
    title: 'Độ dài chuỗi',
    description: 'Nhập một chuỗi từ bàn phím. In ra độ dài của chuỗi đó.',
    difficulty: 'easy',
    starter_code: 's = input()\n# In ra do dai cua chuoi s\n',
    test_cases: [
      { input: 'Hello', expected_output: '5', is_hidden: false },
      { input: 'Python 12', expected_output: '9', is_hidden: false },
      { input: '', expected_output: '0', is_hidden: true },
    ],
    hints: ['Dùng hàm len()', 'print(len(s))'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 14,
    lesson_id: 5,
    title: 'Đảo ngược chuỗi',
    description: 'Nhập một chuỗi từ bàn phím. In ra chuỗi đảo ngược của nó.',
    difficulty: 'medium',
    starter_code: 's = input()\n# In ra chuoi dao nguoc\n',
    test_cases: [
      { input: 'Python', expected_output: 'nohtyP', is_hidden: false },
      { input: 'abcde', expected_output: 'edcba', is_hidden: false },
      { input: '12345', expected_output: '54321', is_hidden: true },
    ],
    hints: ['Dùng slicing: s[::-1]', 'Bước -1 nghĩa là đi ngược từ cuối về đầu'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 15,
    lesson_id: 5,
    title: 'Đếm nguyên âm',
    description: 'Nhập một chuỗi (chỉ chứa chữ cái thường không dấu). Đếm số nguyên âm (a, e, i, o, u) trong chuỗi và in ra kết quả.',
    difficulty: 'hard',
    starter_code: 's = input()\n# Dem so nguyen am trong chuoi\ndem = 0\n\n# In ket qua\nprint(dem)\n',
    test_cases: [
      { input: 'hello', expected_output: '2', is_hidden: false },
      { input: 'python', expected_output: '1', is_hidden: false },
      { input: 'aeiou', expected_output: '5', is_hidden: true },
    ],
    hints: ['Nguyên âm: "aeiou"', 'Duyệt từng ký tự: for c in s', 'Kiểm tra: if c in "aeiou"'],
    order_index: 3,
    xp_reward: 20,
  },

  // ============================================================
  // LEVEL 2: BIỂU THỨC VÀ TOÁN TỬ (Lessons 6-10)
  // ============================================================

  // --- Lesson 6: So sánh ---
  {
    id: 16,
    lesson_id: 6,
    title: 'So sánh hai số',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng). In ra "True" nếu a lớn hơn b, ngược lại in "False".',
    difficulty: 'easy',
    starter_code: 'a = int(input())\nb = int(input())\n# So sanh a > b va in ket qua\n',
    test_cases: [
      { input: '5\n3', expected_output: 'True', is_hidden: false },
      { input: '2\n7', expected_output: 'False', is_hidden: false },
      { input: '4\n4', expected_output: 'False', is_hidden: true },
    ],
    hints: ['Phép so sánh a > b trả về True hoặc False', 'print(a > b)'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 17,
    lesson_id: 6,
    title: 'Tìm số lớn nhất trong 2 số',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng). In ra giá trị lớn nhất.',
    difficulty: 'medium',
    starter_code: 'a = int(input())\nb = int(input())\n# Tim va in so lon nhat\n',
    test_cases: [
      { input: '10\n20', expected_output: '20', is_hidden: false },
      { input: '-3\n-7', expected_output: '-3', is_hidden: false },
      { input: '5\n5', expected_output: '5', is_hidden: true },
    ],
    hints: ['Dùng hàm max(a, b)', 'Hoặc dùng if: if a > b: ... else: ...'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 18,
    lesson_id: 6,
    title: 'Tìm số lớn nhất trong 3 số',
    description: 'Cho ba số nguyên a, b, c (mỗi số trên một dòng). In ra giá trị lớn nhất trong ba số.',
    difficulty: 'hard',
    starter_code: 'a = int(input())\nb = int(input())\nc = int(input())\n# Tim va in so lon nhat trong 3 so\n',
    test_cases: [
      { input: '3\n7\n5', expected_output: '7', is_hidden: false },
      { input: '-1\n-5\n-3', expected_output: '-1', is_hidden: false },
      { input: '10\n10\n10', expected_output: '10', is_hidden: true },
    ],
    hints: ['Dùng max(a, b, c)', 'Hoặc so sánh từng cặp'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 7: Logic ---
  {
    id: 19,
    lesson_id: 7,
    title: 'Kiểm tra năm nhuận đơn giản',
    description: 'Cho một năm (số nguyên dương). In "True" nếu năm đó chia hết cho 4, ngược lại in "False".\n(Đây là kiểm tra đơn giản, chưa xét đầy đủ quy tắc năm nhuận)',
    difficulty: 'easy',
    starter_code: 'nam = int(input())\n# Kiem tra nam chia het cho 4\n',
    test_cases: [
      { input: '2024', expected_output: 'True', is_hidden: false },
      { input: '2023', expected_output: 'False', is_hidden: false },
      { input: '2000', expected_output: 'True', is_hidden: true },
    ],
    hints: ['Chia hết cho 4: nam % 4 == 0', 'print(nam % 4 == 0)'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 20,
    lesson_id: 7,
    title: 'Kiểm tra số trong khoảng',
    description: 'Cho số nguyên n. Kiểm tra xem n có nằm trong đoạn [10, 100] hay không (10 ≤ n ≤ 100). In "True" hoặc "False".',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# Kiem tra 10 <= n <= 100\n',
    test_cases: [
      { input: '50', expected_output: 'True', is_hidden: false },
      { input: '5', expected_output: 'False', is_hidden: false },
      { input: '10', expected_output: 'True', is_hidden: false },
      { input: '101', expected_output: 'False', is_hidden: true },
    ],
    hints: ['Python cho phép: 10 <= n <= 100', 'Hoặc dùng and: n >= 10 and n <= 100'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 21,
    lesson_id: 7,
    title: 'Năm nhuận đầy đủ',
    description: 'Cho một năm (số nguyên dương). Kiểm tra năm nhuận theo quy tắc đầy đủ:\n- Chia hết cho 400 → nhuận\n- Chia hết cho 100 nhưng không chia hết cho 400 → không nhuận\n- Chia hết cho 4 → nhuận\n- Còn lại → không nhuận\nIn "True" nếu là năm nhuận, "False" nếu không.',
    difficulty: 'hard',
    starter_code: 'nam = int(input())\n# Kiem tra nam nhuan day du\n',
    test_cases: [
      { input: '2000', expected_output: 'True', is_hidden: false },
      { input: '1900', expected_output: 'False', is_hidden: false },
      { input: '2024', expected_output: 'True', is_hidden: false },
      { input: '2023', expected_output: 'False', is_hidden: true },
    ],
    hints: ['Điều kiện: (nam % 400 == 0) or (nam % 4 == 0 and nam % 100 != 0)', 'Thứ tự kiểm tra rất quan trọng'],
    order_index: 3,
    xp_reward: 25,
  },

  // --- Lesson 8: Ép kiểu ---
  {
    id: 22,
    lesson_id: 8,
    title: 'Chuyển chuỗi sang số',
    description: 'Cho hai chuỗi số trên hai dòng (ví dụ: "12" và "8"). Hãy chuyển chúng thành số nguyên, tính tổng và in ra kết quả.',
    difficulty: 'easy',
    starter_code: 's1 = input()\ns2 = input()\n# Chuyen sang so nguyen va tinh tong\n',
    test_cases: [
      { input: '12\n8', expected_output: '20', is_hidden: false },
      { input: '100\n250', expected_output: '350', is_hidden: false },
      { input: '-5\n15', expected_output: '10', is_hidden: true },
    ],
    hints: ['Dùng int() để chuyển chuỗi sang số nguyên', 'tong = int(s1) + int(s2)'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 23,
    lesson_id: 8,
    title: 'Nối số thành chuỗi',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng). Hãy nối chúng thành một chuỗi (không có khoảng trắng) và in ra.\nVí dụ: a=12, b=34 → in ra "1234".',
    difficulty: 'medium',
    starter_code: 'a = int(input())\nb = int(input())\n# Noi a va b thanh chuoi va in ra\n',
    test_cases: [
      { input: '12\n34', expected_output: '1234', is_hidden: false },
      { input: '0\n5', expected_output: '05', is_hidden: false },
      { input: '99\n1', expected_output: '991', is_hidden: true },
    ],
    hints: ['Chuyển số sang chuỗi: str(a)', 'Nối chuỗi: str(a) + str(b)'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 24,
    lesson_id: 8,
    title: 'Ép kiểu an toàn',
    description: 'Nhập một chuỗi từ bàn phím. Nếu chuỗi đó có thể chuyển thành số nguyên, in ra số đó nhân 2. Nếu không thể chuyển, in ra "Khong hop le".',
    difficulty: 'hard',
    starter_code: 's = input()\n# Kiem tra va ep kieu an toan\n',
    test_cases: [
      { input: '25', expected_output: '50', is_hidden: false },
      { input: 'abc', expected_output: 'Khong hop le', is_hidden: false },
      { input: '-10', expected_output: '-20', is_hidden: false },
      { input: '3.14', expected_output: 'Khong hop le', is_hidden: true },
    ],
    hints: ['Dùng try/except để bắt lỗi', 'Hoặc dùng phương thức .lstrip("-").isdigit() để kiểm tra', 'try:\\n  n = int(s)\\n  print(n * 2)\\nexcept ValueError:\\n  print("Khong hop le")'],
    order_index: 3,
    xp_reward: 25,
  },

  // --- Lesson 9: Hàm toán học ---
  {
    id: 25,
    lesson_id: 9,
    title: 'Giá trị tuyệt đối',
    description: 'Cho một số nguyên n. In ra giá trị tuyệt đối của n.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# In gia tri tuyet doi cua n\n',
    test_cases: [
      { input: '-5', expected_output: '5', is_hidden: false },
      { input: '3', expected_output: '3', is_hidden: false },
      { input: '0', expected_output: '0', is_hidden: true },
    ],
    hints: ['Dùng hàm abs()', 'print(abs(n))'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 26,
    lesson_id: 9,
    title: 'Tính diện tích hình tròn',
    description: 'Cho bán kính r (số thực dương). Tính diện tích hình tròn theo công thức S = π × r². In kết quả làm tròn 2 chữ số thập phân.\nDùng math.pi cho giá trị π.',
    difficulty: 'medium',
    starter_code: 'import math\nr = float(input())\n# Tinh dien tich hinh tron\n',
    test_cases: [
      { input: '5', expected_output: '78.54', is_hidden: false },
      { input: '1', expected_output: '3.14', is_hidden: false },
      { input: '10', expected_output: '314.16', is_hidden: true },
    ],
    hints: ['S = math.pi * r ** 2', 'Làm tròn: round(S, 2)'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 27,
    lesson_id: 9,
    title: 'Khoảng cách hai điểm',
    description: 'Cho tọa độ hai điểm A(x1, y1) và B(x2, y2) trên mặt phẳng (nhập 4 số thực, mỗi số trên một dòng theo thứ tự x1, y1, x2, y2). Tính khoảng cách AB và in kết quả làm tròn 2 chữ số thập phân.\nCông thức: d = √((x2-x1)² + (y2-y1)²)',
    difficulty: 'hard',
    starter_code: 'import math\nx1 = float(input())\ny1 = float(input())\nx2 = float(input())\ny2 = float(input())\n# Tinh khoang cach AB\n',
    test_cases: [
      { input: '0\n0\n3\n4', expected_output: '5.0', is_hidden: false },
      { input: '1\n1\n4\n5', expected_output: '5.0', is_hidden: false },
      { input: '-1\n-1\n2\n3', expected_output: '5.0', is_hidden: true },
    ],
    hints: ['d = math.sqrt((x2-x1)**2 + (y2-y1)**2)', 'Làm tròn: round(d, 2)'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 10: Toán tử chuỗi ---
  {
    id: 28,
    lesson_id: 10,
    title: 'Kiểm tra chuỗi con',
    description: 'Cho hai chuỗi s và sub (mỗi chuỗi trên một dòng). Kiểm tra xem sub có phải là chuỗi con của s hay không. In "True" hoặc "False".',
    difficulty: 'easy',
    starter_code: 's = input()\nsub = input()\n# Kiem tra sub co nam trong s khong\n',
    test_cases: [
      { input: 'Hello World\nWorld', expected_output: 'True', is_hidden: false },
      { input: 'Python\njava', expected_output: 'False', is_hidden: false },
      { input: 'abcdef\ncde', expected_output: 'True', is_hidden: true },
    ],
    hints: ['Dùng toán tử in: sub in s', 'print(sub in s)'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 29,
    lesson_id: 10,
    title: 'Đếm ký tự xuất hiện',
    description: 'Cho một chuỗi s (dòng 1) và một ký tự c (dòng 2). Đếm số lần ký tự c xuất hiện trong chuỗi s và in ra kết quả.',
    difficulty: 'medium',
    starter_code: 's = input()\nc = input()\n# Dem so lan c xuat hien trong s\n',
    test_cases: [
      { input: 'banana\na', expected_output: '3', is_hidden: false },
      { input: 'hello world\nl', expected_output: '3', is_hidden: false },
      { input: 'python\nz', expected_output: '0', is_hidden: true },
    ],
    hints: ['Dùng phương thức .count()', 'print(s.count(c))'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 30,
    lesson_id: 10,
    title: 'Thay thế từ trong chuỗi',
    description: 'Cho chuỗi s (dòng 1), từ cần tìm old_word (dòng 2), từ thay thế new_word (dòng 3). Thay thế TẤT CẢ các lần xuất hiện của old_word bằng new_word trong s và in ra chuỗi kết quả.',
    difficulty: 'hard',
    starter_code: 's = input()\nold_word = input()\nnew_word = input()\n# Thay the va in ket qua\n',
    test_cases: [
      { input: 'I love Java\nJava\nPython', expected_output: 'I love Python', is_hidden: false },
      { input: 'aaa\na\nbb', expected_output: 'bbbbbb', is_hidden: false },
      { input: 'hello world\nxyz\nabc', expected_output: 'hello world', is_hidden: true },
    ],
    hints: ['Dùng phương thức .replace()', 's.replace(old_word, new_word)'],
    order_index: 3,
    xp_reward: 20,
  },

  // ============================================================
  // LEVEL 3: CÂU LỆNH ĐIỀU KIỆN (Lessons 11-15)
  // ============================================================

  // --- Lesson 11: if ---
  {
    id: 31,
    lesson_id: 11,
    title: 'Kiểm tra số dương',
    description: 'Cho một số nguyên n. Nếu n > 0, in ra "So duong". Nếu không, không in gì cả.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Kiem tra so duong\n',
    test_cases: [
      { input: '5', expected_output: 'So duong', is_hidden: false },
      { input: '-3', expected_output: '', is_hidden: false },
      { input: '0', expected_output: '', is_hidden: true },
    ],
    hints: ['Dùng if n > 0:', 'Chỉ in khi điều kiện đúng'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 32,
    lesson_id: 11,
    title: 'Kiểm tra đủ tuổi lái xe',
    description: 'Cho tuổi của một người (số nguyên). Nếu tuổi >= 18, in ra "Du tuoi lai xe". Nếu không, in ra "Chua du tuoi".',
    difficulty: 'medium',
    starter_code: 'tuoi = int(input())\n# Kiem tra du tuoi lai xe (>= 18)\n',
    test_cases: [
      { input: '20', expected_output: 'Du tuoi lai xe', is_hidden: false },
      { input: '16', expected_output: 'Chua du tuoi', is_hidden: false },
      { input: '18', expected_output: 'Du tuoi lai xe', is_hidden: true },
    ],
    hints: ['if tuoi >= 18:', 'Nhớ dùng >= chứ không phải >'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 33,
    lesson_id: 11,
    title: 'Kiểm tra chia hết cho 3 và 5',
    description: 'Cho số nguyên dương n. Nếu n chia hết cho cả 3 và 5, in "Chia het cho 3 va 5". Nếu chỉ chia hết cho 3, in "Chia het cho 3". Nếu chỉ chia hết cho 5, in "Chia het cho 5". Nếu không chia hết cho số nào, in "Khong chia het".',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Kiem tra chia het cho 3 va 5\n',
    test_cases: [
      { input: '15', expected_output: 'Chia het cho 3 va 5', is_hidden: false },
      { input: '9', expected_output: 'Chia het cho 3', is_hidden: false },
      { input: '10', expected_output: 'Chia het cho 5', is_hidden: false },
      { input: '7', expected_output: 'Khong chia het', is_hidden: true },
    ],
    hints: ['Kiểm tra chia hết: n % 3 == 0', 'Kiểm tra cả hai: n % 3 == 0 and n % 5 == 0', 'Kiểm tra trường hợp chia hết cho cả hai TRƯỚC'],
    order_index: 3,
    xp_reward: 20,
  },

  // --- Lesson 12: if/else ---
  {
    id: 34,
    lesson_id: 12,
    title: 'Chẵn hay lẻ',
    description: 'Cho một số nguyên n. In ra "Chan" nếu n là số chẵn, "Le" nếu n là số lẻ.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Kiem tra chan hay le\n',
    test_cases: [
      { input: '4', expected_output: 'Chan', is_hidden: false },
      { input: '7', expected_output: 'Le', is_hidden: false },
      { input: '0', expected_output: 'Chan', is_hidden: true },
      { input: '-3', expected_output: 'Le', is_hidden: true },
    ],
    hints: ['Số chẵn: n % 2 == 0', 'Số lẻ: n % 2 != 0'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 35,
    lesson_id: 12,
    title: 'Đậu hay rớt',
    description: 'Cho điểm trung bình (số thực). Nếu điểm >= 5.0, in "Dau". Ngược lại in "Rot".',
    difficulty: 'medium',
    starter_code: 'diem = float(input())\n# Kiem tra dau hay rot\n',
    test_cases: [
      { input: '7.5', expected_output: 'Dau', is_hidden: false },
      { input: '4.9', expected_output: 'Rot', is_hidden: false },
      { input: '5.0', expected_output: 'Dau', is_hidden: true },
    ],
    hints: ['if diem >= 5.0:', 'else: in "Rot"'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 36,
    lesson_id: 12,
    title: 'Tính tiền taxi',
    description: 'Một hãng taxi tính giá:\n- 2 km đầu: 15000 VND/km\n- Từ km thứ 3 trở đi: 10000 VND/km\nCho số km đi được (số thực dương). Tính và in ra tổng tiền (số nguyên, làm tròn).',
    difficulty: 'hard',
    starter_code: 'km = float(input())\n# Tinh tien taxi\n',
    test_cases: [
      { input: '1', expected_output: '15000', is_hidden: false },
      { input: '2', expected_output: '30000', is_hidden: false },
      { input: '5', expected_output: '60000', is_hidden: false },
      { input: '10', expected_output: '110000', is_hidden: true },
    ],
    hints: ['Nếu km <= 2: tien = km * 15000', 'Nếu km > 2: tien = 2 * 15000 + (km - 2) * 10000', 'In ra int(round(tien))'],
    order_index: 3,
    xp_reward: 25,
  },

  // --- Lesson 13: if/elif/else ---
  {
    id: 37,
    lesson_id: 13,
    title: 'Xếp loại học lực',
    description: 'Cho điểm trung bình (số thực, 0-10). Xếp loại:\n- >= 8.0: "Gioi"\n- >= 6.5: "Kha"\n- >= 5.0: "Trung binh"\n- < 5.0: "Yeu"\nIn ra xếp loại tương ứng.',
    difficulty: 'easy',
    starter_code: 'diem = float(input())\n# Xep loai hoc luc\n',
    test_cases: [
      { input: '9.0', expected_output: 'Gioi', is_hidden: false },
      { input: '7.0', expected_output: 'Kha', is_hidden: false },
      { input: '5.5', expected_output: 'Trung binh', is_hidden: false },
      { input: '3.0', expected_output: 'Yeu', is_hidden: true },
    ],
    hints: ['Dùng if/elif/elif/else', 'Kiểm tra từ cao xuống thấp'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 38,
    lesson_id: 13,
    title: 'Số ngày trong tháng',
    description: 'Cho tháng (số nguyên 1-12). In ra số ngày trong tháng đó (giả sử năm không nhuận, tháng 2 có 28 ngày).\nCác tháng 4, 6, 9, 11 có 30 ngày. Các tháng còn lại có 31 ngày.',
    difficulty: 'medium',
    starter_code: 'thang = int(input())\n# In so ngay trong thang\n',
    test_cases: [
      { input: '1', expected_output: '31', is_hidden: false },
      { input: '2', expected_output: '28', is_hidden: false },
      { input: '4', expected_output: '30', is_hidden: false },
      { input: '12', expected_output: '31', is_hidden: true },
    ],
    hints: ['Tháng 2: 28 ngày', 'Tháng 4, 6, 9, 11: 30 ngày', 'Dùng if/elif/else hoặc kiểm tra thang in [4, 6, 9, 11]'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 39,
    lesson_id: 13,
    title: 'Máy tính đơn giản',
    description: 'Cho hai số thực a, b (mỗi số trên một dòng) và một phép toán op (dòng 3, là một trong: +, -, *, /).\nThực hiện phép toán và in kết quả làm tròn 2 chữ số thập phân.\nNếu phép chia mà b = 0, in "Loi: chia cho 0".\nNếu phép toán không hợp lệ, in "Phep toan khong hop le".',
    difficulty: 'hard',
    starter_code: 'a = float(input())\nb = float(input())\nop = input()\n# Thuc hien phep toan\n',
    test_cases: [
      { input: '10\n3\n+', expected_output: '13.0', is_hidden: false },
      { input: '10\n3\n/', expected_output: '3.33', is_hidden: false },
      { input: '5\n0\n/', expected_output: 'Loi: chia cho 0', is_hidden: false },
      { input: '4\n2\n^', expected_output: 'Phep toan khong hop le', is_hidden: true },
    ],
    hints: ['Dùng if/elif/elif/elif/else cho từng phép toán', 'Kiểm tra b == 0 trước khi chia', 'round(kq, 2) để làm tròn'],
    order_index: 3,
    xp_reward: 25,
  },

  // --- Lesson 14: Lồng if ---
  {
    id: 40,
    lesson_id: 14,
    title: 'Phân loại tam giác theo cạnh',
    description: 'Cho ba cạnh a, b, c của tam giác (3 số nguyên dương, mỗi số trên một dòng). Kiểm tra:\n1. Nếu không tạo thành tam giác (tổng 2 cạnh bất kỳ <= cạnh còn lại), in "Khong la tam giac"\n2. Nếu là tam giác đều (3 cạnh bằng nhau), in "Tam giac deu"\n3. Nếu là tam giác cân (2 cạnh bằng nhau), in "Tam giac can"\n4. Còn lại, in "Tam giac thuong"',
    difficulty: 'easy',
    starter_code: 'a = int(input())\nb = int(input())\nc = int(input())\n# Phan loai tam giac\n',
    test_cases: [
      { input: '3\n3\n3', expected_output: 'Tam giac deu', is_hidden: false },
      { input: '3\n3\n5', expected_output: 'Tam giac can', is_hidden: false },
      { input: '3\n4\n5', expected_output: 'Tam giac thuong', is_hidden: false },
      { input: '1\n2\n5', expected_output: 'Khong la tam giac', is_hidden: true },
    ],
    hints: ['Điều kiện tam giác: a + b > c và a + c > b và b + c > a', 'Kiểm tra tam giác trước, rồi mới phân loại', 'Tam giác đều: a == b == c'],
    order_index: 1,
    xp_reward: 15,
  },
  {
    id: 41,
    lesson_id: 14,
    title: 'Tính chỉ số BMI',
    description: 'Cho cân nặng (kg, số thực) và chiều cao (m, số thực). Tính BMI = cân nặng / (chiều cao²).\nPhân loại:\n- BMI < 18.5: "Gay"\n- 18.5 <= BMI < 25: "Binh thuong"\n- 25 <= BMI < 30: "Thua can"\n- BMI >= 30: "Beo phi"\nIn ra BMI (làm tròn 1 chữ số) và phân loại trên 2 dòng.',
    difficulty: 'medium',
    starter_code: 'can_nang = float(input())\nchieu_cao = float(input())\n# Tinh BMI va phan loai\n',
    test_cases: [
      { input: '50\n1.6', expected_output: '19.5\nBinh thuong', is_hidden: false },
      { input: '45\n1.7', expected_output: '15.6\nGay', is_hidden: false },
      { input: '90\n1.7', expected_output: '31.1\nBeo phi', is_hidden: false },
      { input: '80\n1.75', expected_output: '26.1\nThua can', is_hidden: true },
    ],
    hints: ['BMI = can_nang / (chieu_cao ** 2)', 'Dùng round(bmi, 1)', 'Dùng if/elif/elif/else để phân loại'],
    order_index: 2,
    xp_reward: 20,
  },
  {
    id: 42,
    lesson_id: 14,
    title: 'Giải phương trình bậc hai',
    description: 'Cho 3 hệ số a, b, c (số thực, mỗi số trên một dòng) của phương trình ax² + bx + c = 0 (a ≠ 0).\nTính delta = b² - 4ac.\n- Nếu delta < 0: in "Vo nghiem"\n- Nếu delta = 0: in "Nghiem kep: x = [giá trị]" (làm tròn 2 chữ số)\n- Nếu delta > 0: in "x1 = [giá trị]" và "x2 = [giá trị]" trên 2 dòng (x1 < x2, làm tròn 2 chữ số)',
    difficulty: 'hard',
    starter_code: 'import math\na = float(input())\nb = float(input())\nc = float(input())\n# Giai phuong trinh bac hai\n',
    test_cases: [
      { input: '1\n-3\n2', expected_output: 'x1 = 1.0\nx2 = 2.0', is_hidden: false },
      { input: '1\n-2\n1', expected_output: 'Nghiem kep: x = 1.0', is_hidden: false },
      { input: '1\n1\n1', expected_output: 'Vo nghiem', is_hidden: false },
      { input: '2\n-7\n3', expected_output: 'x1 = 0.5\nx2 = 3.0', is_hidden: true },
    ],
    hints: ['delta = b**2 - 4*a*c', 'Nghiệm kép: x = -b / (2*a)', 'Hai nghiệm: x1 = (-b - sqrt(delta)) / (2*a)', 'Đảm bảo x1 < x2 bằng cách dùng min/max'],
    order_index: 3,
    xp_reward: 30,
  },

  // --- Lesson 15: Toán tử ba ngôi ---
  {
    id: 43,
    lesson_id: 15,
    title: 'Giá trị tuyệt đối bằng ternary',
    description: 'Cho số nguyên n. Dùng toán tử ba ngôi (ternary) để in ra giá trị tuyệt đối của n.\nYêu cầu: viết trong MỘT dòng lệnh print.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# In gia tri tuyet doi bang toan tu ba ngoi\n# Goi y: print(... if ... else ...)\n',
    test_cases: [
      { input: '-7', expected_output: '7', is_hidden: false },
      { input: '3', expected_output: '3', is_hidden: false },
      { input: '0', expected_output: '0', is_hidden: true },
    ],
    hints: ['Cú pháp: giá_trị_đúng if điều_kiện else giá_trị_sai', 'print(n if n >= 0 else -n)'],
    order_index: 1,
    xp_reward: 10,
  },
  {
    id: 44,
    lesson_id: 15,
    title: 'Tìm min của hai số bằng ternary',
    description: 'Cho hai số nguyên a và b (mỗi số trên một dòng). Dùng toán tử ba ngôi để tìm và in ra số nhỏ hơn.',
    difficulty: 'medium',
    starter_code: 'a = int(input())\nb = int(input())\n# Tim min bang toan tu ba ngoi\n',
    test_cases: [
      { input: '3\n7', expected_output: '3', is_hidden: false },
      { input: '10\n2', expected_output: '2', is_hidden: false },
      { input: '5\n5', expected_output: '5', is_hidden: true },
    ],
    hints: ['print(a if a < b else b)', 'Hoặc dùng min(a, b) nhưng bài yêu cầu ternary'],
    order_index: 2,
    xp_reward: 15,
  },
  {
    id: 45,
    lesson_id: 15,
    title: 'Phân loại điểm bằng ternary lồng',
    description: 'Cho điểm (số thực). Dùng toán tử ba ngôi lồng nhau để in:\n- "Gioi" nếu điểm >= 8\n- "Kha" nếu điểm >= 6.5\n- "TB" nếu điểm >= 5\n- "Yeu" nếu điểm < 5\nViết trong MỘT dòng print.',
    difficulty: 'hard',
    starter_code: 'diem = float(input())\n# Phan loai bang ternary long\n# print("Gioi" if ... else "Kha" if ... else ...)\n',
    test_cases: [
      { input: '9.0', expected_output: 'Gioi', is_hidden: false },
      { input: '7.0', expected_output: 'Kha', is_hidden: false },
      { input: '5.5', expected_output: 'TB', is_hidden: false },
      { input: '4.0', expected_output: 'Yeu', is_hidden: true },
    ],
    hints: ['Ternary lồng: a if cond1 else b if cond2 else c if cond3 else d', 'print("Gioi" if diem >= 8 else "Kha" if diem >= 6.5 else "TB" if diem >= 5 else "Yeu")'],
    order_index: 3,
    xp_reward: 25,
  },

  // ============================================================
  // BÀI TẬP BỔ SUNG - Mỗi lesson thêm 2 bài (exercises 46-75)
  // ============================================================

  // --- Lesson 1 bổ sung ---
  {
    id: 46,
    lesson_id: 1,
    title: 'In số và chuỗi',
    description: 'Viết chương trình in ra 2 dòng:\nDòng 1: "So yeu thich: 7"\nDòng 2: "Mon hoc: Tin hoc"',
    difficulty: 'easy',
    starter_code: '# In ra 2 dong theo yeu cau\n',
    test_cases: [
      { input: '', expected_output: 'So yeu thich: 7\nMon hoc: Tin hoc', is_hidden: false },
    ],
    hints: ['Dùng 2 lệnh print()', 'print("So yeu thich: 7")'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 47,
    lesson_id: 1,
    title: 'In tam giác sao',
    description: 'Viết chương trình in ra tam giác vuông bằng dấu * với 4 dòng:\n*\n**\n***\n****',
    difficulty: 'medium',
    starter_code: '# In tam giac vuong 4 dong\n',
    test_cases: [
      { input: '', expected_output: '*\n**\n***\n****', is_hidden: false },
    ],
    hints: ['Mỗi dòng i có i dấu *', 'print("*" * i) với i từ 1 đến 4'],
    order_index: 5,
    xp_reward: 15,
  },

  // --- Lesson 2 bổ sung ---
  {
    id: 48,
    lesson_id: 2,
    title: 'Tính tuổi từ năm sinh',
    description: 'Cho năm sinh (số nguyên). Tính tuổi hiện tại (giả sử năm hiện tại là 2024) và in ra.\nVí dụ: năm sinh 2006 → tuổi 18.',
    difficulty: 'easy',
    starter_code: 'nam_sinh = int(input())\n# Tinh tuoi (nam hien tai = 2024)\n',
    test_cases: [
      { input: '2006', expected_output: '18', is_hidden: false },
      { input: '2000', expected_output: '24', is_hidden: false },
      { input: '1990', expected_output: '34', is_hidden: true },
    ],
    hints: ['tuoi = 2024 - nam_sinh', 'print(tuoi)'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 49,
    lesson_id: 2,
    title: 'Gán nhiều biến cùng lúc',
    description: 'Cho 3 số nguyên trên 3 dòng. Gán vào 3 biến x, y, z rồi in ra tổng, trung bình cộng (làm tròn 2 chữ số) trên 2 dòng.',
    difficulty: 'medium',
    starter_code: 'x = int(input())\ny = int(input())\nz = int(input())\n# Tinh tong va trung binh\n',
    test_cases: [
      { input: '3\n6\n9', expected_output: '18\n6.0', is_hidden: false },
      { input: '1\n2\n3', expected_output: '6\n2.0', is_hidden: false },
      { input: '10\n20\n30', expected_output: '60\n20.0', is_hidden: true },
    ],
    hints: ['tong = x + y + z', 'tb = tong / 3', 'round(tb, 2)'],
    order_index: 5,
    xp_reward: 15,
  },

  // --- Lesson 3 bổ sung ---
  {
    id: 50,
    lesson_id: 3,
    title: 'Nhập và in ngày tháng',
    description: 'Nhập ngày (số nguyên), tháng (số nguyên), năm (số nguyên) trên 3 dòng. In ra theo định dạng: "dd/mm/yyyy" (ngày và tháng luôn có 2 chữ số, năm 4 chữ số).\nVí dụ: 5, 3, 2024 → "05/03/2024"',
    difficulty: 'medium',
    starter_code: 'ngay = int(input())\nthang = int(input())\nnam = int(input())\n# In theo dinh dang dd/mm/yyyy\n',
    test_cases: [
      { input: '5\n3\n2024', expected_output: '05/03/2024', is_hidden: false },
      { input: '15\n12\n2000', expected_output: '15/12/2000', is_hidden: false },
      { input: '1\n1\n2025', expected_output: '01/01/2025', is_hidden: true },
    ],
    hints: ['Dùng f-string với format: f"{ngay:02d}/{thang:02d}/{nam:04d}"', ':02d nghĩa là in số nguyên với ít nhất 2 chữ số, thêm 0 phía trước nếu cần'],
    order_index: 4,
    xp_reward: 15,
  },
  {
    id: 51,
    lesson_id: 3,
    title: 'Tính giây thành giờ phút giây',
    description: 'Cho tổng số giây (số nguyên dương). Chuyển đổi sang giờ, phút, giây và in theo định dạng: "HH:MM:SS" (mỗi thành phần 2 chữ số).\nVí dụ: 3661 giây → "01:01:01"',
    difficulty: 'hard',
    starter_code: 'tong_giay = int(input())\n# Chuyen doi sang gio:phut:giay\n',
    test_cases: [
      { input: '3661', expected_output: '01:01:01', is_hidden: false },
      { input: '7200', expected_output: '02:00:00', is_hidden: false },
      { input: '90', expected_output: '00:01:30', is_hidden: true },
    ],
    hints: ['gio = tong_giay // 3600', 'phut = (tong_giay % 3600) // 60', 'giay = tong_giay % 60', 'f"{gio:02d}:{phut:02d}:{giay:02d}"'],
    order_index: 5,
    xp_reward: 20,
  },

  // --- Lesson 4 bổ sung ---
  {
    id: 52,
    lesson_id: 4,
    title: 'Tính chu vi và diện tích hình chữ nhật',
    description: 'Cho chiều dài a và chiều rộng b (2 số nguyên dương, mỗi số trên một dòng). In ra chu vi và diện tích trên 2 dòng.',
    difficulty: 'easy',
    starter_code: 'a = int(input())\nb = int(input())\n# Tinh chu vi va dien tich\n',
    test_cases: [
      { input: '5\n3', expected_output: '16\n15', is_hidden: false },
      { input: '10\n4', expected_output: '28\n40', is_hidden: false },
      { input: '7\n7', expected_output: '28\n49', is_hidden: true },
    ],
    hints: ['Chu vi = 2 * (a + b)', 'Diện tích = a * b'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 53,
    lesson_id: 4,
    title: 'Đổi tiền',
    description: 'Cho một số tiền bằng VND (số nguyên dương). Đổi sang USD với tỷ giá 1 USD = 24500 VND. In ra số USD làm tròn 2 chữ số thập phân.',
    difficulty: 'medium',
    starter_code: 'vnd = int(input())\n# Doi sang USD (ty gia 24500)\n',
    test_cases: [
      { input: '49000', expected_output: '2.0', is_hidden: false },
      { input: '100000', expected_output: '4.08', is_hidden: false },
      { input: '1000000', expected_output: '40.82', is_hidden: true },
    ],
    hints: ['usd = vnd / 24500', 'round(usd, 2)'],
    order_index: 5,
    xp_reward: 15,
  },

  // --- Lesson 5 bổ sung ---
  {
    id: 54,
    lesson_id: 5,
    title: 'Chữ hoa và chữ thường',
    description: 'Nhập một chuỗi. In ra 2 dòng:\nDòng 1: chuỗi viết HOA toàn bộ\nDòng 2: chuỗi viết thường toàn bộ',
    difficulty: 'easy',
    starter_code: 's = input()\n# In ra chu hoa va chu thuong\n',
    test_cases: [
      { input: 'Hello World', expected_output: 'HELLO WORLD\nhello world', is_hidden: false },
      { input: 'Python', expected_output: 'PYTHON\npython', is_hidden: false },
      { input: 'ABC def', expected_output: 'ABC DEF\nabc def', is_hidden: true },
    ],
    hints: ['s.upper() chuyển thành chữ hoa', 's.lower() chuyển thành chữ thường'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 55,
    lesson_id: 5,
    title: 'Cắt chuỗi theo vị trí',
    description: 'Nhập chuỗi s (dòng 1) và số nguyên n (dòng 2). In ra n ký tự đầu tiên của chuỗi.\nNếu n lớn hơn độ dài chuỗi, in ra toàn bộ chuỗi.',
    difficulty: 'medium',
    starter_code: 's = input()\nn = int(input())\n# In ra n ky tu dau tien\n',
    test_cases: [
      { input: 'Hello World\n5', expected_output: 'Hello', is_hidden: false },
      { input: 'Python\n3', expected_output: 'Pyt', is_hidden: false },
      { input: 'Hi\n10', expected_output: 'Hi', is_hidden: true },
    ],
    hints: ['Dùng slicing: s[:n]', 'Python tự xử lý khi n > len(s)'],
    order_index: 5,
    xp_reward: 15,
  },

  // --- Lesson 6 bổ sung ---
  {
    id: 56,
    lesson_id: 6,
    title: 'So sánh bằng và khác',
    description: 'Cho hai chuỗi s1 và s2 (mỗi chuỗi trên một dòng). In "Bang nhau" nếu hai chuỗi giống hệt nhau, ngược lại in "Khac nhau".',
    difficulty: 'easy',
    starter_code: 's1 = input()\ns2 = input()\n# So sanh hai chuoi\n',
    test_cases: [
      { input: 'hello\nhello', expected_output: 'Bang nhau', is_hidden: false },
      { input: 'Hello\nhello', expected_output: 'Khac nhau', is_hidden: false },
      { input: 'abc\nabc', expected_output: 'Bang nhau', is_hidden: true },
    ],
    hints: ['Dùng toán tử == để so sánh chuỗi', 'Python phân biệt chữ hoa/thường'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 57,
    lesson_id: 6,
    title: 'Sắp xếp 3 số tăng dần',
    description: 'Cho 3 số nguyên a, b, c (mỗi số trên một dòng). In ra 3 số theo thứ tự tăng dần, cách nhau bởi dấu cách.',
    difficulty: 'hard',
    starter_code: 'a = int(input())\nb = int(input())\nc = int(input())\n# Sap xep tang dan va in ra\n',
    test_cases: [
      { input: '3\n1\n2', expected_output: '1 2 3', is_hidden: false },
      { input: '5\n5\n3', expected_output: '3 5 5', is_hidden: false },
      { input: '10\n-1\n7', expected_output: '-1 7 10', is_hidden: true },
    ],
    hints: ['Dùng sorted([a, b, c])', 'Hoặc dùng min, max và tính số giữa', 'In cách nhau bởi dấu cách: print(*sorted([a,b,c]))'],
    order_index: 5,
    xp_reward: 20,
  },

  // --- Lesson 7 bổ sung ---
  {
    id: 58,
    lesson_id: 7,
    title: 'Kiểm tra ký tự là chữ cái',
    description: 'Nhập một ký tự. Kiểm tra xem nó có phải là chữ cái (a-z hoặc A-Z) hay không. In "True" hoặc "False".',
    difficulty: 'easy',
    starter_code: 'c = input()\n# Kiem tra c co phai chu cai khong\n',
    test_cases: [
      { input: 'A', expected_output: 'True', is_hidden: false },
      { input: '5', expected_output: 'False', is_hidden: false },
      { input: 'z', expected_output: 'True', is_hidden: false },
      { input: '@', expected_output: 'False', is_hidden: true },
    ],
    hints: ['Dùng phương thức .isalpha()', 'print(c.isalpha())'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 59,
    lesson_id: 7,
    title: 'Kiểm tra tam giác vuông',
    description: 'Cho 3 cạnh a, b, c (số nguyên dương, mỗi số trên một dòng). Kiểm tra xem 3 cạnh có tạo thành tam giác vuông hay không (theo định lý Pythagore). In "True" hoặc "False".\nLưu ý: cạnh huyền là cạnh lớn nhất.',
    difficulty: 'hard',
    starter_code: 'a = int(input())\nb = int(input())\nc = int(input())\n# Kiem tra tam giac vuong\n',
    test_cases: [
      { input: '3\n4\n5', expected_output: 'True', is_hidden: false },
      { input: '5\n12\n13', expected_output: 'True', is_hidden: false },
      { input: '3\n4\n6', expected_output: 'False', is_hidden: false },
      { input: '5\n3\n4', expected_output: 'True', is_hidden: true },
    ],
    hints: ['Tìm cạnh lớn nhất: canh_huyen = max(a, b, c)', 'Kiểm tra: a² + b² = c² (với c là cạnh lớn nhất)', 'Sắp xếp: sides = sorted([a, b, c])'],
    order_index: 5,
    xp_reward: 25,
  },

  // --- Lesson 8 bổ sung ---
  {
    id: 60,
    lesson_id: 8,
    title: 'Chuyển boolean sang chuỗi',
    description: 'Cho một số nguyên n. Nếu n != 0, nó được coi là True; nếu n == 0, nó là False. In ra "True" hoặc "False" tương ứng bằng cách ép kiểu bool.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Ep kieu sang bool va in ra\n',
    test_cases: [
      { input: '5', expected_output: 'True', is_hidden: false },
      { input: '0', expected_output: 'False', is_hidden: false },
      { input: '-1', expected_output: 'True', is_hidden: true },
    ],
    hints: ['bool(0) = False, bool(khác 0) = True', 'print(bool(n))'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 61,
    lesson_id: 8,
    title: 'Tách phần nguyên và phần thập phân',
    description: 'Cho một số thực dương (nhập dưới dạng chuỗi, ví dụ "3.14"). Tách và in ra phần nguyên (dòng 1) và phần thập phân dưới dạng chuỗi (dòng 2, không có dấu chấm).\nVí dụ: "3.14" → in "3" và "14".',
    difficulty: 'medium',
    starter_code: 's = input()\n# Tach phan nguyen va phan thap phan\n',
    test_cases: [
      { input: '3.14', expected_output: '3\n14', is_hidden: false },
      { input: '10.5', expected_output: '10\n5', is_hidden: false },
      { input: '0.123', expected_output: '0\n123', is_hidden: true },
    ],
    hints: ['Dùng split(".") để tách chuỗi', 'parts = s.split(".")', 'print(parts[0]) và print(parts[1])'],
    order_index: 5,
    xp_reward: 15,
  },

  // --- Lesson 9 bổ sung ---
  {
    id: 62,
    lesson_id: 9,
    title: 'Làm tròn số',
    description: 'Cho một số thực x. In ra 3 dòng:\nDòng 1: x làm tròn đến hàng đơn vị (0 chữ số thập phân)\nDòng 2: x làm tròn 1 chữ số thập phân\nDòng 3: x làm tròn 3 chữ số thập phân',
    difficulty: 'easy',
    starter_code: 'x = float(input())\n# Lam tron x theo cac muc khac nhau\n',
    test_cases: [
      { input: '3.14159', expected_output: '3\n3.1\n3.142', is_hidden: false },
      { input: '2.71828', expected_output: '3\n2.7\n2.718', is_hidden: false },
      { input: '9.9999', expected_output: '10\n10.0\n10.0', is_hidden: true },
    ],
    hints: ['round(x, 0) hoặc round(x)', 'round(x, 1)', 'round(x, 3)', 'In round(x) dưới dạng int: int(round(x))'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 63,
    lesson_id: 9,
    title: 'Tính thể tích hình cầu',
    description: 'Cho bán kính r (số thực dương). Tính thể tích hình cầu V = (4/3) × π × r³. In kết quả làm tròn 2 chữ số thập phân.',
    difficulty: 'hard',
    starter_code: 'import math\nr = float(input())\n# Tinh the tich hinh cau\n',
    test_cases: [
      { input: '1', expected_output: '4.19', is_hidden: false },
      { input: '3', expected_output: '113.1', is_hidden: false },
      { input: '5', expected_output: '523.6', is_hidden: true },
    ],
    hints: ['V = (4/3) * math.pi * r**3', 'round(V, 2)', 'Chú ý: 4/3 trong Python 3 cho kết quả float'],
    order_index: 5,
    xp_reward: 20,
  },

  // --- Lesson 10 bổ sung ---
  {
    id: 64,
    lesson_id: 10,
    title: 'Tìm vị trí chuỗi con',
    description: 'Cho chuỗi s (dòng 1) và chuỗi con sub (dòng 2). Tìm vị trí xuất hiện đầu tiên của sub trong s. In ra chỉ số (bắt đầu từ 0). Nếu không tìm thấy, in -1.',
    difficulty: 'easy',
    starter_code: 's = input()\nsub = input()\n# Tim vi tri xuat hien dau tien cua sub trong s\n',
    test_cases: [
      { input: 'Hello World\nWorld', expected_output: '6', is_hidden: false },
      { input: 'Python\nJava', expected_output: '-1', is_hidden: false },
      { input: 'banana\nan', expected_output: '1', is_hidden: true },
    ],
    hints: ['Dùng phương thức .find()', 's.find(sub) trả về -1 nếu không tìm thấy'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 65,
    lesson_id: 10,
    title: 'Kiểm tra palindrome',
    description: 'Nhập một chuỗi (chỉ chứa chữ cái thường). Kiểm tra xem chuỗi có phải là palindrome (đọc xuôi ngược giống nhau) hay không. In "True" hoặc "False".',
    difficulty: 'hard',
    starter_code: 's = input()\n# Kiem tra palindrome\n',
    test_cases: [
      { input: 'madam', expected_output: 'True', is_hidden: false },
      { input: 'hello', expected_output: 'False', is_hidden: false },
      { input: 'abcba', expected_output: 'True', is_hidden: false },
      { input: 'a', expected_output: 'True', is_hidden: true },
    ],
    hints: ['Palindrome: chuỗi đọc ngược giống đọc xuôi', 'So sánh s với s[::-1]', 'print(s == s[::-1])'],
    order_index: 5,
    xp_reward: 20,
  },

  // --- Lesson 11 bổ sung ---
  {
    id: 66,
    lesson_id: 11,
    title: 'Kiểm tra số hoàn hảo đơn giản',
    description: 'Cho số nguyên dương n. Nếu n bằng 6 hoặc n bằng 28, in "So hoan hao". Ngược lại in "Khong phai".\n(Số hoàn hảo là số bằng tổng các ước thực sự của nó)',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# Kiem tra so hoan hao (don gian: chi kiem tra 6 va 28)\n',
    test_cases: [
      { input: '6', expected_output: 'So hoan hao', is_hidden: false },
      { input: '28', expected_output: 'So hoan hao', is_hidden: false },
      { input: '12', expected_output: 'Khong phai', is_hidden: false },
      { input: '1', expected_output: 'Khong phai', is_hidden: true },
    ],
    hints: ['Dùng if n == 6 or n == 28:', 'Đây là bài đơn giản, chỉ kiểm tra 2 giá trị'],
    order_index: 4,
    xp_reward: 15,
  },
  {
    id: 67,
    lesson_id: 11,
    title: 'Kiểm tra ký tự đặc biệt',
    description: 'Nhập một ký tự. Kiểm tra:\n- Nếu là chữ số (0-9): in "Chu so"\n- Nếu là chữ cái: in "Chu cai"\n- Nếu là khoảng trắng: in "Khoang trang"\n- Còn lại: in "Ky tu dac biet"',
    difficulty: 'hard',
    starter_code: 'c = input()\n# Phan loai ky tu\n',
    test_cases: [
      { input: '5', expected_output: 'Chu so', is_hidden: false },
      { input: 'A', expected_output: 'Chu cai', is_hidden: false },
      { input: ' ', expected_output: 'Khoang trang', is_hidden: false },
      { input: '@', expected_output: 'Ky tu dac biet', is_hidden: true },
    ],
    hints: ['c.isdigit() kiểm tra chữ số', 'c.isalpha() kiểm tra chữ cái', 'c == " " kiểm tra khoảng trắng'],
    order_index: 5,
    xp_reward: 20,
  },

  // --- Lesson 12 bổ sung ---
  {
    id: 68,
    lesson_id: 12,
    title: 'Kiểm tra năm sinh hợp lệ',
    description: 'Cho năm sinh (số nguyên). Nếu năm sinh nằm trong khoảng 1900-2024, in "Hop le". Ngược lại in "Khong hop le".',
    difficulty: 'easy',
    starter_code: 'nam = int(input())\n# Kiem tra nam sinh hop le\n',
    test_cases: [
      { input: '2000', expected_output: 'Hop le', is_hidden: false },
      { input: '1850', expected_output: 'Khong hop le', is_hidden: false },
      { input: '2025', expected_output: 'Khong hop le', is_hidden: true },
    ],
    hints: ['if 1900 <= nam <= 2024:', 'else: in "Khong hop le"'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 69,
    lesson_id: 12,
    title: 'Tính tiền điện',
    description: 'Cho số kWh điện tiêu thụ (số nguyên dương). Tính tiền điện:\n- 50 kWh đầu: 1678 đ/kWh\n- 51-100 kWh: 1734 đ/kWh\n- Trên 100 kWh: 2014 đ/kWh\nIn ra tổng tiền (số nguyên).',
    difficulty: 'hard',
    starter_code: 'kwh = int(input())\n# Tinh tien dien theo bac thang\n',
    test_cases: [
      { input: '30', expected_output: '50340', is_hidden: false },
      { input: '80', expected_output: '135920', is_hidden: false },
      { input: '150', expected_output: '271400', is_hidden: true },
    ],
    hints: ['Nếu kwh <= 50: tien = kwh * 1678', 'Nếu kwh <= 100: tien = 50*1678 + (kwh-50)*1734', 'Nếu kwh > 100: tien = 50*1678 + 50*1734 + (kwh-100)*2014'],
    order_index: 5,
    xp_reward: 25,
  },

  // --- Lesson 13 bổ sung ---
  {
    id: 70,
    lesson_id: 13,
    title: 'Phân loại tuổi',
    description: 'Cho tuổi (số nguyên dương). Phân loại:\n- 0-2: "So sinh"\n- 3-12: "Thieu nhi"\n- 13-17: "Thieu nien"\n- 18-64: "Nguoi lon"\n- >= 65: "Nguoi gia"\nIn ra phân loại tương ứng.',
    difficulty: 'medium',
    starter_code: 'tuoi = int(input())\n# Phan loai theo tuoi\n',
    test_cases: [
      { input: '1', expected_output: 'So sinh', is_hidden: false },
      { input: '10', expected_output: 'Thieu nhi', is_hidden: false },
      { input: '16', expected_output: 'Thieu nien', is_hidden: false },
      { input: '30', expected_output: 'Nguoi lon', is_hidden: false },
      { input: '70', expected_output: 'Nguoi gia', is_hidden: true },
    ],
    hints: ['Dùng if/elif/elif/elif/else', 'Kiểm tra từ nhỏ đến lớn hoặc từ lớn đến nhỏ'],
    order_index: 4,
    xp_reward: 15,
  },
  {
    id: 71,
    lesson_id: 13,
    title: 'Chuyển điểm số sang chữ (GPA)',
    description: 'Cho điểm số (số thực 0-4.0). Chuyển sang xếp loại chữ:\n- >= 3.6: "A"\n- >= 3.2: "B+"\n- >= 2.5: "B"\n- >= 2.0: "C"\n- >= 1.0: "D"\n- < 1.0: "F"\nIn ra xếp loại.',
    difficulty: 'hard',
    starter_code: 'gpa = float(input())\n# Chuyen GPA sang xep loai chu\n',
    test_cases: [
      { input: '3.8', expected_output: 'A', is_hidden: false },
      { input: '3.3', expected_output: 'B+', is_hidden: false },
      { input: '2.7', expected_output: 'B', is_hidden: false },
      { input: '1.5', expected_output: 'D', is_hidden: false },
      { input: '0.5', expected_output: 'F', is_hidden: true },
    ],
    hints: ['Dùng if/elif/elif/.../else', 'Kiểm tra từ cao xuống thấp', 'Chú ý: >= 3.6 trước, rồi >= 3.2, ...'],
    order_index: 5,
    xp_reward: 25,
  },

  // --- Lesson 14 bổ sung ---
  {
    id: 72,
    lesson_id: 14,
    title: 'Kiểm tra ngày hợp lệ',
    description: 'Cho ngày (dòng 1) và tháng (dòng 2) là số nguyên. Kiểm tra xem ngày/tháng có hợp lệ không (năm không nhuận).\n- Tháng 1-12, ngày phải phù hợp với tháng\n- Tháng 2: 1-28, tháng 4/6/9/11: 1-30, còn lại: 1-31\nIn "Hop le" hoặc "Khong hop le".',
    difficulty: 'medium',
    starter_code: 'ngay = int(input())\nthang = int(input())\n# Kiem tra ngay/thang hop le\n',
    test_cases: [
      { input: '15\n6', expected_output: 'Hop le', is_hidden: false },
      { input: '31\n4', expected_output: 'Khong hop le', is_hidden: false },
      { input: '29\n2', expected_output: 'Khong hop le', is_hidden: false },
      { input: '28\n2', expected_output: 'Hop le', is_hidden: true },
    ],
    hints: ['Kiểm tra tháng hợp lệ trước (1-12)', 'Xác định số ngày tối đa của tháng', 'Dùng if lồng nhau hoặc biến max_ngay'],
    order_index: 4,
    xp_reward: 20,
  },
  {
    id: 73,
    lesson_id: 14,
    title: 'Xếp loại học sinh toàn diện',
    description: 'Cho điểm Toán, Văn, Anh (3 số thực, mỗi số trên một dòng). Tính điểm trung bình.\nXếp loại:\n- TB >= 8 VÀ không có môn nào < 6.5: "Hoc sinh gioi"\n- TB >= 6.5 VÀ không có môn nào < 5: "Hoc sinh kha"\n- TB >= 5 VÀ không có môn nào < 3.5: "Hoc sinh trung binh"\n- Còn lại: "Hoc sinh yeu"\nIn điểm TB (làm tròn 1 chữ số) dòng 1, xếp loại dòng 2.',
    difficulty: 'hard',
    starter_code: 'toan = float(input())\nvan = float(input())\nanh = float(input())\n# Tinh TB va xep loai\n',
    test_cases: [
      { input: '9.0\n8.5\n8.0', expected_output: '8.5\nHoc sinh gioi', is_hidden: false },
      { input: '7.0\n6.5\n7.5', expected_output: '7.0\nHoc sinh kha', is_hidden: false },
      { input: '5.0\n5.5\n4.0', expected_output: '4.8\nHoc sinh yeu', is_hidden: false },
      { input: '8.0\n9.0\n6.0', expected_output: '7.7\nHoc sinh kha', is_hidden: true },
    ],
    hints: ['tb = (toan + van + anh) / 3', 'min_diem = min(toan, van, anh)', 'Kiểm tra cả TB và điểm thấp nhất'],
    order_index: 5,
    xp_reward: 30,
  },

  // --- Lesson 15 bổ sung ---
  {
    id: 74,
    lesson_id: 15,
    title: 'Số chẵn lẻ bằng ternary',
    description: 'Cho số nguyên n. Dùng toán tử ba ngôi in ra "Chan" nếu n chẵn, "Le" nếu n lẻ. Viết trong MỘT dòng print.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# In Chan/Le bang ternary\n',
    test_cases: [
      { input: '4', expected_output: 'Chan', is_hidden: false },
      { input: '7', expected_output: 'Le', is_hidden: false },
      { input: '0', expected_output: 'Chan', is_hidden: true },
    ],
    hints: ['print("Chan" if n % 2 == 0 else "Le")', 'Toán tử ba ngôi: giá_trị_đúng if điều_kiện else giá_trị_sai'],
    order_index: 4,
    xp_reward: 10,
  },
  {
    id: 75,
    lesson_id: 15,
    title: 'Clamp giá trị trong khoảng',
    description: 'Cho 3 số nguyên: giá trị val, giới hạn dưới low, giới hạn trên high (mỗi số trên một dòng). Dùng toán tử ba ngôi lồng để "clamp" val vào khoảng [low, high]:\n- Nếu val < low → in low\n- Nếu val > high → in high\n- Còn lại → in val\nViết trong MỘT dòng print.',
    difficulty: 'hard',
    starter_code: 'val = int(input())\nlow = int(input())\nhigh = int(input())\n# Clamp val vao khoang [low, high] bang ternary\n',
    test_cases: [
      { input: '5\n1\n10', expected_output: '5', is_hidden: false },
      { input: '-3\n0\n100', expected_output: '0', is_hidden: false },
      { input: '150\n0\n100', expected_output: '100', is_hidden: false },
      { input: '50\n50\n50', expected_output: '50', is_hidden: true },
    ],
    hints: ['Ternary lồng: low if val < low else high if val > high else val', 'Hoặc dùng max(low, min(val, high))'],
    order_index: 5,
    xp_reward: 25,
  },
];
