/**
 * Exercise content part 2: exercises 76-150 (levels 4-10).
 */

import type { ExerciseContent } from './exercise-content';

export const EXERCISES_PART2: ExerciseContent[] = [
  // ===== LEVEL 4: Vòng lặp (Lessons 16-20) =====
  // Lesson 16: for + range
  {
    id: 76,
    lesson_id: 16,
    title: 'Tính tổng 1 đến N',
    description: 'Cho số nguyên dương N. Tính tổng S = 1 + 2 + ... + N và in ra kết quả.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Tính tổng từ 1 đến n\n',
    test_cases: [
      { input: '5', expected_output: '15', is_hidden: false },
      { input: '100', expected_output: '5050', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: true },
    ],
    hints: ['Dùng vòng for với range(1, n+1)', 'Hoặc công thức n*(n+1)//2'],
    order_index: 1,
  },
  {
    id: 77,
    lesson_id: 16,
    title: 'In hình tam giác số',
    description: 'Cho số nguyên dương N. In hình tam giác số với N hàng.\nHàng 1: 1\nHàng 2: 1 2\nHàng 3: 1 2 3\n...\nHàng N: 1 2 ... N\nCác số cách nhau bởi dấu cách.',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# In hình tam giác số\n',
    test_cases: [
      { input: '3', expected_output: '1\n1 2\n1 2 3', is_hidden: false },
      { input: '5', expected_output: '1\n1 2\n1 2 3\n1 2 3 4\n1 2 3 4 5', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: true },
    ],
    hints: ['Dùng 2 vòng for lồng nhau', 'Vòng ngoài chạy từ 1 đến n, vòng trong in các số'],
    order_index: 2,
  },
  {
    id: 78,
    lesson_id: 16,
    title: 'Đếm ước số',
    description: 'Cho số nguyên dương N. Đếm số lượng ước số của N (bao gồm 1 và N).',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Đếm số ước của n\n',
    test_cases: [
      { input: '12', expected_output: '6', is_hidden: false },
      { input: '7', expected_output: '2', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: true },
    ],
    hints: ['Duyệt từ 1 đến n, đếm số i mà n % i == 0', 'Tối ưu: chỉ cần duyệt đến sqrt(n)'],
    order_index: 3,
  },

  // Lesson 17: while
  {
    id: 79,
    lesson_id: 17,
    title: 'Tính tổng cho đến khi nhập 0',
    description: 'Nhập liên tiếp các số nguyên (mỗi số 1 dòng). Khi nhập 0 thì dừng. In ra tổng các số đã nhập (không tính số 0).',
    difficulty: 'easy',
    starter_code: '# Tính tổng cho đến khi nhập 0\ntong = 0\n# Viết vòng while\n',
    test_cases: [
      { input: '3\n5\n2\n0', expected_output: '10', is_hidden: false },
      { input: '10\n-3\n0', expected_output: '7', is_hidden: false },
      { input: '0', expected_output: '0', is_hidden: true },
    ],
    hints: ['Dùng while True và break khi nhập 0', 'Hoặc đọc số trước, while n != 0'],
    order_index: 1,
  },
  {
    id: 80,
    lesson_id: 17,
    title: 'Đếm chữ số',
    description: 'Cho số nguyên dương N. Đếm số lượng chữ số của N. Ví dụ N=1234 có 4 chữ số.',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# Đếm số chữ số\n',
    test_cases: [
      { input: '1234', expected_output: '4', is_hidden: false },
      { input: '100', expected_output: '3', is_hidden: false },
      { input: '7', expected_output: '1', is_hidden: true },
    ],
    hints: ['Chia n cho 10 liên tục cho đến khi n == 0', 'Mỗi lần chia, đếm tăng 1'],
    order_index: 2,
  },
  {
    id: 81,
    lesson_id: 17,
    title: 'Đếm bước Collatz',
    description: 'Cho số nguyên dương N. Thực hiện: nếu N chẵn thì N = N/2, nếu N lẻ thì N = 3*N + 1. Lặp cho đến khi N = 1. Đếm số bước thực hiện.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Đếm bước Collatz\n',
    test_cases: [
      { input: '6', expected_output: '8', is_hidden: false },
      { input: '1', expected_output: '0', is_hidden: false },
      { input: '27', expected_output: '111', is_hidden: true },
    ],
    hints: ['Dùng while n != 1', 'Nếu n chẵn: n //= 2, nếu lẻ: n = 3*n + 1', 'Đếm mỗi lần thực hiện'],
    order_index: 3,
  },

  // Lesson 18: break/continue
  {
    id: 82,
    lesson_id: 18,
    title: 'Tìm số nguyên tố đầu tiên lớn hơn N',
    description: 'Cho số nguyên dương N. Tìm và in ra số nguyên tố nhỏ nhất lớn hơn N.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Tìm số nguyên tố đầu tiên > n\n',
    test_cases: [
      { input: '10', expected_output: '11', is_hidden: false },
      { input: '14', expected_output: '17', is_hidden: false },
      { input: '1', expected_output: '2', is_hidden: true },
    ],
    hints: ['Bắt đầu từ n+1, kiểm tra từng số', 'Dùng break khi tìm thấy số nguyên tố'],
    order_index: 1,
  },
  {
    id: 83,
    lesson_id: 18,
    title: 'In số từ 1 đến N bỏ qua bội của 3',
    description: 'Cho số nguyên dương N. In các số từ 1 đến N trên cùng 1 dòng cách nhau bởi dấu cách, bỏ qua các số chia hết cho 3.',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# In số từ 1 đến n, bỏ qua bội của 3\n',
    test_cases: [
      { input: '10', expected_output: '1 2 4 5 7 8 10', is_hidden: false },
      { input: '6', expected_output: '1 2 4 5', is_hidden: false },
      { input: '3', expected_output: '1 2', is_hidden: true },
    ],
    hints: ['Dùng continue khi i % 3 == 0', 'Thu thập kết quả vào list rồi join'],
    order_index: 2,
  },
  {
    id: 84,
    lesson_id: 18,
    title: 'Mô phỏng nhập mật khẩu',
    description: 'Mật khẩu đúng là "python123". Cho phép nhập tối đa 3 lần. Nếu đúng in "Dang nhap thanh cong", nếu sai hết 3 lần in "Tai khoan bi khoa".',
    difficulty: 'hard',
    starter_code: '# Mô phỏng nhập mật khẩu\nmat_khau_dung = "python123"\n# Cho phép nhập tối đa 3 lần\n',
    test_cases: [
      { input: 'python123', expected_output: 'Dang nhap thanh cong', is_hidden: false },
      { input: 'abc\nxyz\npython123', expected_output: 'Dang nhap thanh cong', is_hidden: false },
      { input: 'a\nb\nc', expected_output: 'Tai khoan bi khoa', is_hidden: true },
    ],
    hints: ['Dùng vòng for range(3) hoặc while với biến đếm', 'Dùng break khi nhập đúng'],
    order_index: 3,
  },

  // Lesson 19: Vòng lặp lồng nhau
  {
    id: 85,
    lesson_id: 19,
    title: 'Bảng cửu chương',
    description: 'Cho số nguyên N (2 <= N <= 9). In bảng cửu chương của N từ 1 đến 10. Mỗi dòng có dạng "N x i = ket_qua".',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# In bảng cửu chương\n',
    test_cases: [
      { input: '2', expected_output: '2 x 1 = 2\n2 x 2 = 4\n2 x 3 = 6\n2 x 4 = 8\n2 x 5 = 10\n2 x 6 = 12\n2 x 7 = 14\n2 x 8 = 16\n2 x 9 = 18\n2 x 10 = 20', is_hidden: false },
      { input: '5', expected_output: '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50', is_hidden: true },
    ],
    hints: ['Dùng for i in range(1, 11)', 'In f"{n} x {i} = {n*i}"'],
    order_index: 1,
  },
  {
    id: 86,
    lesson_id: 19,
    title: 'In tam giác sao',
    description: 'Cho số nguyên dương N. In tam giác vuông bằng dấu * với N hàng.\nHàng 1: *\nHàng 2: **\n...\nHàng N: N dấu *',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# In tam giác sao\n',
    test_cases: [
      { input: '4', expected_output: '*\n**\n***\n****', is_hidden: false },
      { input: '3', expected_output: '*\n**\n***', is_hidden: false },
      { input: '1', expected_output: '*', is_hidden: true },
    ],
    hints: ['Hàng i có i dấu *', 'Dùng "*" * i để tạo chuỗi'],
    order_index: 2,
  },
  {
    id: 87,
    lesson_id: 19,
    title: 'In ma trận NxN',
    description: 'Cho số nguyên dương N. In ma trận NxN với các phần tử đánh số từ 1 đến N*N theo hàng. Các số cách nhau bởi dấu cách.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# In ma trận NxN\n',
    test_cases: [
      { input: '3', expected_output: '1 2 3\n4 5 6\n7 8 9', is_hidden: false },
      { input: '2', expected_output: '1 2\n3 4', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: true },
    ],
    hints: ['Dùng 2 vòng for lồng nhau', 'Giá trị tại hàng i cột j: i*n + j + 1 (đếm từ 0)'],
    order_index: 3,
  },

  // Lesson 20: Tổng/tích/đếm
  {
    id: 88,
    lesson_id: 20,
    title: 'Tính giai thừa',
    description: 'Cho số nguyên không âm N. Tính N! (giai thừa). Biết 0! = 1.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Tính n!\n',
    test_cases: [
      { input: '5', expected_output: '120', is_hidden: false },
      { input: '0', expected_output: '1', is_hidden: false },
      { input: '10', expected_output: '3628800', is_hidden: true },
    ],
    hints: ['Dùng vòng for nhân dồn từ 1 đến n', 'Khởi tạo kết quả = 1'],
    order_index: 1,
  },
  {
    id: 89,
    lesson_id: 20,
    title: 'Đếm số nguyên tố trong khoảng',
    description: 'Cho 2 số nguyên dương a và b (a <= b). Đếm số lượng số nguyên tố trong đoạn [a, b].',
    difficulty: 'medium',
    starter_code: 'a = int(input())\nb = int(input())\n# Đếm số nguyên tố trong [a, b]\n',
    test_cases: [
      { input: '1\n10', expected_output: '4', is_hidden: false },
      { input: '10\n20', expected_output: '4', is_hidden: false },
      { input: '1\n1', expected_output: '0', is_hidden: true },
    ],
    hints: ['Viết hàm kiểm tra nguyên tố', 'Duyệt từ a đến b, đếm số nguyên tố'],
    order_index: 2,
  },
  {
    id: 90,
    lesson_id: 20,
    title: 'Tổng các chữ số',
    description: 'Cho số nguyên dương N. Tính tổng các chữ số của N. Ví dụ N=1234 thì tổng = 1+2+3+4 = 10.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Tính tổng các chữ số\n',
    test_cases: [
      { input: '1234', expected_output: '10', is_hidden: false },
      { input: '999', expected_output: '27', is_hidden: false },
      { input: '100', expected_output: '1', is_hidden: true },
    ],
    hints: ['Lấy chữ số cuối: n % 10', 'Bỏ chữ số cuối: n //= 10', 'Lặp cho đến khi n == 0'],
    order_index: 3,
  },

  // ===== LEVEL 5: Hàm (Lessons 21-25) =====
  // Lesson 21: def/return
  {
    id: 91,
    lesson_id: 21,
    title: 'Hàm kiểm tra số nguyên tố',
    description: 'Viết hàm is_prime(n) trả về True nếu n là số nguyên tố, False nếu không. Nhập số nguyên n và in kết quả gọi hàm.',
    difficulty: 'easy',
    starter_code: 'def is_prime(n):\n    # Viết code kiểm tra nguyên tố\n    pass\n\nn = int(input())\nprint(is_prime(n))\n',
    test_cases: [
      { input: '7', expected_output: 'True', is_hidden: false },
      { input: '4', expected_output: 'False', is_hidden: false },
      { input: '2', expected_output: 'True', is_hidden: true },
      { input: '1', expected_output: 'False', is_hidden: true },
    ],
    hints: ['Số < 2 không phải nguyên tố', 'Kiểm tra chia hết từ 2 đến sqrt(n)'],
    order_index: 1,
  },
  {
    id: 92,
    lesson_id: 21,
    title: 'Hàm tính UCLN',
    description: 'Viết hàm gcd(a, b) tính ước chung lớn nhất của a và b bằng thuật toán Euclid. Nhập a, b và in kết quả.',
    difficulty: 'medium',
    starter_code: 'def gcd(a, b):\n    # Thuật toán Euclid\n    pass\n\na = int(input())\nb = int(input())\nprint(gcd(a, b))\n',
    test_cases: [
      { input: '12\n8', expected_output: '4', is_hidden: false },
      { input: '17\n5', expected_output: '1', is_hidden: false },
      { input: '100\n75', expected_output: '25', is_hidden: true },
    ],
    hints: ['Euclid: gcd(a, b) = gcd(b, a % b)', 'Điều kiện dừng: b == 0 thì trả về a'],
    order_index: 2,
  },
  {
    id: 93,
    lesson_id: 21,
    title: 'Hàm tính lũy thừa',
    description: 'Viết hàm power(base, exp) tính base^exp (exp >= 0) KHÔNG dùng toán tử ** hay pow(). Nhập base và exp, in kết quả.',
    difficulty: 'hard',
    starter_code: 'def power(base, exp):\n    # Tính base^exp bằng vòng lặp\n    pass\n\nbase = int(input())\nexp = int(input())\nprint(power(base, exp))\n',
    test_cases: [
      { input: '2\n10', expected_output: '1024', is_hidden: false },
      { input: '3\n0', expected_output: '1', is_hidden: false },
      { input: '5\n3', expected_output: '125', is_hidden: true },
    ],
    hints: ['Nhân base với chính nó exp lần', 'Trường hợp exp = 0 trả về 1'],
    order_index: 3,
  },

  // Lesson 22: Tham số mặc định
  {
    id: 94,
    lesson_id: 22,
    title: 'Hàm chào với thời gian',
    description: 'Viết hàm greet(name, time="sang") trả về chuỗi "Chao buoi <time>, <name>!". Nhập name và time (2 dòng), nếu time là "default" thì gọi hàm không truyền time.',
    difficulty: 'easy',
    starter_code: 'def greet(name, time="sang"):\n    # Trả về lời chào\n    pass\n\nname = input()\ntime = input()\nif time == "default":\n    print(greet(name))\nelse:\n    print(greet(name, time))\n',
    test_cases: [
      { input: 'An\ndefault', expected_output: 'Chao buoi sang, An!', is_hidden: false },
      { input: 'Binh\ntoi', expected_output: 'Chao buoi toi, Binh!', is_hidden: false },
      { input: 'Chi\ntrua', expected_output: 'Chao buoi trua, Chi!', is_hidden: true },
    ],
    hints: ['return f"Chao buoi {time}, {name}!"', 'Tham số mặc định dùng khi không truyền giá trị'],
    order_index: 1,
  },
  {
    id: 95,
    lesson_id: 22,
    title: 'Hàm định dạng số',
    description: 'Viết hàm format_number(n, decimals=2, prefix="") trả về chuỗi số n làm tròn decimals chữ số thập phân, có prefix phía trước. Nhập n, decimals, prefix trên 3 dòng.',
    difficulty: 'medium',
    starter_code: 'def format_number(n, decimals=2, prefix=""):\n    # Định dạng số\n    pass\n\nn = float(input())\ndecimals = int(input())\nprefix = input()\nprint(format_number(n, decimals, prefix))\n',
    test_cases: [
      { input: '3.14159\n2\n$', expected_output: '$3.14', is_hidden: false },
      { input: '1000.5\n1\n', expected_output: '1000.5', is_hidden: false },
      { input: '99.999\n0\nVND ', expected_output: 'VND 100', is_hidden: true },
    ],
    hints: ['Dùng round(n, decimals)', 'Dùng f-string với :.{decimals}f', 'Nối prefix + kết quả'],
    order_index: 2,
  },
  {
    id: 96,
    lesson_id: 22,
    title: 'Hàm tạo mật khẩu',
    description: 'Viết hàm generate_pattern(char="*", length=5, border=True). Nếu border=True trả về chuỗi dạng [*****], nếu False trả về *****. Nhập char, length, border (3 dòng, border là "True"/"False").',
    difficulty: 'hard',
    starter_code: 'def generate_pattern(char="*", length=5, border=True):\n    # Tạo pattern\n    pass\n\nchar = input()\nlength = int(input())\nborder = input() == "True"\nprint(generate_pattern(char, length, border))\n',
    test_cases: [
      { input: '*\n5\nTrue', expected_output: '[*****]', is_hidden: false },
      { input: '#\n3\nFalse', expected_output: '###', is_hidden: false },
      { input: '-\n8\nTrue', expected_output: '[--------]', is_hidden: true },
    ],
    hints: ['Tạo chuỗi: char * length', 'Nếu border: thêm [ và ] bao quanh'],
    order_index: 3,
  },

  // Lesson 23: Phạm vi biến
  {
    id: 97,
    lesson_id: 23,
    title: 'Hàm đếm lời gọi',
    description: 'Viết chương trình: có biến toàn cục count = 0. Viết hàm increment() tăng count lên 1 (dùng global). Nhập số nguyên n, gọi increment() n lần rồi in count.',
    difficulty: 'easy',
    starter_code: 'count = 0\n\ndef increment():\n    # Tăng count lên 1\n    pass\n\nn = int(input())\nfor _ in range(n):\n    increment()\nprint(count)\n',
    test_cases: [
      { input: '5', expected_output: '5', is_hidden: false },
      { input: '0', expected_output: '0', is_hidden: false },
      { input: '100', expected_output: '100', is_hidden: true },
    ],
    hints: ['Dùng từ khóa global count bên trong hàm', 'global cho phép thay đổi biến toàn cục'],
    order_index: 1,
  },
  {
    id: 98,
    lesson_id: 23,
    title: 'Hàm tích lũy',
    description: 'Viết hàm make_accumulator() trả về một hàm con. Hàm con nhận số x và cộng dồn vào tổng. Nhập n số (dòng 1 là n, các dòng sau là n số), in tổng tích lũy sau mỗi lần cộng, mỗi kết quả 1 dòng.',
    difficulty: 'medium',
    starter_code: 'def make_accumulator():\n    total = 0\n    def add(x):\n        nonlocal total\n        total += x\n        return total\n    return add\n\nacc = make_accumulator()\nn = int(input())\nfor _ in range(n):\n    x = int(input())\n    print(acc(x))\n',
    test_cases: [
      { input: '3\n5\n3\n2', expected_output: '5\n8\n10', is_hidden: false },
      { input: '2\n10\n-3', expected_output: '10\n7', is_hidden: false },
      { input: '1\n100', expected_output: '100', is_hidden: true },
    ],
    hints: ['nonlocal cho phép hàm con thay đổi biến của hàm cha', 'Closure giữ trạng thái giữa các lần gọi'],
    order_index: 2,
  },
  {
    id: 99,
    lesson_id: 23,
    title: 'Biến cục bộ và toàn cục',
    description: 'Cho biến toàn cục x = 10. Viết hàm modify(val) gán biến cục bộ x = val và trả về x + biến toàn cục x. Nhập val, in kết quả hàm modify(val) và giá trị x toàn cục sau khi gọi.',
    difficulty: 'hard',
    starter_code: 'x = 10\n\ndef modify(val):\n    x = val\n    return x + 10  # 10 là giá trị toàn cục\n\nval = int(input())\nresult = modify(val)\nprint(result)\nprint(x)\n',
    test_cases: [
      { input: '5', expected_output: '15\n10', is_hidden: false },
      { input: '20', expected_output: '30\n10', is_hidden: false },
      { input: '0', expected_output: '10\n10', is_hidden: true },
    ],
    hints: ['Biến x trong hàm là cục bộ, không ảnh hưởng x toàn cục', 'Hàm trả về val + 10 (giá trị toàn cục)'],
    order_index: 3,
  },

  // Lesson 24: Đệ quy
  {
    id: 100,
    lesson_id: 24,
    title: 'Fibonacci đệ quy',
    description: 'Viết hàm đệ quy fibonacci(n) trả về số Fibonacci thứ n (F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)). Nhập n và in kết quả.',
    difficulty: 'easy',
    starter_code: 'def fibonacci(n):\n    # Đệ quy tính Fibonacci\n    pass\n\nn = int(input())\nprint(fibonacci(n))\n',
    test_cases: [
      { input: '6', expected_output: '8', is_hidden: false },
      { input: '0', expected_output: '0', is_hidden: false },
      { input: '10', expected_output: '55', is_hidden: true },
    ],
    hints: ['Trường hợp cơ sở: n <= 1 trả về n', 'Đệ quy: fibonacci(n-1) + fibonacci(n-2)'],
    order_index: 1,
  },
  {
    id: 101,
    lesson_id: 24,
    title: 'Tổng chữ số đệ quy',
    description: 'Viết hàm đệ quy sum_digits(n) tính tổng các chữ số của số nguyên dương n. Nhập n và in kết quả.',
    difficulty: 'medium',
    starter_code: 'def sum_digits(n):\n    # Đệ quy tính tổng chữ số\n    pass\n\nn = int(input())\nprint(sum_digits(n))\n',
    test_cases: [
      { input: '1234', expected_output: '10', is_hidden: false },
      { input: '9', expected_output: '9', is_hidden: false },
      { input: '999', expected_output: '27', is_hidden: true },
    ],
    hints: ['Trường hợp cơ sở: n < 10 trả về n', 'Đệ quy: n % 10 + sum_digits(n // 10)'],
    order_index: 2,
  },
  {
    id: 102,
    lesson_id: 24,
    title: 'Đếm bước Tháp Hà Nội',
    description: 'Viết hàm đệ quy hanoi(n) trả về số bước tối thiểu để di chuyển n đĩa trong bài toán Tháp Hà Nội. Nhập n và in kết quả.',
    difficulty: 'hard',
    starter_code: 'def hanoi(n):\n    # Đếm số bước di chuyển n đĩa\n    pass\n\nn = int(input())\nprint(hanoi(n))\n',
    test_cases: [
      { input: '3', expected_output: '7', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: false },
      { input: '10', expected_output: '1023', is_hidden: true },
    ],
    hints: ['hanoi(n) = 2 * hanoi(n-1) + 1', 'Trường hợp cơ sở: hanoi(1) = 1', 'Hoặc công thức: 2^n - 1'],
    order_index: 3,
  },

  // Lesson 25: Lambda/map/filter
  {
    id: 103,
    lesson_id: 25,
    title: 'Sắp xếp theo độ dài',
    description: 'Nhập n (số từ), sau đó nhập n từ (mỗi từ 1 dòng). Sắp xếp các từ theo độ dài tăng dần (nếu bằng nhau giữ thứ tự ban đầu). In mỗi từ 1 dòng.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\nwords = [input() for _ in range(n)]\n# Sắp xếp theo độ dài dùng lambda\n',
    test_cases: [
      { input: '4\nbanana\ncat\napple\nhi', expected_output: 'hi\ncat\napple\nbanana', is_hidden: false },
      { input: '3\nabc\nab\na', expected_output: 'a\nab\nabc', is_hidden: false },
    ],
    hints: ['Dùng sorted() với key=lambda x: len(x)', 'sorted() giữ thứ tự ban đầu khi bằng nhau (stable)'],
    order_index: 1,
  },
  {
    id: 104,
    lesson_id: 25,
    title: 'Lọc số chẵn',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Dùng filter và lambda để lọc ra các số chẵn. In kết quả trên 1 dòng cách nhau bởi dấu cách.',
    difficulty: 'medium',
    starter_code: 'numbers = list(map(int, input().split()))\n# Lọc số chẵn dùng filter + lambda\n',
    test_cases: [
      { input: '1 2 3 4 5 6 7 8', expected_output: '2 4 6 8', is_hidden: false },
      { input: '1 3 5 7', expected_output: '', is_hidden: false },
      { input: '2 4 6', expected_output: '2 4 6', is_hidden: true },
    ],
    hints: ['filter(lambda x: x % 2 == 0, numbers)', 'Chuyển kết quả thành list rồi join'],
    order_index: 2,
  },
  {
    id: 105,
    lesson_id: 25,
    title: 'Biến đổi danh sách',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Dùng map và lambda để tạo danh sách mới: mỗi phần tử bình phương nếu dương, giữ nguyên nếu âm hoặc 0. In kết quả trên 1 dòng cách nhau bởi dấu cách.',
    difficulty: 'hard',
    starter_code: 'numbers = list(map(int, input().split()))\n# Biến đổi: bình phương nếu dương, giữ nguyên nếu <= 0\n',
    test_cases: [
      { input: '1 -2 3 0 -5', expected_output: '1 -2 9 0 -5', is_hidden: false },
      { input: '2 4 6', expected_output: '4 16 36', is_hidden: false },
      { input: '-1 -2 -3', expected_output: '-1 -2 -3', is_hidden: true },
    ],
    hints: ['lambda x: x**2 if x > 0 else x', 'Dùng map() để áp dụng cho toàn bộ list'],
    order_index: 3,
  },

  // ===== LEVEL 6: List/Tuple (Lessons 26-30) =====
  // Lesson 26: List cơ bản
  {
    id: 106,
    lesson_id: 26,
    title: 'Đảo ngược danh sách',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra danh sách đảo ngược trên 1 dòng cách nhau bởi dấu cách.',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\n# Đảo ngược danh sách\n',
    test_cases: [
      { input: '1 2 3 4 5', expected_output: '5 4 3 2 1', is_hidden: false },
      { input: '10 20 30', expected_output: '30 20 10', is_hidden: false },
      { input: '7', expected_output: '7', is_hidden: true },
    ],
    hints: ['Dùng slicing [::-1]', 'Hoặc dùng .reverse() hoặc reversed()'],
    order_index: 1,
  },
  {
    id: 107,
    lesson_id: 26,
    title: 'Tìm max và min',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra giá trị lớn nhất và nhỏ nhất trên 2 dòng: "Max: <x>" và "Min: <y>".',
    difficulty: 'medium',
    starter_code: 'numbers = list(map(int, input().split()))\n# Tìm max và min\n',
    test_cases: [
      { input: '3 1 4 1 5 9 2 6', expected_output: 'Max: 9\nMin: 1', is_hidden: false },
      { input: '-5 -2 -8 -1', expected_output: 'Max: -1\nMin: -8', is_hidden: false },
      { input: '7', expected_output: 'Max: 7\nMin: 7', is_hidden: true },
    ],
    hints: ['Dùng max() và min()', 'Hoặc duyệt list để tìm'],
    order_index: 2,
  },
  {
    id: 108,
    lesson_id: 26,
    title: 'Tìm phần tử lớn thứ hai',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách (n >= 2, có ít nhất 2 giá trị khác nhau). In ra phần tử lớn thứ hai (second largest).',
    difficulty: 'hard',
    starter_code: 'numbers = list(map(int, input().split()))\n# Tìm phần tử lớn thứ hai\n',
    test_cases: [
      { input: '3 1 4 1 5 9 2 6', expected_output: '6', is_hidden: false },
      { input: '10 10 5 3', expected_output: '5', is_hidden: false },
      { input: '1 2', expected_output: '1', is_hidden: true },
    ],
    hints: ['Loại bỏ trùng lặp bằng set()', 'Sắp xếp và lấy phần tử thứ hai từ cuối'],
    order_index: 3,
  },

  // Lesson 27: Phương thức list
  {
    id: 109,
    lesson_id: 27,
    title: 'Xóa phần tử trùng lặp',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra danh sách sau khi xóa các phần tử trùng lặp, giữ nguyên thứ tự xuất hiện đầu tiên.',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\n# Xóa trùng lặp giữ thứ tự\n',
    test_cases: [
      { input: '1 2 3 2 1 4 5 4', expected_output: '1 2 3 4 5', is_hidden: false },
      { input: '5 5 5 5', expected_output: '5', is_hidden: false },
      { input: '1 2 3', expected_output: '1 2 3', is_hidden: true },
    ],
    hints: ['Dùng dict.fromkeys() để giữ thứ tự', 'Hoặc duyệt và thêm vào list mới nếu chưa có'],
    order_index: 1,
  },
  {
    id: 110,
    lesson_id: 27,
    title: 'Xoay mảng',
    description: 'Nhập dòng 1: n số nguyên cách nhau bởi dấu cách. Dòng 2: số k (xoay phải k vị trí). In ra mảng sau khi xoay.',
    difficulty: 'medium',
    starter_code: 'numbers = list(map(int, input().split()))\nk = int(input())\n# Xoay mảng phải k vị trí\n',
    test_cases: [
      { input: '1 2 3 4 5\n2', expected_output: '4 5 1 2 3', is_hidden: false },
      { input: '10 20 30\n1', expected_output: '30 10 20', is_hidden: false },
      { input: '1 2 3\n3', expected_output: '1 2 3', is_hidden: true },
    ],
    hints: ['Xoay phải k: lấy k phần tử cuối + phần còn lại', 'k = k % len(numbers) để xử lý k > n'],
    order_index: 2,
  },
  {
    id: 111,
    lesson_id: 27,
    title: 'Trộn hai mảng đã sắp xếp',
    description: 'Nhập 2 dòng, mỗi dòng là dãy số nguyên đã sắp xếp tăng dần cách nhau bởi dấu cách. Trộn thành 1 dãy sắp xếp tăng dần. In kết quả trên 1 dòng.',
    difficulty: 'hard',
    starter_code: 'a = list(map(int, input().split()))\nb = list(map(int, input().split()))\n# Trộn 2 mảng đã sắp xếp\n',
    test_cases: [
      { input: '1 3 5 7\n2 4 6 8', expected_output: '1 2 3 4 5 6 7 8', is_hidden: false },
      { input: '1 2 3\n4 5 6', expected_output: '1 2 3 4 5 6', is_hidden: false },
      { input: '5 10\n1 3 7 12', expected_output: '1 3 5 7 10 12', is_hidden: true },
    ],
    hints: ['Dùng 2 con trỏ i, j duyệt song song', 'So sánh a[i] và b[j], thêm phần tử nhỏ hơn vào kết quả'],
    order_index: 3,
  },

  // Lesson 28: List comprehension
  {
    id: 112,
    lesson_id: 28,
    title: 'Danh sách bình phương',
    description: 'Nhập số nguyên dương N. Dùng list comprehension tạo danh sách bình phương từ 1 đến N. In các số cách nhau bởi dấu cách.',
    difficulty: 'easy',
    starter_code: 'n = int(input())\n# Tạo danh sách bình phương dùng list comprehension\n',
    test_cases: [
      { input: '5', expected_output: '1 4 9 16 25', is_hidden: false },
      { input: '3', expected_output: '1 4 9', is_hidden: false },
      { input: '1', expected_output: '1', is_hidden: true },
    ],
    hints: ['[i**2 for i in range(1, n+1)]', 'Dùng " ".join(map(str, ...)) để in'],
    order_index: 1,
  },
  {
    id: 113,
    lesson_id: 28,
    title: 'Lọc số nguyên tố',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Dùng list comprehension lọc ra các số nguyên tố. In kết quả trên 1 dòng cách nhau bởi dấu cách. Nếu không có số nguyên tố nào, in "Khong co".',
    difficulty: 'medium',
    starter_code: 'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\nnumbers = list(map(int, input().split()))\n# Lọc số nguyên tố dùng list comprehension\n',
    test_cases: [
      { input: '1 2 3 4 5 6 7 8 9 10', expected_output: '2 3 5 7', is_hidden: false },
      { input: '11 13 15 17 19', expected_output: '11 13 17 19', is_hidden: false },
      { input: '4 6 8 9', expected_output: 'Khong co', is_hidden: true },
    ],
    hints: ['[x for x in numbers if is_prime(x)]', 'Kiểm tra list rỗng trước khi in'],
    order_index: 2,
  },
  {
    id: 114,
    lesson_id: 28,
    title: 'Làm phẳng ma trận 2D',
    description: 'Nhập dòng 1: số hàng n. Các dòng tiếp theo: mỗi dòng là 1 hàng của ma trận (các số cách nhau bởi dấu cách). Dùng list comprehension để làm phẳng thành 1 danh sách. In kết quả trên 1 dòng.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\nmatrix = [list(map(int, input().split())) for _ in range(n)]\n# Làm phẳng ma trận dùng list comprehension\n',
    test_cases: [
      { input: '3\n1 2 3\n4 5 6\n7 8 9', expected_output: '1 2 3 4 5 6 7 8 9', is_hidden: false },
      { input: '2\n10 20\n30 40', expected_output: '10 20 30 40', is_hidden: false },
      { input: '1\n5 6 7', expected_output: '5 6 7', is_hidden: true },
    ],
    hints: ['[x for row in matrix for x in row]', 'Vòng for ngoài duyệt hàng, vòng trong duyệt phần tử'],
    order_index: 3,
  },

  // Lesson 29: Tuple/unpacking
  {
    id: 115,
    lesson_id: 29,
    title: 'Hoán đổi bằng tuple unpacking',
    description: 'Nhập 2 số nguyên a, b trên 1 dòng cách nhau bởi dấu cách. Hoán đổi giá trị bằng tuple unpacking và in "a b" sau khi hoán đổi.',
    difficulty: 'easy',
    starter_code: 'a, b = map(int, input().split())\n# Hoán đổi bằng tuple unpacking\n',
    test_cases: [
      { input: '3 7', expected_output: '7 3', is_hidden: false },
      { input: '10 20', expected_output: '20 10', is_hidden: false },
      { input: '5 5', expected_output: '5 5', is_hidden: true },
    ],
    hints: ['a, b = b, a', 'Python hỗ trợ hoán đổi trực tiếp bằng tuple'],
    order_index: 1,
  },
  {
    id: 116,
    lesson_id: 29,
    title: 'Hàm trả về nhiều giá trị',
    description: 'Viết hàm min_max(lst) nhận danh sách số nguyên, trả về tuple (min, max). Nhập n số trên 1 dòng, gọi hàm và in "Min: <min> Max: <max>".',
    difficulty: 'medium',
    starter_code: 'def min_max(lst):\n    # Trả về (min, max)\n    pass\n\nnumbers = list(map(int, input().split()))\nmi, ma = min_max(numbers)\nprint(f"Min: {mi} Max: {ma}")\n',
    test_cases: [
      { input: '3 1 4 1 5 9', expected_output: 'Min: 1 Max: 9', is_hidden: false },
      { input: '-5 0 5', expected_output: 'Min: -5 Max: 5', is_hidden: false },
      { input: '7', expected_output: 'Min: 7 Max: 7', is_hidden: true },
    ],
    hints: ['return (min(lst), max(lst))', 'Tuple unpacking: mi, ma = min_max(numbers)'],
    order_index: 2,
  },
  {
    id: 117,
    lesson_id: 29,
    title: 'Khoảng cách giữa hai tọa độ',
    description: 'Nhập 2 dòng, mỗi dòng là tọa độ (x, y) cách nhau bởi dấu cách. Tính khoảng cách Euclid giữa 2 điểm. In kết quả làm tròn 2 chữ số thập phân.',
    difficulty: 'hard',
    starter_code: 'import math\n\nx1, y1 = map(float, input().split())\nx2, y2 = map(float, input().split())\n# Tính khoảng cách\n',
    test_cases: [
      { input: '0 0\n3 4', expected_output: '5.00', is_hidden: false },
      { input: '1 1\n4 5', expected_output: '5.00', is_hidden: false },
      { input: '0 0\n1 1', expected_output: '1.41', is_hidden: true },
    ],
    hints: ['d = sqrt((x2-x1)^2 + (y2-y1)^2)', 'Dùng tuple unpacking để đọc tọa độ'],
    order_index: 3,
  },

  // Lesson 30: Duyệt/lọc
  {
    id: 118,
    lesson_id: 30,
    title: 'Các phần tử trên trung bình',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra các phần tử lớn hơn giá trị trung bình của danh sách, trên 1 dòng cách nhau bởi dấu cách.',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\n# Tìm các phần tử > trung bình\n',
    test_cases: [
      { input: '1 2 3 4 5', expected_output: '4 5', is_hidden: false },
      { input: '10 20 30 40 50', expected_output: '40 50', is_hidden: false },
      { input: '5 5 5', expected_output: '', is_hidden: true },
    ],
    hints: ['Tính trung bình: sum(numbers) / len(numbers)', 'Lọc: [x for x in numbers if x > avg]'],
    order_index: 1,
  },
  {
    id: 119,
    lesson_id: 30,
    title: 'Chuỗi liên tiếp dài nhất',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Tìm độ dài chuỗi con liên tiếp dài nhất có cùng giá trị. In ra độ dài đó.',
    difficulty: 'medium',
    starter_code: 'numbers = list(map(int, input().split()))\n# Tìm chuỗi liên tiếp dài nhất\n',
    test_cases: [
      { input: '1 1 2 2 2 3 3', expected_output: '3', is_hidden: false },
      { input: '5 5 5 5 5', expected_output: '5', is_hidden: false },
      { input: '1 2 3 4 5', expected_output: '1', is_hidden: true },
    ],
    hints: ['Duyệt và đếm liên tiếp', 'Khi gặp phần tử khác, cập nhật max và reset đếm'],
    order_index: 2,
  },
  {
    id: 120,
    lesson_id: 30,
    title: 'Đếm tần suất',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra mỗi phần tử duy nhất và số lần xuất hiện, theo thứ tự xuất hiện đầu tiên. Mỗi dòng: "<so>: <so_lan>".',
    difficulty: 'hard',
    starter_code: 'numbers = list(map(int, input().split()))\n# Đếm tần suất giữ thứ tự\n',
    test_cases: [
      { input: '1 2 2 3 1 3 3', expected_output: '1: 2\n2: 2\n3: 3', is_hidden: false },
      { input: '5 5 5', expected_output: '5: 3', is_hidden: false },
      { input: '4 3 2 1', expected_output: '4: 1\n3: 1\n2: 1\n1: 1', is_hidden: true },
    ],
    hints: ['Dùng dict để đếm, giữ thứ tự xuất hiện', 'Hoặc dùng collections.Counter nhưng cần giữ thứ tự'],
    order_index: 3,
  },

  // ===== LEVEL 7: Chuỗi (Lessons 31-35) =====
  // Lesson 31: Duyệt chuỗi
  {
    id: 121,
    lesson_id: 31,
    title: 'Đếm nguyên âm',
    description: 'Nhập một chuỗi. Đếm số lượng nguyên âm (a, e, i, o, u - không phân biệt hoa thường) trong chuỗi.',
    difficulty: 'easy',
    starter_code: 's = input()\n# Đếm nguyên âm\n',
    test_cases: [
      { input: 'Hello World', expected_output: '3', is_hidden: false },
      { input: 'PYTHON', expected_output: '1', is_hidden: false },
      { input: 'xyz', expected_output: '0', is_hidden: true },
    ],
    hints: ['Nguyên âm: "aeiouAEIOU"', 'Duyệt từng ký tự và đếm'],
    order_index: 1,
  },
  {
    id: 122,
    lesson_id: 31,
    title: 'Viết hoa chữ cái đầu mỗi từ',
    description: 'Nhập một chuỗi (các từ cách nhau bởi dấu cách). In ra chuỗi với chữ cái đầu mỗi từ viết hoa, còn lại viết thường.',
    difficulty: 'medium',
    starter_code: 's = input()\n# Viết hoa chữ cái đầu mỗi từ\n',
    test_cases: [
      { input: 'hello world python', expected_output: 'Hello World Python', is_hidden: false },
      { input: 'NGUYEN VAN AN', expected_output: 'Nguyen Van An', is_hidden: false },
      { input: 'a', expected_output: 'A', is_hidden: true },
    ],
    hints: ['Dùng .title() hoặc .capitalize() cho từng từ', 'Hoặc split, xử lý từng từ, rồi join'],
    order_index: 2,
  },
  {
    id: 123,
    lesson_id: 31,
    title: 'Xóa khoảng trắng thừa',
    description: 'Nhập một chuỗi có thể có nhiều khoảng trắng liên tiếp. In ra chuỗi chỉ có 1 khoảng trắng giữa các từ, không có khoảng trắng đầu/cuối.',
    difficulty: 'hard',
    starter_code: 's = input()\n# Xóa khoảng trắng thừa\n',
    test_cases: [
      { input: '  Hello   World   Python  ', expected_output: 'Hello World Python', is_hidden: false },
      { input: 'No  extra   spaces', expected_output: 'No extra spaces', is_hidden: false },
      { input: '   single   ', expected_output: 'single', is_hidden: true },
    ],
    hints: ['Dùng .split() không tham số (tự tách theo khoảng trắng)', 'Rồi " ".join() để nối lại'],
    order_index: 3,
  },

  // Lesson 32: split/join
  {
    id: 124,
    lesson_id: 32,
    title: 'Đếm số từ',
    description: 'Nhập một câu. Đếm số từ trong câu (từ là chuỗi ký tự liên tiếp không chứa khoảng trắng).',
    difficulty: 'easy',
    starter_code: 's = input()\n# Đếm số từ\n',
    test_cases: [
      { input: 'Hello World Python', expected_output: '3', is_hidden: false },
      { input: 'Mot hai ba bon nam', expected_output: '5', is_hidden: false },
      { input: 'Single', expected_output: '1', is_hidden: true },
    ],
    hints: ['Dùng .split() để tách thành list các từ', 'len() của list là số từ'],
    order_index: 1,
  },
  {
    id: 125,
    lesson_id: 32,
    title: 'Đảo ngược từng từ',
    description: 'Nhập một câu. Đảo ngược từng từ trong câu nhưng giữ nguyên thứ tự các từ. Ví dụ "Hello World" → "olleH dlroW".',
    difficulty: 'medium',
    starter_code: 's = input()\n# Đảo ngược từng từ\n',
    test_cases: [
      { input: 'Hello World', expected_output: 'olleH dlroW', is_hidden: false },
      { input: 'Python is fun', expected_output: 'nohtyP si nuf', is_hidden: false },
      { input: 'A', expected_output: 'A', is_hidden: true },
    ],
    hints: ['Split thành list từ', 'Đảo ngược mỗi từ bằng [::-1]', 'Join lại bằng " "'],
    order_index: 2,
  },
  {
    id: 126,
    lesson_id: 32,
    title: 'Phân tích dòng CSV',
    description: 'Nhập một dòng CSV (các giá trị cách nhau bởi dấu phẩy). In ra số lượng cột và giá trị của từng cột trên mỗi dòng theo format "Cot <i>: <gia_tri>" (i bắt đầu từ 1). Dòng đầu in "So cot: <n>".',
    difficulty: 'hard',
    starter_code: 'line = input()\n# Phân tích CSV\n',
    test_cases: [
      { input: 'An,20,Ha Noi', expected_output: 'So cot: 3\nCot 1: An\nCot 2: 20\nCot 3: Ha Noi', is_hidden: false },
      { input: 'x,y', expected_output: 'So cot: 2\nCot 1: x\nCot 2: y', is_hidden: false },
      { input: 'single', expected_output: 'So cot: 1\nCot 1: single', is_hidden: true },
    ],
    hints: ['Dùng .split(",") để tách', 'Duyệt với enumerate để có index'],
    order_index: 3,
  },

  // Lesson 33: Format chuỗi
  {
    id: 127,
    lesson_id: 33,
    title: 'Căn chỉnh bảng',
    description: 'Nhập n (số hàng). Mỗi hàng tiếp theo nhập tên và điểm cách nhau bởi dấu phẩy. In bảng với tên căn trái 10 ký tự và điểm căn phải 5 ký tự, cách nhau bởi "|".',
    difficulty: 'easy',
    starter_code: 'n = int(input())\nfor _ in range(n):\n    line = input()\n    # Phân tích và in căn chỉnh\n',
    test_cases: [
      { input: '2\nAn,9\nBinh,10', expected_output: 'An        |    9\nBinh      |   10', is_hidden: false },
      { input: '1\nChi,8', expected_output: 'Chi       |    8', is_hidden: true },
    ],
    hints: ['Dùng f-string: f"{name:<10}|{score:>5}"', 'Split dòng bằng dấu phẩy'],
    order_index: 1,
  },
  {
    id: 128,
    lesson_id: 33,
    title: 'Đệm số 0',
    description: 'Nhập số nguyên dương n. In ra n với đệm số 0 phía trước cho đủ 5 chữ số. Ví dụ n=42 → "00042".',
    difficulty: 'medium',
    starter_code: 'n = int(input())\n# In số với đệm 0 cho đủ 5 chữ số\n',
    test_cases: [
      { input: '42', expected_output: '00042', is_hidden: false },
      { input: '12345', expected_output: '12345', is_hidden: false },
      { input: '1', expected_output: '00001', is_hidden: true },
    ],
    hints: ['Dùng f"{n:05d}"', 'Hoặc str(n).zfill(5)'],
    order_index: 2,
  },
  {
    id: 129,
    lesson_id: 33,
    title: 'Định dạng tiền tệ',
    description: 'Nhập số nguyên (có thể lớn). In ra số đó với dấu chấm phân cách hàng nghìn và hậu tố " VND". Ví dụ 1000000 → "1.000.000 VND".',
    difficulty: 'hard',
    starter_code: 'n = int(input())\n# Định dạng tiền tệ\n',
    test_cases: [
      { input: '1000000', expected_output: '1.000.000 VND', is_hidden: false },
      { input: '50000', expected_output: '50.000 VND', is_hidden: false },
      { input: '999', expected_output: '999 VND', is_hidden: true },
    ],
    hints: ['Dùng f"{n:,}".replace(",", ".")', 'Hoặc xử lý thủ công từ phải sang trái'],
    order_index: 3,
  },

  // Lesson 34: Palindrome
  {
    id: 130,
    lesson_id: 34,
    title: 'Kiểm tra palindrome',
    description: 'Nhập một chuỗi (chỉ chứa chữ cái thường và số). Kiểm tra xem chuỗi có phải palindrome không (đọc xuôi ngược giống nhau). In "Yes" hoặc "No".',
    difficulty: 'easy',
    starter_code: 's = input()\n# Kiểm tra palindrome\n',
    test_cases: [
      { input: 'racecar', expected_output: 'Yes', is_hidden: false },
      { input: 'hello', expected_output: 'No', is_hidden: false },
      { input: 'a', expected_output: 'Yes', is_hidden: true },
      { input: '12321', expected_output: 'Yes', is_hidden: true },
    ],
    hints: ['So sánh s với s[::-1]', 'Palindrome: chuỗi đọc ngược giống đọc xuôi'],
    order_index: 1,
  },
  {
    id: 131,
    lesson_id: 34,
    title: 'Palindrome bỏ qua khoảng trắng và hoa/thường',
    description: 'Nhập một chuỗi. Kiểm tra palindrome sau khi bỏ khoảng trắng và chuyển về chữ thường. In "Yes" hoặc "No".',
    difficulty: 'medium',
    starter_code: 's = input()\n# Kiểm tra palindrome (bỏ qua khoảng trắng, hoa/thường)\n',
    test_cases: [
      { input: 'A man a plan a canal Panama', expected_output: 'Yes', is_hidden: false },
      { input: 'Race Car', expected_output: 'Yes', is_hidden: false },
      { input: 'Hello World', expected_output: 'No', is_hidden: true },
    ],
    hints: ['Bỏ khoảng trắng: s.replace(" ", "")', 'Chuyển thường: .lower()', 'Rồi kiểm tra palindrome'],
    order_index: 2,
  },
  {
    id: 132,
    lesson_id: 34,
    title: 'Độ dài chuỗi con palindrome dài nhất',
    description: 'Nhập một chuỗi (chỉ chữ cái thường). Tìm độ dài chuỗi con liên tiếp dài nhất là palindrome. In ra độ dài đó.',
    difficulty: 'hard',
    starter_code: 's = input()\n# Tìm độ dài palindrome con dài nhất\n',
    test_cases: [
      { input: 'babad', expected_output: '3', is_hidden: false },
      { input: 'cbbd', expected_output: '2', is_hidden: false },
      { input: 'a', expected_output: '1', is_hidden: true },
      { input: 'abcba', expected_output: '5', is_hidden: true },
    ],
    hints: ['Duyệt tất cả chuỗi con, kiểm tra palindrome', 'Hoặc mở rộng từ tâm (expand around center)'],
    order_index: 3,
  },

  // Lesson 35: Mã hoá
  {
    id: 133,
    lesson_id: 35,
    title: 'Mã hoá Caesar',
    description: 'Nhập chuỗi (chỉ chữ cái thường) và số dịch k (2 dòng). Mã hoá Caesar: dịch mỗi ký tự sang phải k vị trí trong bảng chữ cái (quay vòng). In chuỗi đã mã hoá.',
    difficulty: 'easy',
    starter_code: 's = input()\nk = int(input())\n# Mã hoá Caesar\n',
    test_cases: [
      { input: 'abc\n3', expected_output: 'def', is_hidden: false },
      { input: 'xyz\n3', expected_output: 'abc', is_hidden: false },
      { input: 'hello\n1', expected_output: 'ifmmp', is_hidden: true },
    ],
    hints: ['Dùng ord() và chr()', 'Công thức: chr((ord(c) - ord("a") + k) % 26 + ord("a"))'],
    order_index: 1,
  },
  {
    id: 134,
    lesson_id: 35,
    title: 'Giải mã Caesar',
    description: 'Nhập chuỗi đã mã hoá (chỉ chữ cái thường) và số dịch k (2 dòng). Giải mã Caesar (dịch ngược k vị trí). In chuỗi gốc.',
    difficulty: 'medium',
    starter_code: 's = input()\nk = int(input())\n# Giải mã Caesar\n',
    test_cases: [
      { input: 'def\n3', expected_output: 'abc', is_hidden: false },
      { input: 'abc\n3', expected_output: 'xyz', is_hidden: false },
      { input: 'ifmmp\n1', expected_output: 'hello', is_hidden: true },
    ],
    hints: ['Giải mã = mã hoá với k = 26 - k', 'Hoặc dịch trái k vị trí: (ord(c) - ord("a") - k) % 26'],
    order_index: 2,
  },
  {
    id: 135,
    lesson_id: 35,
    title: 'Tần suất ký tự',
    description: 'Nhập một chuỗi (chỉ chữ cái thường). In ra tần suất mỗi ký tự xuất hiện, sắp xếp theo tần suất giảm dần. Mỗi dòng: "<ky_tu>: <so_lan>". Nếu bằng nhau, sắp xếp theo thứ tự alphabet.',
    difficulty: 'hard',
    starter_code: 's = input()\n# Đếm và in tần suất ký tự\n',
    test_cases: [
      { input: 'banana', expected_output: 'a: 3\nn: 2\nb: 1', is_hidden: false },
      { input: 'hello', expected_output: 'l: 2\ne: 1\nh: 1\no: 1', is_hidden: false },
      { input: 'aaa', expected_output: 'a: 3', is_hidden: true },
    ],
    hints: ['Dùng dict hoặc Counter để đếm', 'Sắp xếp: sorted(items, key=lambda x: (-x[1], x[0]))'],
    order_index: 3,
  },

  // ===== LEVEL 8: Dict/Set (Lessons 36-40) =====
  // Lesson 36: Dict cơ bản
  {
    id: 136,
    lesson_id: 36,
    title: 'Danh bạ điện thoại',
    description: 'Dòng 1: số n (số liên hệ). n dòng tiếp theo: mỗi dòng "ten,sdt". Dòng cuối: tên cần tra. Nếu tìm thấy in số điện thoại, nếu không in "Khong tim thay".',
    difficulty: 'easy',
    starter_code: 'n = int(input())\nphone_book = {}\nfor _ in range(n):\n    line = input()\n    # Thêm vào danh bạ\n\nquery = input()\n# Tra cứu\n',
    test_cases: [
      { input: '3\nAn,0901234567\nBinh,0912345678\nChi,0923456789\nBinh', expected_output: '0912345678', is_hidden: false },
      { input: '2\nAn,0901234567\nBinh,0912345678\nDung', expected_output: 'Khong tim thay', is_hidden: false },
    ],
    hints: ['Split dòng bằng dấu phẩy', 'Dùng dict.get() hoặc kiểm tra key in dict'],
    order_index: 1,
  },
  {
    id: 137,
    lesson_id: 36,
    title: 'Đếm tần suất từ',
    description: 'Nhập một câu (các từ cách nhau bởi dấu cách, chỉ chữ thường). In ra mỗi từ và số lần xuất hiện, theo thứ tự xuất hiện đầu tiên. Format: "<tu>: <so_lan>".',
    difficulty: 'medium',
    starter_code: 's = input()\n# Đếm tần suất từ\n',
    test_cases: [
      { input: 'the cat sat on the mat the cat', expected_output: 'the: 3\ncat: 2\nsat: 1\non: 1\nmat: 1', is_hidden: false },
      { input: 'hello hello hello', expected_output: 'hello: 3', is_hidden: false },
      { input: 'a b c', expected_output: 'a: 1\nb: 1\nc: 1', is_hidden: true },
    ],
    hints: ['Dùng dict để đếm, giữ thứ tự (Python 3.7+ dict giữ thứ tự)', 'Split câu thành list từ'],
    order_index: 2,
  },
  {
    id: 138,
    lesson_id: 36,
    title: 'Từ điển Anh-Việt',
    description: 'Dòng 1: n (số từ trong từ điển). n dòng tiếp: "english:vietnamese". Dòng tiếp: m (số từ cần tra). m dòng tiếp: từ tiếng Anh cần tra. In nghĩa tiếng Việt hoặc "N/A" nếu không có.',
    difficulty: 'hard',
    starter_code: 'n = int(input())\ndictionary = {}\nfor _ in range(n):\n    line = input()\n    # Thêm vào từ điển\n\nm = int(input())\nfor _ in range(m):\n    word = input()\n    # Tra cứu và in\n',
    test_cases: [
      { input: '3\nhello:xin chao\ngoodbye:tam biet\nthank:cam on\n2\nhello\nworld', expected_output: 'xin chao\nN/A', is_hidden: false },
      { input: '2\ncat:con meo\ndog:con cho\n1\ndog', expected_output: 'con cho', is_hidden: true },
    ],
    hints: ['Split bằng dấu ":" để tách key và value', 'Dùng dict.get(word, "N/A")'],
    order_index: 3,
  },

  // Lesson 37: Duyệt dict
  {
    id: 139,
    lesson_id: 37,
    title: 'Phần tử xuất hiện nhiều nhất',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Tìm phần tử xuất hiện nhiều nhất. Nếu có nhiều phần tử cùng tần suất, in phần tử nhỏ nhất.',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\n# Tìm phần tử xuất hiện nhiều nhất\n',
    test_cases: [
      { input: '1 2 2 3 3 3 4', expected_output: '3', is_hidden: false },
      { input: '1 1 2 2', expected_output: '1', is_hidden: false },
      { input: '5', expected_output: '5', is_hidden: true },
    ],
    hints: ['Dùng dict đếm tần suất', 'Tìm max theo value, nếu bằng nhau lấy key nhỏ nhất'],
    order_index: 1,
  },
  {
    id: 140,
    lesson_id: 37,
    title: 'Đảo ngược dict',
    description: 'Nhập n (số cặp). n dòng tiếp: "key:value". Đảo ngược dict (value thành key, key thành value). In mỗi cặp mới trên 1 dòng "new_key:new_value", sắp xếp theo new_key.',
    difficulty: 'medium',
    starter_code: 'n = int(input())\nd = {}\nfor _ in range(n):\n    line = input()\n    k, v = line.split(":")\n    d[k] = v\n# Đảo ngược dict\n',
    test_cases: [
      { input: '3\na:1\nb:2\nc:3', expected_output: '1:a\n2:b\n3:c', is_hidden: false },
      { input: '2\nhello:xin chao\nbye:tam biet', expected_output: 'tam biet:bye\nxin chao:hello', is_hidden: true },
    ],
    hints: ['Tạo dict mới: {v: k for k, v in d.items()}', 'Sắp xếp theo key của dict mới'],
    order_index: 2,
  },
  {
    id: 141,
    lesson_id: 37,
    title: 'Gộp hai dict',
    description: 'Nhập 2 dict: dòng 1 là n1, n1 dòng tiếp "key:value", rồi n2, n2 dòng tiếp "key:value". Gộp 2 dict: nếu key trùng, cộng value (value là số nguyên). In mỗi cặp "key:value" sắp xếp theo key.',
    difficulty: 'hard',
    starter_code: 'n1 = int(input())\nd1 = {}\nfor _ in range(n1):\n    k, v = input().split(":")\n    d1[k] = int(v)\n\nn2 = int(input())\nd2 = {}\nfor _ in range(n2):\n    k, v = input().split(":")\n    d2[k] = int(v)\n# Gộp 2 dict\n',
    test_cases: [
      { input: '2\na:1\nb:2\n2\nb:3\nc:4', expected_output: 'a:1\nb:5\nc:4', is_hidden: false },
      { input: '1\nx:10\n1\ny:20', expected_output: 'x:10\ny:20', is_hidden: true },
    ],
    hints: ['Duyệt d2, nếu key có trong d1 thì cộng, nếu không thì thêm mới', 'Sắp xếp kết quả theo key'],
    order_index: 3,
  },

  // Lesson 38: Set
  {
    id: 142,
    lesson_id: 38,
    title: 'Phần tử duy nhất',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. In ra số lượng phần tử duy nhất (không trùng lặp).',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\n# Đếm phần tử duy nhất\n',
    test_cases: [
      { input: '1 2 3 2 1 4 5 4', expected_output: '5', is_hidden: false },
      { input: '1 1 1 1', expected_output: '1', is_hidden: false },
      { input: '1 2 3 4 5', expected_output: '5', is_hidden: true },
    ],
    hints: ['Dùng set() để loại bỏ trùng lặp', 'len(set(numbers)) cho số phần tử duy nhất'],
    order_index: 1,
  },
  {
    id: 143,
    lesson_id: 38,
    title: 'Giao của hai tập hợp',
    description: 'Nhập 2 dòng, mỗi dòng là dãy số nguyên cách nhau bởi dấu cách. In ra các phần tử chung (giao) của 2 dãy, sắp xếp tăng dần, trên 1 dòng cách nhau bởi dấu cách. Nếu không có in "Rong".',
    difficulty: 'medium',
    starter_code: 'a = list(map(int, input().split()))\nb = list(map(int, input().split()))\n# Tìm giao 2 tập hợp\n',
    test_cases: [
      { input: '1 2 3 4 5\n3 4 5 6 7', expected_output: '3 4 5', is_hidden: false },
      { input: '1 2 3\n4 5 6', expected_output: 'Rong', is_hidden: false },
      { input: '1 1 2 2\n2 2 3 3', expected_output: '2', is_hidden: true },
    ],
    hints: ['Dùng set(a) & set(b) hoặc .intersection()', 'Sắp xếp kết quả bằng sorted()'],
    order_index: 2,
  },
  {
    id: 144,
    lesson_id: 38,
    title: 'Hiệu đối xứng',
    description: 'Nhập 2 dòng, mỗi dòng là dãy số nguyên cách nhau bởi dấu cách. In ra hiệu đối xứng (symmetric difference - phần tử chỉ thuộc 1 trong 2 tập), sắp xếp tăng dần.',
    difficulty: 'hard',
    starter_code: 'a = list(map(int, input().split()))\nb = list(map(int, input().split()))\n# Tìm hiệu đối xứng\n',
    test_cases: [
      { input: '1 2 3 4\n3 4 5 6', expected_output: '1 2 5 6', is_hidden: false },
      { input: '1 2 3\n1 2 3', expected_output: '', is_hidden: false },
      { input: '10 20\n30 40', expected_output: '10 20 30 40', is_hidden: true },
    ],
    hints: ['Dùng set(a) ^ set(b) hoặc .symmetric_difference()', 'Sắp xếp kết quả'],
    order_index: 3,
  },

  // Lesson 39: Counter
  {
    id: 145,
    lesson_id: 39,
    title: 'Top K phần tử phổ biến',
    description: 'Dòng 1: n số nguyên cách nhau bởi dấu cách. Dòng 2: số k. In ra k phần tử xuất hiện nhiều nhất, sắp xếp theo tần suất giảm dần. Nếu bằng nhau, phần tử nhỏ hơn trước. Mỗi phần tử 1 dòng.',
    difficulty: 'easy',
    starter_code: 'numbers = list(map(int, input().split()))\nk = int(input())\n# Tìm top k phần tử phổ biến\n',
    test_cases: [
      { input: '1 1 1 2 2 3\n2', expected_output: '1\n2', is_hidden: false },
      { input: '4 4 4 3 3 2 2 1\n3', expected_output: '4\n2\n3', is_hidden: false },
      { input: '5 5 5\n1', expected_output: '5', is_hidden: true },
    ],
    hints: ['Dùng Counter hoặc dict đếm tần suất', 'Sắp xếp theo (-count, value) rồi lấy k phần tử đầu'],
    order_index: 1,
  },
  {
    id: 146,
    lesson_id: 39,
    title: 'Kiểm tra anagram',
    description: 'Nhập 2 chuỗi (chỉ chữ cái thường) trên 2 dòng. Kiểm tra xem 2 chuỗi có phải anagram không (cùng các ký tự, khác thứ tự). In "Yes" hoặc "No".',
    difficulty: 'medium',
    starter_code: 's1 = input()\ns2 = input()\n# Kiểm tra anagram\n',
    test_cases: [
      { input: 'listen\nsilent', expected_output: 'Yes', is_hidden: false },
      { input: 'hello\nworld', expected_output: 'No', is_hidden: false },
      { input: 'anagram\nnagaram', expected_output: 'Yes', is_hidden: true },
    ],
    hints: ['Anagram: 2 chuỗi có cùng tần suất ký tự', 'Dùng Counter(s1) == Counter(s2)', 'Hoặc sorted(s1) == sorted(s2)'],
    order_index: 2,
  },
  {
    id: 147,
    lesson_id: 39,
    title: 'Nhóm theo tần suất',
    description: 'Nhập n số nguyên trên 1 dòng cách nhau bởi dấu cách. Nhóm các số theo tần suất xuất hiện. In mỗi dòng: "Tan suat <f>: <cac_so>" (các số cách nhau bởi dấu cách, sắp xếp tăng dần). In theo tần suất giảm dần.',
    difficulty: 'hard',
    starter_code: 'numbers = list(map(int, input().split()))\n# Nhóm theo tần suất\n',
    test_cases: [
      { input: '1 2 2 3 3 3', expected_output: 'Tan suat 3: 3\nTan suat 2: 2\nTan suat 1: 1', is_hidden: false },
      { input: '5 5 3 3 1 1', expected_output: 'Tan suat 2: 1 3 5', is_hidden: false },
      { input: '7', expected_output: 'Tan suat 1: 7', is_hidden: true },
    ],
    hints: ['Đếm tần suất, rồi nhóm ngược: freq -> list of numbers', 'Sắp xếp theo tần suất giảm dần'],
    order_index: 3,
  },

  // Lesson 40: Dict + List
  {
    id: 148,
    lesson_id: 40,
    title: 'Bảng điểm học sinh',
    description: 'Dòng 1: n (số học sinh). n dòng tiếp: "ten,diem1,diem2,diem3". Tính điểm trung bình mỗi học sinh. In tên và điểm TB (làm tròn 1 chữ số) của học sinh có điểm TB cao nhất. Format: "<ten>: <dtb>".',
    difficulty: 'easy',
    starter_code: 'n = int(input())\nstudents = {}\nfor _ in range(n):\n    parts = input().split(",")\n    # Lưu thông tin học sinh\n\n# Tìm học sinh có điểm TB cao nhất\n',
    test_cases: [
      { input: '3\nAn,8,9,7\nBinh,6,7,8\nChi,9,10,9', expected_output: 'Chi: 9.3', is_hidden: false },
      { input: '2\nX,5,5,5\nY,10,10,10', expected_output: 'Y: 10.0', is_hidden: true },
    ],
    hints: ['Lưu dict: {ten: [diem1, diem2, diem3]}', 'Tính TB: sum(scores) / len(scores)'],
    order_index: 1,
  },
  {
    id: 149,
    lesson_id: 40,
    title: 'Sắp xếp dict theo value',
    description: 'Dòng 1: n (số cặp). n dòng tiếp: "key:value" (value là số nguyên). Sắp xếp theo value tăng dần. In mỗi cặp "key:value" trên 1 dòng. Nếu value bằng nhau, sắp xếp key theo alphabet.',
    difficulty: 'medium',
    starter_code: 'n = int(input())\nd = {}\nfor _ in range(n):\n    k, v = input().split(":")\n    d[k] = int(v)\n# Sắp xếp theo value\n',
    test_cases: [
      { input: '4\nbanana:3\napple:1\ncherry:2\ndate:1', expected_output: 'apple:1\ndate:1\ncherry:2\nbanana:3', is_hidden: false },
      { input: '2\nb:10\na:5', expected_output: 'a:5\nb:10', is_hidden: true },
    ],
    hints: ['sorted(d.items(), key=lambda x: (x[1], x[0]))', 'Sắp xếp theo tuple (value, key)'],
    order_index: 2,
  },
  {
    id: 150,
    lesson_id: 40,
    title: 'Tra cứu lồng nhau',
    description: 'Dòng 1: n (số học sinh). n dòng tiếp: "ten,mon1:diem1,mon2:diem2,...". Dòng cuối: "ten,mon" cần tra. In điểm của học sinh đó môn đó. Nếu không tìm thấy in "Khong tim thay".',
    difficulty: 'hard',
    starter_code: 'n = int(input())\ndata = {}\nfor _ in range(n):\n    parts = input().split(",")\n    # Lưu dữ liệu lồng nhau\n\nquery = input().split(",")\n# Tra cứu\n',
    test_cases: [
      { input: '2\nAn,Toan:9,Ly:8,Hoa:7\nBinh,Toan:6,Ly:9,Hoa:8\nAn,Ly', expected_output: '8', is_hidden: false },
      { input: '1\nChi,Toan:10,Van:9\nChi,Anh', expected_output: 'Khong tim thay', is_hidden: false },
      { input: '1\nDung,Toan:7\nEm,Toan', expected_output: 'Khong tim thay', is_hidden: true },
    ],
    hints: ['Lưu: data[ten] = {mon: diem}', 'Tra cứu: data.get(ten, {}).get(mon, "Khong tim thay")'],
    order_index: 3,
  },

];
