import type { Problem } from './problem-bank';

export const PROBLEM_BANK_2: Problem[] = [
  // ==================== MEDIUM: SLIDING WINDOW (201-210) ====================
  {
    id: 201,
    slug: 'max-sum-subarray-k',
    title: 'Tổng Lớn Nhất Mảng Con Kích Thước K',
    description: 'Cho mảng n số nguyên và số K. Tìm tổng lớn nhất của mảng con liên tiếp có đúng K phần tử. In ra tổng lớn nhất tìm được.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Mảng'],
    acceptanceRate: 58,
    xp: 30,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# Tìm tổng lớn nhất mảng con kích thước k\n',
    testCases: [
      { input: '7 3\n2 1 5 1 3 2 8', expectedOutput: '13', isHidden: false },
      { input: '5 2\n1 2 3 4 5', expectedOutput: '9', isHidden: false },
      { input: '3 3\n-1 -2 -3', expectedOutput: '-6', isHidden: true },
    ],
    hints: ['Tính tổng K phần tử đầu tiên', 'Trượt cửa sổ: thêm phần tử mới, bỏ phần tử cũ', 'Cập nhật max sau mỗi bước trượt'],
    editorial: {
      approach: 'Sliding Window: tính tổng cửa sổ đầu tiên, sau đó trượt bằng cách cộng phần tử mới và trừ phần tử cũ.',
      code: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\nwindow_sum = sum(arr[:k])\nmax_sum = window_sum\nfor i in range(k, n):\n    window_sum += arr[i] - arr[i - k]\n    max_sum = max(max_sum, window_sum)\nprint(max_sum)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 202,
    slug: 'smallest-subarray-sum-geq-s',
    title: 'Mảng Con Ngắn Nhất Có Tổng >= S',
    description: 'Cho mảng n số nguyên dương và số S. Tìm độ dài mảng con liên tiếp ngắn nhất có tổng lớn hơn hoặc bằng S. Nếu không tồn tại, in 0.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Mảng'],
    acceptanceRate: 45,
    xp: 35,
    starterCode: 'n, s = map(int, input().split())\narr = list(map(int, input().split()))\n# Tìm độ dài mảng con ngắn nhất có tổng >= s\n',
    testCases: [
      { input: '6 7\n2 3 1 2 4 3', expectedOutput: '2', isHidden: false },
      { input: '3 11\n1 2 3', expectedOutput: '0', isHidden: false },
      { input: '5 15\n5 1 3 5 10', expectedOutput: '2', isHidden: true },
      { input: '1 5\n5', expectedOutput: '1', isHidden: true },
    ],
    hints: ['Dùng hai con trỏ left và right', 'Mở rộng right cho đến khi tổng >= S', 'Thu hẹp left để tìm độ dài nhỏ nhất'],
    editorial: {
      approach: 'Sliding Window co giãn: mở rộng cửa sổ bên phải, khi tổng >= S thì thu hẹp bên trái và cập nhật kết quả.',
      code: 'n, s = map(int, input().split())\narr = list(map(int, input().split()))\nleft = 0\ncur_sum = 0\nmin_len = float("inf")\nfor right in range(n):\n    cur_sum += arr[right]\n    while cur_sum >= s:\n        min_len = min(min_len, right - left + 1)\n        cur_sum -= arr[left]\n        left += 1\nprint(0 if min_len == float("inf") else min_len)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 203,
    slug: 'longest-substring-no-repeat',
    title: 'Chuỗi Con Dài Nhất Không Lặp Ký Tự',
    description: 'Cho chuỗi s chỉ gồm chữ cái thường. Tìm độ dài chuỗi con liên tiếp dài nhất mà không có ký tự nào lặp lại.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Chuỗi', 'Hash Set'],
    acceptanceRate: 42,
    xp: 40,
    starterCode: 's = input()\n# Tìm độ dài chuỗi con dài nhất không lặp ký tự\n',
    testCases: [
      { input: 'abcabcbb', expectedOutput: '3', isHidden: false },
      { input: 'bbbbb', expectedOutput: '1', isHidden: false },
      { input: 'pwwkew', expectedOutput: '3', isHidden: true },
      { input: 'abcdefg', expectedOutput: '7', isHidden: true },
    ],
    hints: ['Dùng set để theo dõi ký tự trong cửa sổ hiện tại', 'Khi gặp ký tự trùng, thu hẹp cửa sổ từ bên trái', 'Cập nhật max_len sau mỗi bước'],
    editorial: {
      approach: 'Sliding Window + Hash Set: mở rộng cửa sổ bên phải, khi gặp ký tự trùng thì loại bỏ từ bên trái cho đến khi hết trùng.',
      code: 's = input()\nchar_set = set()\nleft = 0\nmax_len = 0\nfor right in range(len(s)):\n    while s[right] in char_set:\n        char_set.remove(s[left])\n        left += 1\n    char_set.add(s[right])\n    max_len = max(max_len, right - left + 1)\nprint(max_len)',
      complexity: 'Time: O(n), Space: O(min(n, 26))',
    },
  },
  {
    id: 204,
    slug: 'max-consecutive-ones-k-flips',
    title: 'Dãy 1 Liên Tiếp Dài Nhất (Đổi K Số 0)',
    description: 'Cho mảng nhị phân (chỉ gồm 0 và 1) và số K. Bạn được phép đổi tối đa K số 0 thành 1. Tìm độ dài dãy 1 liên tiếp dài nhất có thể đạt được.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Mảng'],
    acceptanceRate: 48,
    xp: 35,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# Tìm dãy 1 liên tiếp dài nhất sau khi đổi tối đa k số 0\n',
    testCases: [
      { input: '10 2\n1 1 0 0 1 1 1 0 1 1', expectedOutput: '7', isHidden: false },
      { input: '5 1\n0 0 0 0 0', expectedOutput: '1', isHidden: false },
      { input: '6 3\n1 0 1 0 1 0', expectedOutput: '6', isHidden: true },
    ],
    hints: ['Dùng sliding window, đếm số lượng 0 trong cửa sổ', 'Khi số 0 vượt quá K, thu hẹp cửa sổ từ trái', 'Kết quả là kích thước cửa sổ lớn nhất'],
    editorial: {
      approach: 'Sliding Window: duy trì cửa sổ chứa tối đa K số 0. Khi vượt quá, thu hẹp từ trái.',
      code: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\nleft = 0\nzeros = 0\nmax_len = 0\nfor right in range(n):\n    if arr[right] == 0:\n        zeros += 1\n    while zeros > k:\n        if arr[left] == 0:\n            zeros -= 1\n        left += 1\n    max_len = max(max_len, right - left + 1)\nprint(max_len)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 205,
    slug: 'longest-repeating-char-replacement',
    title: 'Thay Thế Ký Tự - Chuỗi Dài Nhất Cùng Ký Tự',
    description: 'Cho chuỗi s gồm chữ cái in hoa và số K. Bạn được thay tối đa K ký tự bất kỳ. Tìm độ dài chuỗi con dài nhất chỉ chứa một loại ký tự sau khi thay thế.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Chuỗi'],
    acceptanceRate: 40,
    xp: 40,
    starterCode: 's = input()\nk = int(input())\n# Tìm chuỗi con dài nhất cùng ký tự sau khi thay tối đa k ký tự\n',
    testCases: [
      { input: 'AABABBA\n1', expectedOutput: '4', isHidden: false },
      { input: 'ABAB\n2', expectedOutput: '4', isHidden: false },
      { input: 'AAAA\n0', expectedOutput: '4', isHidden: true },
    ],
    hints: ['Dùng sliding window, đếm tần suất ký tự trong cửa sổ', 'Điều kiện hợp lệ: window_size - max_freq <= K', 'Khi vi phạm, thu hẹp cửa sổ từ trái'],
    editorial: {
      approach: 'Sliding Window: duy trì cửa sổ sao cho (kích thước - tần suất ký tự xuất hiện nhiều nhất) <= K.',
      code: 's = input()\nk = int(input())\nfrom collections import defaultdict\nfreq = defaultdict(int)\nleft = 0\nmax_freq = 0\nmax_len = 0\nfor right in range(len(s)):\n    freq[s[right]] += 1\n    max_freq = max(max_freq, freq[s[right]])\n    while (right - left + 1) - max_freq > k:\n        freq[s[left]] -= 1\n        left += 1\n    max_len = max(max_len, right - left + 1)\nprint(max_len)',
      complexity: 'Time: O(n), Space: O(26)',
    },
  },
  {
    id: 206,
    slug: 'fruits-into-baskets',
    title: 'Thu Hoạch Trái Cây (Tối Đa 2 Loại)',
    description: 'Cho mảng n số nguyên đại diện cho loại trái cây trên từng cây. Bạn có 2 giỏ, mỗi giỏ chỉ chứa 1 loại. Tìm số lượng trái cây tối đa có thể thu hoạch liên tiếp.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Hash Map'],
    acceptanceRate: 44,
    xp: 35,
    starterCode: 'n = int(input())\nfruits = list(map(int, input().split()))\n# Tìm số trái cây tối đa thu hoạch liên tiếp với 2 giỏ\n',
    testCases: [
      { input: '5\n1 2 1 2 3', expectedOutput: '4', isHidden: false },
      { input: '6\n0 1 2 2 2 2', expectedOutput: '5', isHidden: false },
      { input: '4\n3 3 3 3', expectedOutput: '4', isHidden: true },
    ],
    hints: ['Bài toán tương đương: tìm mảng con dài nhất chứa tối đa 2 giá trị khác nhau', 'Dùng dict đếm số loại trong cửa sổ', 'Khi có > 2 loại, thu hẹp từ trái'],
    editorial: {
      approach: 'Sliding Window + Hash Map: duy trì cửa sổ chứa tối đa 2 loại trái cây.',
      code: 'n = int(input())\nfruits = list(map(int, input().split()))\nfrom collections import defaultdict\nbasket = defaultdict(int)\nleft = 0\nmax_fruits = 0\nfor right in range(n):\n    basket[fruits[right]] += 1\n    while len(basket) > 2:\n        basket[fruits[left]] -= 1\n        if basket[fruits[left]] == 0:\n            del basket[fruits[left]]\n        left += 1\n    max_fruits = max(max_fruits, right - left + 1)\nprint(max_fruits)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 207,
    slug: 'permutation-in-string',
    title: 'Kiểm Tra Hoán Vị Trong Chuỗi',
    description: 'Cho hai chuỗi s1 và s2 gồm chữ cái thường. Kiểm tra xem s2 có chứa một hoán vị của s1 như chuỗi con hay không. In "YES" hoặc "NO".',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Chuỗi', 'Hash Map'],
    acceptanceRate: 43,
    xp: 40,
    starterCode: 's1 = input()\ns2 = input()\n# Kiểm tra s2 có chứa hoán vị của s1 không\n',
    testCases: [
      { input: 'ab\neidbaooo', expectedOutput: 'YES', isHidden: false },
      { input: 'ab\neidboaoo', expectedOutput: 'NO', isHidden: false },
      { input: 'adc\ndcda', expectedOutput: 'YES', isHidden: true },
    ],
    hints: ['Dùng cửa sổ kích thước len(s1) trượt trên s2', 'So sánh tần suất ký tự trong cửa sổ với tần suất s1', 'Dùng mảng 26 phần tử thay vì dict để nhanh hơn'],
    editorial: {
      approach: 'Sliding Window kích thước cố định: so sánh tần suất ký tự cửa sổ với tần suất s1.',
      code: 's1 = input()\ns2 = input()\nfrom collections import Counter\nif len(s1) > len(s2):\n    print("NO")\nelse:\n    freq1 = Counter(s1)\n    window = Counter(s2[:len(s1)])\n    if window == freq1:\n        print("YES")\n    else:\n        found = False\n        for i in range(len(s1), len(s2)):\n            window[s2[i]] += 1\n            window[s2[i - len(s1)]] -= 1\n            if window[s2[i - len(s1)]] == 0:\n                del window[s2[i - len(s1)]]\n            if window == freq1:\n                found = True\n                break\n        print("YES" if found else "NO")',
      complexity: 'Time: O(n), Space: O(26)',
    },
  },
  {
    id: 208,
    slug: 'max-average-subarray',
    title: 'Trung Bình Lớn Nhất Mảng Con Kích Thước K',
    description: 'Cho mảng n số nguyên và số K. Tìm giá trị trung bình lớn nhất của mảng con liên tiếp có đúng K phần tử. In kết quả với 5 chữ số thập phân.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Mảng'],
    acceptanceRate: 55,
    xp: 30,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# Tìm trung bình lớn nhất mảng con kích thước k\n',
    testCases: [
      { input: '6 4\n1 12 -5 -6 50 3', expectedOutput: '12.75000', isHidden: false },
      { input: '5 1\n5 3 8 2 1', expectedOutput: '8.00000', isHidden: false },
      { input: '4 2\n-1 -2 -3 -4', expectedOutput: '-1.50000', isHidden: true },
    ],
    hints: ['Tương tự bài tổng lớn nhất, nhưng chia cho K', 'Dùng sliding window kích thước K', 'Chú ý format output 5 chữ số thập phân'],
    editorial: {
      approach: 'Sliding Window kích thước K: tìm tổng lớn nhất rồi chia cho K.',
      code: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\nwindow_sum = sum(arr[:k])\nmax_sum = window_sum\nfor i in range(k, n):\n    window_sum += arr[i] - arr[i - k]\n    max_sum = max(max_sum, window_sum)\nprint(f"{max_sum / k:.5f}")',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 209,
    slug: 'count-subarrays-sum-equals-k',
    title: 'Đếm Mảng Con Có Tổng Bằng K',
    description: 'Cho mảng n số nguyên (có thể âm) và số K. Đếm số lượng mảng con liên tiếp có tổng đúng bằng K.',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Hash Map', 'Prefix Sum'],
    acceptanceRate: 38,
    xp: 45,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# Đếm số mảng con có tổng bằng k\n',
    testCases: [
      { input: '4 3\n1 1 1 2', expectedOutput: '2', isHidden: false },
      { input: '3 0\n1 -1 0', expectedOutput: '3', isHidden: false },
      { input: '5 5\n5 0 5 -5 5', expectedOutput: '5', isHidden: true },
    ],
    hints: ['Dùng prefix sum: sum[i..j] = prefix[j] - prefix[i-1]', 'Cần đếm số prefix[i] sao cho prefix[j] - prefix[i] = K', 'Dùng hash map lưu số lần xuất hiện của mỗi prefix sum'],
    editorial: {
      approach: 'Prefix Sum + Hash Map: với mỗi prefix sum hiện tại, đếm số lần (prefix - K) đã xuất hiện trước đó.',
      code: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\nfrom collections import defaultdict\nprefix_count = defaultdict(int)\nprefix_count[0] = 1\ncur_sum = 0\ncount = 0\nfor num in arr:\n    cur_sum += num\n    count += prefix_count[cur_sum - k]\n    prefix_count[cur_sum] += 1\nprint(count)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 210,
    slug: 'min-window-substring',
    title: 'Cửa Sổ Nhỏ Nhất Chứa Tất Cả Ký Tự',
    description: 'Cho chuỗi s và chuỗi t gồm chữ cái thường. Tìm chuỗi con ngắn nhất của s chứa tất cả ký tự của t (kể cả trùng lặp). Nếu không tồn tại, in "NONE".',
    difficulty: 'medium',
    tags: ['Sliding Window', 'Chuỗi', 'Hash Map'],
    acceptanceRate: 35,
    xp: 50,
    starterCode: 's = input()\nt = input()\n# Tìm cửa sổ nhỏ nhất của s chứa tất cả ký tự của t\n',
    testCases: [
      { input: 'adobecodebanc\nabc', expectedOutput: 'banc', isHidden: false },
      { input: 'a\na', expectedOutput: 'a', isHidden: false },
      { input: 'a\naa', expectedOutput: 'NONE', isHidden: true },
      { input: 'cabwefgewcwaefgcf\ncae', expectedOutput: 'cwae', isHidden: true },
    ],
    hints: ['Dùng hash map đếm ký tự cần thiết từ t', 'Mở rộng cửa sổ bên phải, khi đủ ký tự thì thu hẹp bên trái', 'Dùng biến formed đếm số ký tự đã thỏa mãn'],
    editorial: {
      approach: 'Sliding Window co giãn: mở rộng phải cho đến khi chứa đủ ký tự t, sau đó thu hẹp trái để tìm cửa sổ nhỏ nhất.',
      code: 's = input()\nt = input()\nfrom collections import Counter\nif not t or not s:\n    print("NONE")\nelse:\n    need = Counter(t)\n    have = {}\n    formed = 0\n    required = len(need)\n    left = 0\n    min_len = float("inf")\n    min_start = 0\n    for right in range(len(s)):\n        c = s[right]\n        have[c] = have.get(c, 0) + 1\n        if c in need and have[c] == need[c]:\n            formed += 1\n        while formed == required:\n            if right - left + 1 < min_len:\n                min_len = right - left + 1\n                min_start = left\n            have[s[left]] -= 1\n            if s[left] in need and have[s[left]] < need[s[left]]:\n                formed -= 1\n            left += 1\n    print(s[min_start:min_start + min_len] if min_len != float("inf") else "NONE")',
      complexity: 'Time: O(n + m), Space: O(n + m)',
    },
  },

  // ==================== MEDIUM: STACK & QUEUE (211-220) ====================
  {
    id: 211,
    slug: 'daily-temperatures',
    title: 'Nhiệt Độ Hàng Ngày',
    description: 'Cho mảng n số nguyên đại diện nhiệt độ mỗi ngày. Với mỗi ngày, tìm số ngày phải chờ để gặp ngày có nhiệt độ cao hơn. Nếu không có, trả về 0.',
    difficulty: 'medium',
    tags: ['Stack', 'Mảng'],
    acceptanceRate: 52,
    xp: 35,
    starterCode: 'n = int(input())\ntemps = list(map(int, input().split()))\n# In ra mảng số ngày chờ cho mỗi ngày\n',
    testCases: [
      { input: '8\n73 74 75 71 69 72 76 73', expectedOutput: '1 1 4 2 1 1 0 0', isHidden: false },
      { input: '4\n30 40 50 60', expectedOutput: '1 1 1 0', isHidden: false },
      { input: '3\n50 40 30', expectedOutput: '0 0 0', isHidden: true },
    ],
    hints: ['Dùng stack lưu chỉ số các ngày chưa tìm được ngày nóng hơn', 'Khi gặp ngày nóng hơn đỉnh stack, pop và tính khoảng cách', 'Duyệt từ trái sang phải'],
    editorial: {
      approach: 'Monotone Stack: dùng stack giảm dần lưu chỉ số. Khi gặp nhiệt độ cao hơn đỉnh stack, pop và ghi kết quả.',
      code: 'n = int(input())\ntemps = list(map(int, input().split()))\nresult = [0] * n\nstack = []\nfor i in range(n):\n    while stack and temps[i] > temps[stack[-1]]:\n        idx = stack.pop()\n        result[idx] = i - idx\n    stack.append(i)\nprint(*result)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 212,
    slug: 'evaluate-rpn',
    title: 'Tính Biểu Thức Hậu Tố (RPN)',
    description: 'Cho biểu thức hậu tố (Reverse Polish Notation) gồm các số nguyên và phép toán +, -, *, /. Tính giá trị biểu thức. Phép chia lấy phần nguyên hướng về 0.',
    difficulty: 'medium',
    tags: ['Stack', 'Toán'],
    acceptanceRate: 50,
    xp: 35,
    starterCode: 'tokens = input().split()\n# Tính giá trị biểu thức hậu tố\n',
    testCases: [
      { input: '2 1 + 3 *', expectedOutput: '9', isHidden: false },
      { input: '4 13 5 / +', expectedOutput: '6', isHidden: false },
      { input: '10 6 9 3 + -11 * / * 17 + 5 +', expectedOutput: '22', isHidden: true },
    ],
    hints: ['Dùng stack: gặp số thì push, gặp phép toán thì pop 2 số và tính', 'Chú ý thứ tự: pop ra b trước, a sau, kết quả là a op b', 'Phép chia: dùng int(a/b) để chia hướng về 0'],
    editorial: {
      approach: 'Stack: duyệt từng token, nếu là số thì push, nếu là phép toán thì pop 2 số, tính và push kết quả.',
      code: 'tokens = input().split()\nstack = []\nfor token in tokens:\n    if token in "+-*/":\n        b = stack.pop()\n        a = stack.pop()\n        if token == "+":\n            stack.append(a + b)\n        elif token == "-":\n            stack.append(a - b)\n        elif token == "*":\n            stack.append(a * b)\n        else:\n            stack.append(int(a / b))\n    else:\n        stack.append(int(token))\nprint(stack[0])',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 213,
    slug: 'valid-parentheses-types',
    title: 'Kiểm Tra Ngoặc Hợp Lệ (3 Loại)',
    description: 'Cho chuỗi chỉ gồm các ký tự ()[]{}. Kiểm tra xem chuỗi có hợp lệ không (mỗi ngoặc mở có ngoặc đóng tương ứng đúng thứ tự). In "YES" hoặc "NO".',
    difficulty: 'medium',
    tags: ['Stack', 'Chuỗi'],
    acceptanceRate: 60,
    xp: 25,
    starterCode: 's = input()\n# Kiểm tra chuỗi ngoặc hợp lệ\n',
    testCases: [
      { input: '()[]{} ', expectedOutput: 'YES', isHidden: false },
      { input: '([)]', expectedOutput: 'NO', isHidden: false },
      { input: '{[()]}', expectedOutput: 'YES', isHidden: true },
      { input: '(', expectedOutput: 'NO', isHidden: true },
    ],
    hints: ['Dùng stack: gặp ngoặc mở thì push', 'Gặp ngoặc đóng thì kiểm tra đỉnh stack có phải ngoặc mở tương ứng', 'Cuối cùng stack phải rỗng'],
    editorial: {
      approach: 'Stack: push ngoặc mở, khi gặp ngoặc đóng kiểm tra match với đỉnh stack.',
      code: 's = input().strip()\nstack = []\nmatch = {")": "(", "]": "[", "}": "{"}\nvalid = True\nfor c in s:\n    if c in "([{":\n        stack.append(c)\n    elif c in ")]}":\n        if not stack or stack[-1] != match[c]:\n            valid = False\n            break\n        stack.pop()\nprint("YES" if valid and not stack else "NO")',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 214,
    slug: 'asteroid-collision',
    title: 'Va Chạm Thiên Thạch',
    description: 'Cho mảng n số nguyên đại diện thiên thạch. Giá trị dương đi sang phải, âm đi sang trái. Khi hai thiên thạch va chạm, thiên thạch nhỏ hơn nổ tung. Nếu bằng nhau, cả hai nổ. Tìm trạng thái cuối cùng.',
    difficulty: 'medium',
    tags: ['Stack', 'Mảng'],
    acceptanceRate: 42,
    xp: 40,
    starterCode: 'n = int(input())\nasteroids = list(map(int, input().split()))\n# Tìm trạng thái cuối cùng sau va chạm\n',
    testCases: [
      { input: '4\n5 10 -5 -10', expectedOutput: '5', isHidden: false },
      { input: '3\n-2 -1 1', expectedOutput: '-2 -1 1', isHidden: false },
      { input: '2\n10 -10', expectedOutput: '', isHidden: true },
      { input: '4\n1 -2 -2 -2', expectedOutput: '-2 -2 -2', isHidden: true },
    ],
    hints: ['Dùng stack: push thiên thạch vào', 'Va chạm xảy ra khi đỉnh stack > 0 và thiên thạch hiện tại < 0', 'So sánh kích thước để quyết định ai nổ'],
    editorial: {
      approach: 'Stack: duyệt từng thiên thạch, xử lý va chạm khi đỉnh stack dương và thiên thạch hiện tại âm.',
      code: 'n = int(input())\nasteroids = list(map(int, input().split()))\nstack = []\nfor ast in asteroids:\n    alive = True\n    while stack and ast < 0 < stack[-1]:\n        if stack[-1] < -ast:\n            stack.pop()\n        elif stack[-1] == -ast:\n            stack.pop()\n            alive = False\n            break\n        else:\n            alive = False\n            break\n    if alive:\n        stack.append(ast)\nprint(*stack if stack else "")',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 215,
    slug: 'queue-using-stacks',
    title: 'Cài Đặt Queue Bằng 2 Stack',
    description: 'Cài đặt hàng đợi (FIFO) sử dụng 2 stack. Xử lý Q thao tác: "PUSH x" thêm x, "POP" lấy ra phần tử đầu, "PEEK" xem phần tử đầu. In kết quả mỗi POP và PEEK.',
    difficulty: 'medium',
    tags: ['Stack', 'Queue', 'Thiết kế'],
    acceptanceRate: 55,
    xp: 30,
    starterCode: 'q = int(input())\n# Cài đặt queue bằng 2 stack, xử lý q thao tác\n',
    testCases: [
      { input: '5\nPUSH 1\nPUSH 2\nPEEK\nPOP\nPEEK', expectedOutput: '1\n1\n2', isHidden: false },
      { input: '4\nPUSH 10\nPUSH 20\nPOP\nPOP', expectedOutput: '10\n20', isHidden: false },
      { input: '6\nPUSH 5\nPUSH 3\nPUSH 8\nPOP\nPOP\nPOP', expectedOutput: '5\n3\n8', isHidden: true },
    ],
    hints: ['Dùng stack_in để push, stack_out để pop/peek', 'Khi stack_out rỗng, chuyển hết từ stack_in sang stack_out', 'Thao tác amortized O(1)'],
    editorial: {
      approach: 'Dùng 2 stack: stack_in nhận push, stack_out phục vụ pop/peek. Khi stack_out rỗng, đổ hết stack_in sang.',
      code: 'q = int(input())\nstack_in = []\nstack_out = []\nresults = []\nfor _ in range(q):\n    op = input().split()\n    if op[0] == "PUSH":\n        stack_in.append(int(op[1]))\n    else:\n        if not stack_out:\n            while stack_in:\n                stack_out.append(stack_in.pop())\n        if op[0] == "POP":\n            results.append(str(stack_out.pop()))\n        else:\n            results.append(str(stack_out[-1]))\nprint("\\n".join(results))',
      complexity: 'Time: Amortized O(1) mỗi thao tác, Space: O(n)',
    },
  },
  {
    id: 216,
    slug: 'next-greater-element',
    title: 'Phần Tử Lớn Hơn Tiếp Theo',
    description: 'Cho mảng n số nguyên. Với mỗi phần tử, tìm phần tử lớn hơn đầu tiên bên phải nó. Nếu không có, trả về -1.',
    difficulty: 'medium',
    tags: ['Stack', 'Mảng'],
    acceptanceRate: 54,
    xp: 30,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm phần tử lớn hơn tiếp theo cho mỗi phần tử\n',
    testCases: [
      { input: '4\n4 5 2 25', expectedOutput: '5 25 25 -1', isHidden: false },
      { input: '4\n13 7 6 12', expectedOutput: '-1 12 12 -1', isHidden: false },
      { input: '3\n1 2 3', expectedOutput: '2 3 -1', isHidden: true },
    ],
    hints: ['Dùng stack giảm dần (monotone decreasing stack)', 'Duyệt từ phải sang trái', 'Với mỗi phần tử, pop stack cho đến khi tìm được phần tử lớn hơn'],
    editorial: {
      approach: 'Monotone Stack: duyệt từ phải sang trái, dùng stack giữ các phần tử theo thứ tự giảm dần.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nresult = [-1] * n\nstack = []\nfor i in range(n - 1, -1, -1):\n    while stack and stack[-1] <= arr[i]:\n        stack.pop()\n    if stack:\n        result[i] = stack[-1]\n    stack.append(arr[i])\nprint(*result)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 217,
    slug: 'min-stack',
    title: 'Stack Hỗ Trợ Tìm Min O(1)',
    description: 'Cài đặt stack hỗ trợ thao tác getMin() trong O(1). Xử lý Q thao tác: "PUSH x", "POP", "MIN" (in giá trị nhỏ nhất hiện tại).',
    difficulty: 'medium',
    tags: ['Stack', 'Thiết kế'],
    acceptanceRate: 58,
    xp: 30,
    starterCode: 'q = int(input())\n# Cài đặt min stack, xử lý q thao tác\n',
    testCases: [
      { input: '6\nPUSH -2\nPUSH 0\nPUSH -3\nMIN\nPOP\nMIN', expectedOutput: '-3\n-2', isHidden: false },
      { input: '4\nPUSH 5\nPUSH 3\nMIN\nMIN', expectedOutput: '3\n3', isHidden: false },
      { input: '5\nPUSH 1\nPUSH 1\nPOP\nMIN\nPOP', expectedOutput: '1', isHidden: true },
    ],
    hints: ['Dùng stack phụ lưu giá trị min tại mỗi thời điểm', 'Khi push, push min(x, min hiện tại) vào stack phụ', 'Khi pop, pop cả hai stack'],
    editorial: {
      approach: 'Dùng stack phụ song song lưu giá trị min tương ứng tại mỗi vị trí.',
      code: 'q = int(input())\nstack = []\nmin_stack = []\nresults = []\nfor _ in range(q):\n    op = input().split()\n    if op[0] == "PUSH":\n        x = int(op[1])\n        stack.append(x)\n        min_stack.append(min(x, min_stack[-1] if min_stack else x))\n    elif op[0] == "POP":\n        stack.pop()\n        min_stack.pop()\n    else:\n        results.append(str(min_stack[-1]))\nprint("\\n".join(results))',
      complexity: 'Time: O(1) mỗi thao tác, Space: O(n)',
    },
  },
  {
    id: 218,
    slug: 'largest-rectangle-histogram',
    title: 'Hình Chữ Nhật Lớn Nhất Trong Histogram',
    description: 'Cho mảng n số nguyên dương đại diện chiều cao các cột histogram (chiều rộng mỗi cột = 1). Tìm diện tích hình chữ nhật lớn nhất có thể tạo được.',
    difficulty: 'medium',
    tags: ['Stack', 'Mảng'],
    acceptanceRate: 36,
    xp: 50,
    starterCode: 'n = int(input())\nheights = list(map(int, input().split()))\n# Tìm diện tích HCN lớn nhất trong histogram\n',
    testCases: [
      { input: '6\n2 1 5 6 2 3', expectedOutput: '10', isHidden: false },
      { input: '2\n2 4', expectedOutput: '4', isHidden: false },
      { input: '5\n1 1 1 1 1', expectedOutput: '5', isHidden: true },
      { input: '1\n7', expectedOutput: '7', isHidden: true },
    ],
    hints: ['Dùng stack lưu chỉ số các cột theo thứ tự tăng dần chiều cao', 'Khi gặp cột thấp hơn đỉnh stack, pop và tính diện tích', 'Chiều rộng = khoảng cách từ cột hiện tại đến cột trước đỉnh stack'],
    editorial: {
      approach: 'Monotone Stack tăng dần: khi gặp cột thấp hơn, pop và tính diện tích với chiều cao = cột pop, chiều rộng = khoảng cách.',
      code: 'n = int(input())\nheights = list(map(int, input().split()))\nstack = []\nmax_area = 0\nfor i in range(n + 1):\n    h = heights[i] if i < n else 0\n    while stack and heights[stack[-1]] > h:\n        height = heights[stack.pop()]\n        width = i if not stack else i - stack[-1] - 1\n        max_area = max(max_area, height * width)\n    stack.append(i)\nprint(max_area)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 219,
    slug: 'sliding-window-maximum',
    title: 'Giá Trị Lớn Nhất Cửa Sổ Trượt',
    description: 'Cho mảng n số nguyên và số K. Trượt cửa sổ kích thước K từ trái sang phải. In giá trị lớn nhất trong mỗi vị trí cửa sổ.',
    difficulty: 'medium',
    tags: ['Queue', 'Deque', 'Sliding Window'],
    acceptanceRate: 38,
    xp: 45,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# In max của mỗi cửa sổ kích thước k\n',
    testCases: [
      { input: '8 3\n1 3 -1 -3 5 3 6 7', expectedOutput: '3 3 5 5 6 7', isHidden: false },
      { input: '5 2\n1 2 3 4 5', expectedOutput: '2 3 4 5', isHidden: false },
      { input: '4 4\n4 3 2 1', expectedOutput: '4', isHidden: true },
    ],
    hints: ['Dùng deque (hàng đợi hai đầu) lưu chỉ số', 'Duy trì deque giảm dần: loại bỏ phần tử nhỏ hơn phần tử mới', 'Loại bỏ phần tử ngoài cửa sổ từ đầu deque'],
    editorial: {
      approach: 'Monotone Deque giảm dần: duy trì deque chứa chỉ số theo thứ tự giá trị giảm dần, đầu deque luôn là max.',
      code: 'from collections import deque\nn, k = map(int, input().split())\narr = list(map(int, input().split()))\ndq = deque()\nresult = []\nfor i in range(n):\n    while dq and dq[0] < i - k + 1:\n        dq.popleft()\n    while dq and arr[dq[-1]] <= arr[i]:\n        dq.pop()\n    dq.append(i)\n    if i >= k - 1:\n        result.append(str(arr[dq[0]]))\nprint(" ".join(result))',
      complexity: 'Time: O(n), Space: O(k)',
    },
  },
  {
    id: 220,
    slug: 'decode-string',
    title: 'Giải Mã Chuỗi Nén',
    description: 'Cho chuỗi mã hóa dạng k[encoded_string]. Giải mã bằng cách lặp encoded_string k lần. Có thể lồng nhau. VD: 3[a2[c]] = accaccacc.',
    difficulty: 'medium',
    tags: ['Stack', 'Chuỗi'],
    acceptanceRate: 48,
    xp: 40,
    starterCode: 's = input()\n# Giải mã chuỗi nén\n',
    testCases: [
      { input: '3[a]2[bc]', expectedOutput: 'aaabcbc', isHidden: false },
      { input: '3[a2[c]]', expectedOutput: 'accaccacc', isHidden: false },
      { input: '2[abc]3[cd]ef', expectedOutput: 'abcabccdcdcdef', isHidden: true },
    ],
    hints: ['Dùng 2 stack: một cho số, một cho chuỗi', 'Gặp [ thì push số và chuỗi hiện tại vào stack', 'Gặp ] thì pop và nhân chuỗi hiện tại với số'],
    editorial: {
      approach: 'Stack: dùng stack lưu (số lặp, chuỗi trước đó). Khi gặp ] thì pop và ghép chuỗi.',
      code: 's = input()\nstack = []\ncur_str = ""\ncur_num = 0\nfor c in s:\n    if c.isdigit():\n        cur_num = cur_num * 10 + int(c)\n    elif c == "[":\n        stack.append((cur_str, cur_num))\n        cur_str = ""\n        cur_num = 0\n    elif c == "]":\n        prev_str, num = stack.pop()\n        cur_str = prev_str + cur_str * num\n    else:\n        cur_str += c\nprint(cur_str)',
      complexity: 'Time: O(n * max_k), Space: O(n)',
    },
  },

  // ==================== MEDIUM: ADVANCED SORTING & SEARCHING (221-230) ====================
  {
    id: 221,
    slug: 'search-rotated-sorted-array',
    title: 'Tìm Kiếm Trong Mảng Xoay',
    description: 'Cho mảng n số nguyên phân biệt đã sắp xếp tăng dần rồi bị xoay tại một điểm. Tìm chỉ số của target trong mảng. Nếu không có, in -1. Yêu cầu O(log n).',
    difficulty: 'medium',
    tags: ['Binary Search', 'Mảng'],
    acceptanceRate: 40,
    xp: 45,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# Tìm chỉ số target trong mảng xoay\n',
    testCases: [
      { input: '7\n4 5 6 7 0 1 2\n0', expectedOutput: '4', isHidden: false },
      { input: '7\n4 5 6 7 0 1 2\n3', expectedOutput: '-1', isHidden: false },
      { input: '5\n3 4 5 1 2\n5', expectedOutput: '2', isHidden: true },
      { input: '1\n1\n1', expectedOutput: '0', isHidden: true },
    ],
    hints: ['Dùng binary search, xác định nửa nào đang sắp xếp', 'Nếu nửa trái sắp xếp và target nằm trong đó, tìm bên trái', 'Ngược lại tìm bên phải'],
    editorial: {
      approach: 'Binary Search biến thể: xác định nửa nào sorted, kiểm tra target có nằm trong nửa sorted không để quyết định hướng tìm.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\nleft, right = 0, n - 1\nresult = -1\nwhile left <= right:\n    mid = (left + right) // 2\n    if arr[mid] == target:\n        result = mid\n        break\n    if arr[left] <= arr[mid]:\n        if arr[left] <= target < arr[mid]:\n            right = mid - 1\n        else:\n            left = mid + 1\n    else:\n        if arr[mid] < target <= arr[right]:\n            left = mid + 1\n        else:\n            right = mid - 1\nprint(result)',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 222,
    slug: 'find-first-last-position',
    title: 'Tìm Vị Trí Đầu Và Cuối Của Phần Tử',
    description: 'Cho mảng n số nguyên sắp xếp tăng dần và target. Tìm vị trí xuất hiện đầu tiên và cuối cùng của target. Nếu không có, in "-1 -1". Yêu cầu O(log n).',
    difficulty: 'medium',
    tags: ['Binary Search', 'Mảng'],
    acceptanceRate: 45,
    xp: 40,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# Tìm vị trí đầu và cuối của target\n',
    testCases: [
      { input: '6\n5 7 7 8 8 10\n8', expectedOutput: '3 4', isHidden: false },
      { input: '6\n5 7 7 8 8 10\n6', expectedOutput: '-1 -1', isHidden: false },
      { input: '5\n1 1 1 1 1\n1', expectedOutput: '0 4', isHidden: true },
    ],
    hints: ['Dùng 2 lần binary search: một tìm vị trí đầu, một tìm vị trí cuối', 'Tìm vị trí đầu: khi arr[mid] == target, tiếp tục tìm bên trái', 'Tìm vị trí cuối: khi arr[mid] == target, tiếp tục tìm bên phải'],
    editorial: {
      approach: 'Hai lần Binary Search: lần 1 tìm biên trái (first), lần 2 tìm biên phải (last).',
      code: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\ndef find_left():\n    lo, hi = 0, n - 1\n    res = -1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            res = mid\n            hi = mid - 1\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return res\ndef find_right():\n    lo, hi = 0, n - 1\n    res = -1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            res = mid\n            lo = mid + 1\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return res\nprint(find_left(), find_right())',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 223,
    slug: 'find-peak-element',
    title: 'Tìm Phần Tử Đỉnh',
    description: 'Cho mảng n số nguyên. Phần tử đỉnh là phần tử lớn hơn cả hai phần tử liền kề. Tìm chỉ số của một phần tử đỉnh bất kỳ. Giả sử arr[-1] = arr[n] = -∞. Yêu cầu O(log n).',
    difficulty: 'medium',
    tags: ['Binary Search', 'Mảng'],
    acceptanceRate: 48,
    xp: 35,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm chỉ số phần tử đỉnh\n',
    testCases: [
      { input: '4\n1 2 3 1', expectedOutput: '2', isHidden: false },
      { input: '5\n1 2 1 3 5', expectedOutput: '4', isHidden: false },
      { input: '1\n1', expectedOutput: '0', isHidden: true },
    ],
    hints: ['Dùng binary search: so sánh mid với mid+1', 'Nếu arr[mid] < arr[mid+1], đỉnh nằm bên phải', 'Nếu arr[mid] > arr[mid+1], đỉnh nằm bên trái (hoặc chính mid)'],
    editorial: {
      approach: 'Binary Search: nếu arr[mid] < arr[mid+1] thì đỉnh ở bên phải, ngược lại ở bên trái.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nleft, right = 0, n - 1\nwhile left < right:\n    mid = (left + right) // 2\n    if arr[mid] < arr[mid + 1]:\n        left = mid + 1\n    else:\n        right = mid\nprint(left)',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 224,
    slug: 'kth-smallest-sorted-matrix',
    title: 'Phần Tử Nhỏ Thứ K Trong Ma Trận Sắp Xếp',
    description: 'Cho ma trận n×n trong đó mỗi hàng và mỗi cột đều sắp xếp tăng dần. Tìm phần tử nhỏ thứ K trong ma trận.',
    difficulty: 'medium',
    tags: ['Binary Search', 'Ma trận'],
    acceptanceRate: 42,
    xp: 45,
    starterCode: 'n, k = map(int, input().split())\nmatrix = []\nfor _ in range(n):\n    matrix.append(list(map(int, input().split())))\n# Tìm phần tử nhỏ thứ k\n',
    testCases: [
      { input: '3 8\n1 5 9\n10 11 13\n12 13 15', expectedOutput: '13', isHidden: false },
      { input: '2 3\n1 2\n3 4', expectedOutput: '3', isHidden: false },
      { input: '1 1\n5', expectedOutput: '5', isHidden: true },
    ],
    hints: ['Binary search trên giá trị: tìm giá trị nhỏ nhất x sao cho có ít nhất k phần tử <= x', 'Đếm số phần tử <= mid bằng cách duyệt từ góc trái dưới', 'Kết quả là giá trị nhỏ nhất thỏa mãn điều kiện'],
    editorial: {
      approach: 'Binary Search trên giá trị: tìm giá trị x nhỏ nhất sao cho count(<=x) >= k.',
      code: 'n, k = map(int, input().split())\nmatrix = []\nfor _ in range(n):\n    matrix.append(list(map(int, input().split())))\ndef count_leq(mid):\n    count = 0\n    row, col = n - 1, 0\n    while row >= 0 and col < n:\n        if matrix[row][col] <= mid:\n            count += row + 1\n            col += 1\n        else:\n            row -= 1\n    return count\nlo, hi = matrix[0][0], matrix[n-1][n-1]\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if count_leq(mid) < k:\n        lo = mid + 1\n    else:\n        hi = mid\nprint(lo)',
      complexity: 'Time: O(n * log(max-min)), Space: O(1)',
    },
  },
  {
    id: 225,
    slug: 'merge-sort-count-inversions',
    title: 'Đếm Số Nghịch Thế (Merge Sort)',
    description: 'Cho mảng n số nguyên. Đếm số cặp (i, j) với i < j mà arr[i] > arr[j]. Đây gọi là số nghịch thế của mảng.',
    difficulty: 'medium',
    tags: ['Sorting', 'Divide and Conquer'],
    acceptanceRate: 38,
    xp: 50,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Đếm số nghịch thế\n',
    testCases: [
      { input: '5\n2 4 1 3 5', expectedOutput: '3', isHidden: false },
      { input: '4\n4 3 2 1', expectedOutput: '6', isHidden: false },
      { input: '3\n1 2 3', expectedOutput: '0', isHidden: true },
    ],
    hints: ['Dùng merge sort biến thể để đếm', 'Khi merge, nếu phần tử bên phải nhỏ hơn bên trái, đếm inversions', 'Số inversions = mid - left_pointer + 1 mỗi lần'],
    editorial: {
      approach: 'Merge Sort biến thể: trong bước merge, đếm số phần tử bên trái lớn hơn phần tử bên phải.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\ndef merge_count(arr):\n    if len(arr) <= 1:\n        return arr, 0\n    mid = len(arr) // 2\n    left, l_inv = merge_count(arr[:mid])\n    right, r_inv = merge_count(arr[mid:])\n    merged = []\n    inversions = l_inv + r_inv\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            merged.append(left[i])\n            i += 1\n        else:\n            merged.append(right[j])\n            inversions += len(left) - i\n            j += 1\n    merged.extend(left[i:])\n    merged.extend(right[j:])\n    return merged, inversions\n_, result = merge_count(arr)\nprint(result)',
      complexity: 'Time: O(n log n), Space: O(n)',
    },
  },
  {
    id: 226,
    slug: 'find-minimum-rotated-array',
    title: 'Tìm Giá Trị Nhỏ Nhất Trong Mảng Xoay',
    description: 'Cho mảng n số nguyên phân biệt đã sắp xếp tăng dần rồi bị xoay. Tìm giá trị nhỏ nhất. Yêu cầu O(log n).',
    difficulty: 'medium',
    tags: ['Binary Search', 'Mảng'],
    acceptanceRate: 52,
    xp: 35,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm giá trị nhỏ nhất trong mảng xoay\n',
    testCases: [
      { input: '5\n3 4 5 1 2', expectedOutput: '1', isHidden: false },
      { input: '7\n4 5 6 7 0 1 2', expectedOutput: '0', isHidden: false },
      { input: '3\n1 2 3', expectedOutput: '1', isHidden: true },
    ],
    hints: ['Dùng binary search, so sánh mid với right', 'Nếu arr[mid] > arr[right], min nằm bên phải', 'Nếu arr[mid] < arr[right], min nằm bên trái (hoặc chính mid)'],
    editorial: {
      approach: 'Binary Search: so sánh arr[mid] với arr[right] để xác định nửa chứa điểm xoay.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nleft, right = 0, n - 1\nwhile left < right:\n    mid = (left + right) // 2\n    if arr[mid] > arr[right]:\n        left = mid + 1\n    else:\n        right = mid\nprint(arr[left])',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 227,
    slug: 'search-2d-matrix',
    title: 'Tìm Kiếm Trong Ma Trận 2D',
    description: 'Cho ma trận m×n trong đó mỗi hàng sắp xếp tăng dần và phần tử đầu mỗi hàng lớn hơn phần tử cuối hàng trước. Kiểm tra target có trong ma trận không. In "YES" hoặc "NO".',
    difficulty: 'medium',
    tags: ['Binary Search', 'Ma trận'],
    acceptanceRate: 55,
    xp: 30,
    starterCode: 'm, n = map(int, input().split())\nmatrix = []\nfor _ in range(m):\n    matrix.append(list(map(int, input().split())))\ntarget = int(input())\n# Tìm target trong ma trận\n',
    testCases: [
      { input: '3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n3', expectedOutput: 'YES', isHidden: false },
      { input: '3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n13', expectedOutput: 'NO', isHidden: false },
      { input: '1 1\n5\n5', expectedOutput: 'YES', isHidden: true },
    ],
    hints: ['Coi ma trận như mảng 1D sắp xếp', 'Chỉ số 1D k tương ứng hàng k//n, cột k%n', 'Dùng binary search trên mảng 1D ảo'],
    editorial: {
      approach: 'Binary Search: coi ma trận m×n như mảng 1D có m*n phần tử, áp dụng binary search.',
      code: 'm, n = map(int, input().split())\nmatrix = []\nfor _ in range(m):\n    matrix.append(list(map(int, input().split())))\ntarget = int(input())\nleft, right = 0, m * n - 1\nfound = False\nwhile left <= right:\n    mid = (left + right) // 2\n    val = matrix[mid // n][mid % n]\n    if val == target:\n        found = True\n        break\n    elif val < target:\n        left = mid + 1\n    else:\n        right = mid - 1\nprint("YES" if found else "NO")',
      complexity: 'Time: O(log(m*n)), Space: O(1)',
    },
  },
  {
    id: 228,
    slug: 'median-two-sorted-arrays',
    title: 'Trung Vị Hai Mảng Sắp Xếp',
    description: 'Cho hai mảng đã sắp xếp tăng dần có kích thước m và n. Tìm trung vị của mảng hợp nhất. In kết quả với 1 chữ số thập phân.',
    difficulty: 'medium',
    tags: ['Binary Search', 'Mảng'],
    acceptanceRate: 35,
    xp: 50,
    starterCode: 'm = int(input())\narr1 = list(map(int, input().split()))\nn = int(input())\narr2 = list(map(int, input().split()))\n# Tìm trung vị hai mảng\n',
    testCases: [
      { input: '2\n1 3\n1\n2', expectedOutput: '2.0', isHidden: false },
      { input: '2\n1 2\n2\n3 4', expectedOutput: '2.5', isHidden: false },
      { input: '1\n1\n1\n1', expectedOutput: '1.0', isHidden: true },
    ],
    hints: ['Merge hai mảng rồi tìm trung vị (cách đơn giản O(m+n))', 'Cách tối ưu: binary search trên mảng ngắn hơn', 'Tìm partition sao cho max(left) <= min(right)'],
    editorial: {
      approach: 'Merge đơn giản: hợp nhất hai mảng rồi lấy trung vị. (Cách tối ưu dùng binary search O(log(min(m,n))))',
      code: 'm = int(input())\narr1 = list(map(int, input().split()))\nn = int(input())\narr2 = list(map(int, input().split()))\nmerged = []\ni = j = 0\nwhile i < m and j < n:\n    if arr1[i] <= arr2[j]:\n        merged.append(arr1[i])\n        i += 1\n    else:\n        merged.append(arr2[j])\n        j += 1\nmerged.extend(arr1[i:])\nmerged.extend(arr2[j:])\ntotal = m + n\nif total % 2 == 1:\n    print(f"{merged[total // 2]:.1f}")\nelse:\n    print(f"{(merged[total // 2 - 1] + merged[total // 2]) / 2:.1f}")',
      complexity: 'Time: O(m+n), Space: O(m+n)',
    },
  },
  {
    id: 229,
    slug: 'sort-colors-dutch-flag',
    title: 'Sắp Xếp 3 Màu (Dutch National Flag)',
    description: 'Cho mảng n phần tử chỉ gồm 0, 1, 2. Sắp xếp mảng tại chỗ sao cho các 0 đứng trước, rồi đến 1, rồi đến 2. Chỉ duyệt mảng 1 lần.',
    difficulty: 'medium',
    tags: ['Sorting', 'Mảng', 'Two Pointers'],
    acceptanceRate: 52,
    xp: 35,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Sắp xếp mảng 3 màu tại chỗ\n',
    testCases: [
      { input: '6\n2 0 2 1 1 0', expectedOutput: '0 0 1 1 2 2', isHidden: false },
      { input: '3\n2 0 1', expectedOutput: '0 1 2', isHidden: false },
      { input: '5\n0 0 0 0 0', expectedOutput: '0 0 0 0 0', isHidden: true },
    ],
    hints: ['Dùng 3 con trỏ: low, mid, high', 'low: biên phải của vùng 0, high: biên trái của vùng 2', 'mid duyệt: gặp 0 swap với low, gặp 2 swap với high'],
    editorial: {
      approach: 'Dutch National Flag: 3 con trỏ phân vùng mảng thành [0..low-1]=0, [low..mid-1]=1, [high+1..n-1]=2.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nlow = mid = 0\nhigh = n - 1\nwhile mid <= high:\n    if arr[mid] == 0:\n        arr[low], arr[mid] = arr[mid], arr[low]\n        low += 1\n        mid += 1\n    elif arr[mid] == 1:\n        mid += 1\n    else:\n        arr[mid], arr[high] = arr[high], arr[mid]\n        high -= 1\nprint(*arr)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 230,
    slug: 'kth-largest-element',
    title: 'Phần Tử Lớn Thứ K',
    description: 'Cho mảng n số nguyên và số K. Tìm phần tử lớn thứ K trong mảng (không cần sắp xếp toàn bộ). K=1 là phần tử lớn nhất.',
    difficulty: 'medium',
    tags: ['Sorting', 'Mảng', 'Heap'],
    acceptanceRate: 50,
    xp: 35,
    starterCode: 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# Tìm phần tử lớn thứ k\n',
    testCases: [
      { input: '6 2\n3 2 1 5 6 4', expectedOutput: '5', isHidden: false },
      { input: '9 4\n3 2 3 1 2 4 5 5 6', expectedOutput: '4', isHidden: false },
      { input: '1 1\n1', expectedOutput: '1', isHidden: true },
    ],
    hints: ['Cách đơn giản: sắp xếp giảm dần, lấy phần tử thứ k-1', 'Cách tối ưu: dùng min-heap kích thước k', 'Hoặc dùng QuickSelect (trung bình O(n))'],
    editorial: {
      approach: 'Min-Heap kích thước K: duy trì heap k phần tử lớn nhất, đỉnh heap là phần tử lớn thứ K.',
      code: 'import heapq\nn, k = map(int, input().split())\narr = list(map(int, input().split()))\nheap = []\nfor num in arr:\n    heapq.heappush(heap, num)\n    if len(heap) > k:\n        heapq.heappop(heap)\nprint(heap[0])',
      complexity: 'Time: O(n log k), Space: O(k)',
    },
  },

  // ==================== HARD: DYNAMIC PROGRAMMING (231-240) ====================
  {
    id: 231,
    slug: 'longest-palindromic-subsequence',
    title: 'Dãy Con Palindrome Dài Nhất',
    description: 'Cho chuỗi s gồm chữ cái thường. Tìm độ dài dãy con (subsequence) dài nhất tạo thành palindrome. Dãy con không cần liên tiếp.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 38,
    xp: 70,
    starterCode: 's = input()\n# Tìm độ dài dãy con palindrome dài nhất\n',
    testCases: [
      { input: 'bbbab', expectedOutput: '4', isHidden: false },
      { input: 'cbbd', expectedOutput: '2', isHidden: false },
      { input: 'abcba', expectedOutput: '5', isHidden: true },
      { input: 'a', expectedOutput: '1', isHidden: true },
    ],
    hints: ['Đây là bài LCS của s và reverse(s)', 'dp[i][j] = độ dài dãy con palindrome dài nhất của s[i..j]', 'Nếu s[i]==s[j]: dp[i][j] = dp[i+1][j-1] + 2'],
    editorial: {
      approach: 'DP 2D: dp[i][j] là độ dài dãy con palindrome dài nhất trong s[i..j]. Duyệt theo độ dài tăng dần.',
      code: 's = input()\nn = len(s)\ndp = [[0] * n for _ in range(n)]\nfor i in range(n):\n    dp[i][i] = 1\nfor length in range(2, n + 1):\n    for i in range(n - length + 1):\n        j = i + length - 1\n        if s[i] == s[j]:\n            dp[i][j] = dp[i+1][j-1] + 2\n        else:\n            dp[i][j] = max(dp[i+1][j], dp[i][j-1])\nprint(dp[0][n-1])',
      complexity: 'Time: O(n²), Space: O(n²)',
    },
  },
  {
    id: 232,
    slug: 'word-break',
    title: 'Tách Từ (Word Break)',
    description: 'Cho chuỗi s và danh sách từ điển wordDict. Kiểm tra xem s có thể được tách thành các từ trong wordDict hay không. Mỗi từ có thể dùng nhiều lần. In "YES" hoặc "NO".',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 35,
    xp: 75,
    starterCode: 's = input()\nn = int(input())\nwords = input().split()\n# Kiểm tra s có thể tách thành các từ trong wordDict\n',
    testCases: [
      { input: 'leetcode\n2\nleet code', expectedOutput: 'YES', isHidden: false },
      { input: 'applepenapple\n2\napple pen', expectedOutput: 'YES', isHidden: false },
      { input: 'catsandog\n4\ncats dog sand and', expectedOutput: 'NO', isHidden: true },
      { input: 'aaaaaaa\n2\naaa aaaa', expectedOutput: 'YES', isHidden: true },
    ],
    hints: ['dp[i] = True nếu s[0:i] có thể tách được', 'dp[i] = True nếu tồn tại j < i sao cho dp[j] = True và s[j:i] trong wordDict', 'Dùng set cho wordDict để tra cứu O(1)'],
    editorial: {
      approach: 'DP 1D: dp[i] cho biết s[0:i] có tách được không. Với mỗi i, thử tất cả j < i.',
      code: 's = input()\nn = int(input())\nwords = set(input().split())\nm = len(s)\ndp = [False] * (m + 1)\ndp[0] = True\nfor i in range(1, m + 1):\n    for j in range(i):\n        if dp[j] and s[j:i] in words:\n            dp[i] = True\n            break\nprint("YES" if dp[m] else "NO")',
      complexity: 'Time: O(n² * m), Space: O(n)',
    },
  },
  {
    id: 233,
    slug: 'decode-ways',
    title: 'Số Cách Giải Mã',
    description: 'Cho chuỗi chữ số s. Mỗi chữ cái A-Z được mã hóa 1-26. Đếm số cách giải mã chuỗi s thành chữ cái. VD: "12" có thể là "AB" (1,2) hoặc "L" (12).',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 32,
    xp: 75,
    starterCode: 's = input()\n# Đếm số cách giải mã chuỗi số\n',
    testCases: [
      { input: '12', expectedOutput: '2', isHidden: false },
      { input: '226', expectedOutput: '3', isHidden: false },
      { input: '06', expectedOutput: '0', isHidden: true },
      { input: '11106', expectedOutput: '2', isHidden: true },
    ],
    hints: ['dp[i] = số cách giải mã s[0:i]', 'Nếu s[i-1] != "0": dp[i] += dp[i-1] (giải mã 1 chữ số)', 'Nếu s[i-2:i] trong 10-26: dp[i] += dp[i-2] (giải mã 2 chữ số)'],
    editorial: {
      approach: 'DP 1D: dp[i] = số cách giải mã i ký tự đầu. Xét giải mã 1 chữ số và 2 chữ số.',
      code: 's = input()\nn = len(s)\nif n == 0 or s[0] == "0":\n    print(0)\nelse:\n    dp = [0] * (n + 1)\n    dp[0] = 1\n    dp[1] = 1\n    for i in range(2, n + 1):\n        one = int(s[i-1:i])\n        two = int(s[i-2:i])\n        if 1 <= one <= 9:\n            dp[i] += dp[i-1]\n        if 10 <= two <= 26:\n            dp[i] += dp[i-2]\n    print(dp[n])',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 234,
    slug: 'unique-paths',
    title: 'Số Đường Đi Duy Nhất',
    description: 'Cho lưới m×n. Robot bắt đầu từ góc trái trên (0,0) và muốn đến góc phải dưới (m-1,n-1). Mỗi bước chỉ đi xuống hoặc sang phải. Đếm số đường đi khác nhau.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Ma trận'],
    acceptanceRate: 45,
    xp: 60,
    starterCode: 'm, n = map(int, input().split())\n# Đếm số đường đi từ (0,0) đến (m-1,n-1)\n',
    testCases: [
      { input: '3 7', expectedOutput: '28', isHidden: false },
      { input: '3 2', expectedOutput: '3', isHidden: false },
      { input: '1 1', expectedOutput: '1', isHidden: true },
      { input: '7 3', expectedOutput: '28', isHidden: true },
    ],
    hints: ['dp[i][j] = số đường đi đến ô (i,j)', 'dp[i][j] = dp[i-1][j] + dp[i][j-1]', 'Hàng đầu và cột đầu đều = 1'],
    editorial: {
      approach: 'DP 2D: dp[i][j] = dp[i-1][j] + dp[i][j-1]. Có thể tối ưu space thành O(n).',
      code: 'm, n = map(int, input().split())\ndp = [[1] * n for _ in range(m)]\nfor i in range(1, m):\n    for j in range(1, n):\n        dp[i][j] = dp[i-1][j] + dp[i][j-1]\nprint(dp[m-1][n-1])',
      complexity: 'Time: O(m*n), Space: O(m*n)',
    },
  },
  {
    id: 235,
    slug: 'min-path-sum',
    title: 'Đường Đi Tổng Nhỏ Nhất',
    description: 'Cho lưới m×n chứa số không âm. Tìm đường đi từ góc trái trên đến góc phải dưới sao cho tổng các số trên đường đi là nhỏ nhất. Chỉ đi xuống hoặc sang phải.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Ma trận'],
    acceptanceRate: 42,
    xp: 65,
    starterCode: 'm, n = map(int, input().split())\ngrid = []\nfor _ in range(m):\n    grid.append(list(map(int, input().split())))\n# Tìm đường đi tổng nhỏ nhất\n',
    testCases: [
      { input: '3 3\n1 3 1\n1 5 1\n4 2 1', expectedOutput: '7', isHidden: false },
      { input: '2 3\n1 2 3\n4 5 6', expectedOutput: '12', isHidden: false },
      { input: '1 1\n0', expectedOutput: '0', isHidden: true },
    ],
    hints: ['dp[i][j] = tổng nhỏ nhất để đến ô (i,j)', 'dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])', 'Xử lý riêng hàng đầu và cột đầu'],
    editorial: {
      approach: 'DP 2D: dp[i][j] = chi phí nhỏ nhất đến (i,j) = grid[i][j] + min(trên, trái).',
      code: 'm, n = map(int, input().split())\ngrid = []\nfor _ in range(m):\n    grid.append(list(map(int, input().split())))\ndp = [[0]*n for _ in range(m)]\ndp[0][0] = grid[0][0]\nfor j in range(1, n):\n    dp[0][j] = dp[0][j-1] + grid[0][j]\nfor i in range(1, m):\n    dp[i][0] = dp[i-1][0] + grid[i][0]\nfor i in range(1, m):\n    for j in range(1, n):\n        dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1])\nprint(dp[m-1][n-1])',
      complexity: 'Time: O(m*n), Space: O(m*n)',
    },
  },
  {
    id: 236,
    slug: 'coin-change-min',
    title: 'Đổi Tiền - Số Đồng Xu Ít Nhất',
    description: 'Cho mảng coins chứa mệnh giá các đồng xu và số tiền amount. Tìm số đồng xu ít nhất để tạo thành amount. Nếu không thể, in -1. Mỗi loại xu dùng không giới hạn.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Toán'],
    acceptanceRate: 38,
    xp: 70,
    starterCode: 'n = int(input())\ncoins = list(map(int, input().split()))\namount = int(input())\n# Tìm số đồng xu ít nhất\n',
    testCases: [
      { input: '3\n1 5 11\n15', expectedOutput: '3', isHidden: false },
      { input: '3\n2 5 10\n3', expectedOutput: '-1', isHidden: false },
      { input: '1\n1\n0', expectedOutput: '0', isHidden: true },
      { input: '2\n1 2\n10', expectedOutput: '5', isHidden: true },
    ],
    hints: ['dp[i] = số xu ít nhất để tạo số tiền i', 'dp[i] = min(dp[i - coin] + 1) với mọi coin <= i', 'Khởi tạo dp[0] = 0, dp[i] = infinity'],
    editorial: {
      approach: 'DP 1D: dp[i] = số xu ít nhất cho số tiền i. Duyệt mỗi mệnh giá cho mỗi giá trị.',
      code: 'n = int(input())\ncoins = list(map(int, input().split()))\namount = int(input())\ndp = [float("inf")] * (amount + 1)\ndp[0] = 0\nfor i in range(1, amount + 1):\n    for coin in coins:\n        if coin <= i and dp[i - coin] + 1 < dp[i]:\n            dp[i] = dp[i - coin] + 1\nprint(dp[amount] if dp[amount] != float("inf") else -1)',
      complexity: 'Time: O(amount * n), Space: O(amount)',
    },
  },
  {
    id: 237,
    slug: 'longest-increasing-subsequence',
    title: 'Dãy Con Tăng Dài Nhất (LIS)',
    description: 'Cho mảng n số nguyên. Tìm độ dài dãy con tăng nghiêm ngặt dài nhất (không cần liên tiếp).',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Binary Search'],
    acceptanceRate: 40,
    xp: 70,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm độ dài LIS\n',
    testCases: [
      { input: '8\n10 9 2 5 3 7 101 18', expectedOutput: '4', isHidden: false },
      { input: '6\n0 1 0 3 2 3', expectedOutput: '4', isHidden: false },
      { input: '5\n5 4 3 2 1', expectedOutput: '1', isHidden: true },
    ],
    hints: ['DP O(n²): dp[i] = LIS kết thúc tại i', 'Tối ưu O(n log n): dùng mảng tails + binary search', 'tails[i] = giá trị nhỏ nhất kết thúc LIS độ dài i+1'],
    editorial: {
      approach: 'DP + Binary Search: duy trì mảng tails, dùng bisect để tìm vị trí chèn.',
      code: 'import bisect\nn = int(input())\narr = list(map(int, input().split()))\ntails = []\nfor num in arr:\n    pos = bisect.bisect_left(tails, num)\n    if pos == len(tails):\n        tails.append(num)\n    else:\n        tails[pos] = num\nprint(len(tails))',
      complexity: 'Time: O(n log n), Space: O(n)',
    },
  },
  {
    id: 238,
    slug: 'edit-distance',
    title: 'Khoảng Cách Chỉnh Sửa',
    description: 'Cho hai chuỗi word1 và word2. Tìm số thao tác ít nhất (chèn, xóa, thay thế) để biến word1 thành word2.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 35,
    xp: 80,
    starterCode: 'word1 = input()\nword2 = input()\n# Tìm khoảng cách chỉnh sửa\n',
    testCases: [
      { input: 'horse\nros', expectedOutput: '3', isHidden: false },
      { input: 'intention\nexecution', expectedOutput: '5', isHidden: false },
      { input: 'abc\nabc', expectedOutput: '0', isHidden: true },
      { input: '\nabc', expectedOutput: '3', isHidden: true },
    ],
    hints: ['dp[i][j] = edit distance giữa word1[0:i] và word2[0:j]', 'Nếu word1[i-1] == word2[j-1]: dp[i][j] = dp[i-1][j-1]', 'Ngược lại: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])'],
    editorial: {
      approach: 'DP 2D: dp[i][j] = số thao tác tối thiểu biến word1[0:i] thành word2[0:j].',
      code: 'word1 = input()\nword2 = input()\nm, n = len(word1), len(word2)\ndp = [[0] * (n + 1) for _ in range(m + 1)]\nfor i in range(m + 1):\n    dp[i][0] = i\nfor j in range(n + 1):\n    dp[0][j] = j\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if word1[i-1] == word2[j-1]:\n            dp[i][j] = dp[i-1][j-1]\n        else:\n            dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\nprint(dp[m][n])',
      complexity: 'Time: O(m*n), Space: O(m*n)',
    },
  },
  {
    id: 239,
    slug: 'knapsack-01',
    title: 'Bài Toán Cái Túi 0/1',
    description: 'Cho n vật phẩm, mỗi vật có trọng lượng w[i] và giá trị v[i]. Túi chứa tối đa W trọng lượng. Tìm giá trị lớn nhất có thể mang (mỗi vật chọn hoặc không chọn).',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Thuật toán'],
    acceptanceRate: 40,
    xp: 70,
    starterCode: 'n, W = map(int, input().split())\nitems = []\nfor _ in range(n):\n    w, v = map(int, input().split())\n    items.append((w, v))\n# Tìm giá trị lớn nhất\n',
    testCases: [
      { input: '4 7\n1 1\n3 4\n4 5\n5 7', expectedOutput: '9', isHidden: false },
      { input: '3 50\n10 60\n20 100\n30 120', expectedOutput: '220', isHidden: false },
      { input: '2 3\n5 10\n6 20', expectedOutput: '0', isHidden: true },
    ],
    hints: ['dp[i][w] = giá trị max dùng i vật đầu với sức chứa w', 'Với mỗi vật: chọn hoặc không chọn', 'dp[i][w] = max(dp[i-1][w], dp[i-1][w-wi] + vi)'],
    editorial: {
      approach: 'DP 2D (tối ưu 1D): dp[w] = giá trị max với sức chứa w. Duyệt ngược w để tránh dùng lại vật.',
      code: 'n, W = map(int, input().split())\nitems = []\nfor _ in range(n):\n    w, v = map(int, input().split())\n    items.append((w, v))\ndp = [0] * (W + 1)\nfor w, v in items:\n    for j in range(W, w - 1, -1):\n        dp[j] = max(dp[j], dp[j - w] + v)\nprint(dp[W])',
      complexity: 'Time: O(n*W), Space: O(W)',
    },
  },
  {
    id: 240,
    slug: 'longest-common-subsequence',
    title: 'Dãy Con Chung Dài Nhất (LCS)',
    description: 'Cho hai chuỗi text1 và text2. Tìm độ dài dãy con chung dài nhất của hai chuỗi. Dãy con không cần liên tiếp nhưng giữ nguyên thứ tự.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 42,
    xp: 65,
    starterCode: 'text1 = input()\ntext2 = input()\n# Tìm độ dài LCS\n',
    testCases: [
      { input: 'abcde\nace', expectedOutput: '3', isHidden: false },
      { input: 'abc\nabc', expectedOutput: '3', isHidden: false },
      { input: 'abc\ndef', expectedOutput: '0', isHidden: true },
    ],
    hints: ['dp[i][j] = LCS của text1[0:i] và text2[0:j]', 'Nếu text1[i-1] == text2[j-1]: dp[i][j] = dp[i-1][j-1] + 1', 'Ngược lại: dp[i][j] = max(dp[i-1][j], dp[i][j-1])'],
    editorial: {
      approach: 'DP 2D: so sánh từng cặp ký tự, nếu giống thì +1 từ dp[i-1][j-1], ngược lại lấy max.',
      code: 'text1 = input()\ntext2 = input()\nm, n = len(text1), len(text2)\ndp = [[0] * (n + 1) for _ in range(m + 1)]\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if text1[i-1] == text2[j-1]:\n            dp[i][j] = dp[i-1][j-1] + 1\n        else:\n            dp[i][j] = max(dp[i-1][j], dp[i][j-1])\nprint(dp[m][n])',
      complexity: 'Time: O(m*n), Space: O(m*n)',
    },
  },

  // ==================== HARD: BACKTRACKING & GRAPH (241-250) ====================
  {
    id: 241,
    slug: 'combination-sum',
    title: 'Tổ Hợp Tổng Bằng Target',
    description: 'Cho mảng n số nguyên dương phân biệt và target. Tìm tất cả tổ hợp có tổng bằng target. Mỗi số có thể dùng nhiều lần. In mỗi tổ hợp trên 1 dòng (sắp xếp tăng dần).',
    difficulty: 'hard',
    tags: ['Quay lui', 'Mảng'],
    acceptanceRate: 42,
    xp: 65,
    starterCode: 'n = int(input())\ncandidates = list(map(int, input().split()))\ntarget = int(input())\n# Tìm tất cả tổ hợp có tổng bằng target\n',
    testCases: [
      { input: '4\n2 3 6 7\n7', expectedOutput: '2 2 3\n7', isHidden: false },
      { input: '3\n2 3 5\n8', expectedOutput: '2 2 2 2\n2 3 3\n3 5', isHidden: false },
      { input: '1\n1\n3', expectedOutput: '1 1 1', isHidden: true },
    ],
    hints: ['Dùng backtracking với chỉ số bắt đầu để tránh trùng lặp', 'Sắp xếp mảng trước để dễ cắt nhánh', 'Khi tổng hiện tại > target, dừng sớm'],
    editorial: {
      approach: 'Backtracking: sắp xếp mảng, duyệt từ chỉ số hiện tại (cho phép lặp), cắt nhánh khi tổng vượt target.',
      code: 'n = int(input())\ncandidates = sorted(list(map(int, input().split())))\ntarget = int(input())\nresults = []\ndef backtrack(start, path, remaining):\n    if remaining == 0:\n        results.append(list(path))\n        return\n    for i in range(start, n):\n        if candidates[i] > remaining:\n            break\n        path.append(candidates[i])\n        backtrack(i, path, remaining - candidates[i])\n        path.pop()\nbacktrack(0, [], target)\nfor r in results:\n    print(*r)',
      complexity: 'Time: O(n^(target/min)), Space: O(target/min)',
    },
  },
  {
    id: 242,
    slug: 'generate-parentheses',
    title: 'Sinh Tất Cả Ngoặc Hợp Lệ',
    description: 'Cho số n. Sinh tất cả chuỗi ngoặc đơn hợp lệ có đúng n cặp ngoặc. In mỗi chuỗi trên 1 dòng theo thứ tự từ điển.',
    difficulty: 'hard',
    tags: ['Quay lui', 'Chuỗi'],
    acceptanceRate: 45,
    xp: 60,
    starterCode: 'n = int(input())\n# Sinh tất cả chuỗi ngoặc hợp lệ n cặp\n',
    testCases: [
      { input: '2', expectedOutput: '(())\n()()', isHidden: false },
      { input: '3', expectedOutput: '((()))\n(()())\n(())()\n()(())\n()()()', isHidden: false },
      { input: '1', expectedOutput: '()', isHidden: true },
    ],
    hints: ['Dùng backtracking với 2 biến: open_count và close_count', 'Thêm ( khi open_count < n', 'Thêm ) khi close_count < open_count'],
    editorial: {
      approach: 'Backtracking: theo dõi số ngoặc mở/đóng đã dùng, chỉ thêm khi hợp lệ.',
      code: 'n = int(input())\nresults = []\ndef backtrack(s, open_c, close_c):\n    if len(s) == 2 * n:\n        results.append(s)\n        return\n    if open_c < n:\n        backtrack(s + "(", open_c + 1, close_c)\n    if close_c < open_c:\n        backtrack(s + ")", open_c, close_c + 1)\nbacktrack("", 0, 0)\nfor r in results:\n    print(r)',
      complexity: 'Time: O(4^n / sqrt(n)), Space: O(n)',
    },
  },
  {
    id: 243,
    slug: 'sudoku-validator',
    title: 'Kiểm Tra Sudoku Hợp Lệ',
    description: 'Cho bảng Sudoku 9x9 (0 đại diện ô trống). Kiểm tra xem các số đã điền có hợp lệ không (không trùng trong hàng, cột, và ô 3x3). In "YES" hoặc "NO".',
    difficulty: 'hard',
    tags: ['Ma trận', 'Hash Set'],
    acceptanceRate: 44,
    xp: 60,
    starterCode: 'board = []\nfor _ in range(9):\n    board.append(list(map(int, input().split())))\n# Kiểm tra sudoku hợp lệ\n',
    testCases: [
      { input: '5 3 0 0 7 0 0 0 0\n6 0 0 1 9 5 0 0 0\n0 9 8 0 0 0 0 6 0\n8 0 0 0 6 0 0 0 3\n4 0 0 8 0 3 0 0 1\n7 0 0 0 2 0 0 0 6\n0 6 0 0 0 0 2 8 0\n0 0 0 4 1 9 0 0 5\n0 0 0 0 8 0 0 7 9', expectedOutput: 'YES', isHidden: false },
      { input: '5 3 0 0 7 0 0 0 0\n6 0 0 1 9 5 0 0 0\n0 9 8 0 0 0 0 6 0\n8 0 0 0 6 0 0 0 3\n4 0 0 8 0 3 0 0 1\n7 0 0 0 2 0 0 0 6\n0 6 0 0 0 0 2 8 0\n0 0 0 4 1 9 0 0 5\n0 0 0 0 8 0 0 7 5', expectedOutput: 'NO', isHidden: false },
      { input: '0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0\n0 0 0 0 0 0 0 0 0', expectedOutput: 'YES', isHidden: true },
    ],
    hints: ['Kiểm tra từng hàng, từng cột, từng ô 3x3', 'Dùng set để phát hiện trùng lặp', 'Bỏ qua ô trống (giá trị 0)'],
    editorial: {
      approach: 'Dùng set kiểm tra trùng lặp cho mỗi hàng, cột, và ô 3x3.',
      code: 'board = []\nfor _ in range(9):\n    board.append(list(map(int, input().split())))\ndef is_valid():\n    for i in range(9):\n        row_set = set()\n        col_set = set()\n        for j in range(9):\n            if board[i][j] != 0:\n                if board[i][j] in row_set:\n                    return False\n                row_set.add(board[i][j])\n            if board[j][i] != 0:\n                if board[j][i] in col_set:\n                    return False\n                col_set.add(board[j][i])\n    for br in range(3):\n        for bc in range(3):\n            box_set = set()\n            for i in range(3):\n                for j in range(3):\n                    val = board[br*3+i][bc*3+j]\n                    if val != 0:\n                        if val in box_set:\n                            return False\n                        box_set.add(val)\n    return True\nprint("YES" if is_valid() else "NO")',
      complexity: 'Time: O(1) (bảng cố định 9x9), Space: O(1)',
    },
  },

  {
    id: 244,
    slug: 'word-ladder-simplified',
    title: 'Biến Đổi Từ (Word Ladder)',
    description: 'Cho từ beginWord, endWord và danh sách từ wordList. Mỗi bước đổi đúng 1 ký tự để tạo từ mới trong wordList. Tìm số bước ít nhất từ beginWord đến endWord. Nếu không thể, in 0.',
    difficulty: 'hard',
    tags: ['BFS', 'Đồ thị', 'Chuỗi'],
    acceptanceRate: 30,
    xp: 85,
    starterCode: 'begin_word = input()\nend_word = input()\nn = int(input())\nword_list = input().split()\n# Tìm số bước ít nhất biến đổi từ\n',
    testCases: [
      { input: 'hit\ncog\n6\nhot dot dog lot log cog', expectedOutput: '5', isHidden: false },
      { input: 'hit\ncog\n5\nhot dot dog lot log', expectedOutput: '0', isHidden: false },
      { input: 'a\nc\n2\na c', expectedOutput: '2', isHidden: true },
    ],
    hints: ['Dùng BFS: mỗi từ là một node, hai từ kề nhau nếu khác đúng 1 ký tự', 'Bắt đầu BFS từ beginWord', 'Dùng set để đánh dấu từ đã thăm'],
    editorial: {
      approach: 'BFS: bắt đầu từ beginWord, mỗi bước thử thay từng ký tự bằng a-z, kiểm tra có trong wordList không.',
      code: 'from collections import deque\nbegin_word = input()\nend_word = input()\nn = int(input())\nword_list = set(input().split())\nif end_word not in word_list:\n    print(0)\nelse:\n    queue = deque([(begin_word, 1)])\n    visited = {begin_word}\n    found = False\n    while queue:\n        word, steps = queue.popleft()\n        if word == end_word:\n            print(steps)\n            found = True\n            break\n        for i in range(len(word)):\n            for c in "abcdefghijklmnopqrstuvwxyz":\n                new_word = word[:i] + c + word[i+1:]\n                if new_word in word_list and new_word not in visited:\n                    visited.add(new_word)\n                    queue.append((new_word, steps + 1))\n    if not found:\n        print(0)',
      complexity: 'Time: O(n * L * 26), Space: O(n * L)',
    },
  },
  {
    id: 245,
    slug: 'course-schedule-ii',
    title: 'Thứ Tự Học Môn (Topological Sort)',
    description: 'Có n môn học (0 đến n-1) và danh sách điều kiện tiên quyết. Tìm thứ tự học hợp lệ. Nếu không thể (có chu trình), in -1. Nếu nhiều đáp án, in bất kỳ.',
    difficulty: 'hard',
    tags: ['Đồ thị', 'Topological Sort', 'BFS'],
    acceptanceRate: 35,
    xp: 80,
    starterCode: 'n, m = map(int, input().split())\nprereqs = []\nfor _ in range(m):\n    a, b = map(int, input().split())\n    prereqs.append((a, b))\n# Tìm thứ tự học hợp lệ (b phải học trước a)\n',
    testCases: [
      { input: '4 4\n1 0\n2 0\n3 1\n3 2', expectedOutput: '0 1 2 3', isHidden: false },
      { input: '2 2\n1 0\n0 1', expectedOutput: '-1', isHidden: false },
      { input: '3 0', expectedOutput: '0 1 2', isHidden: true },
    ],
    hints: ['Dùng Topological Sort (BFS với Kahn algorithm)', 'Tính in-degree cho mỗi node, bắt đầu từ node có in-degree = 0', 'Nếu kết quả không đủ n node thì có chu trình'],
    editorial: {
      approach: 'Kahn Algorithm (BFS Topological Sort): bắt đầu từ node in-degree=0, giảm in-degree hàng xóm.',
      code: 'from collections import deque, defaultdict\nn, m = map(int, input().split())\ngraph = defaultdict(list)\nin_degree = [0] * n\nfor _ in range(m):\n    a, b = map(int, input().split())\n    graph[b].append(a)\n    in_degree[a] += 1\nqueue = deque()\nfor i in range(n):\n    if in_degree[i] == 0:\n        queue.append(i)\norder = []\nwhile queue:\n    node = queue.popleft()\n    order.append(node)\n    for neighbor in graph[node]:\n        in_degree[neighbor] -= 1\n        if in_degree[neighbor] == 0:\n            queue.append(neighbor)\nif len(order) == n:\n    print(*order)\nelse:\n    print(-1)',
      complexity: 'Time: O(V + E), Space: O(V + E)',
    },
  },
  {
    id: 246,
    slug: 'network-delay-time',
    title: 'Thời Gian Truyền Mạng (Dijkstra)',
    description: 'Cho đồ thị có hướng có trọng số với n node và m cạnh. Từ node nguồn k, tìm thời gian để tín hiệu đến tất cả node. Nếu không thể đến hết, in -1.',
    difficulty: 'hard',
    tags: ['Đồ thị', 'Dijkstra', 'Heap'],
    acceptanceRate: 38,
    xp: 80,
    starterCode: 'n, m = map(int, input().split())\nk = int(input())\nedges = []\nfor _ in range(m):\n    u, v, w = map(int, input().split())\n    edges.append((u, v, w))\n# Tìm thời gian truyền từ k đến tất cả node\n',
    testCases: [
      { input: '4 5\n1\n1 2 1\n1 3 4\n2 3 2\n2 4 6\n3 4 3', expectedOutput: '6', isHidden: false },
      { input: '3 2\n1\n1 2 1\n2 3 2', expectedOutput: '3', isHidden: false },
      { input: '2 0\n1', expectedOutput: '-1', isHidden: true },
    ],
    hints: ['Dùng Dijkstra tìm đường ngắn nhất từ k đến mọi node', 'Kết quả là max(dist) nếu tất cả node đều đến được', 'Dùng priority queue (heapq)'],
    editorial: {
      approach: 'Dijkstra: tìm khoảng cách ngắn nhất từ k đến mọi node, kết quả là max distance.',
      code: 'import heapq\nfrom collections import defaultdict\nn, m = map(int, input().split())\nk = int(input())\ngraph = defaultdict(list)\nfor _ in range(m):\n    u, v, w = map(int, input().split())\n    graph[u].append((v, w))\ndist = [float("inf")] * (n + 1)\ndist[k] = 0\npq = [(0, k)]\nwhile pq:\n    d, u = heapq.heappop(pq)\n    if d > dist[u]:\n        continue\n    for v, w in graph[u]:\n        if dist[u] + w < dist[v]:\n            dist[v] = dist[u] + w\n            heapq.heappush(pq, (dist[v], v))\nmax_dist = max(dist[1:n+1])\nprint(max_dist if max_dist != float("inf") else -1)',
      complexity: 'Time: O((V+E) log V), Space: O(V + E)',
    },
  },

  {
    id: 247,
    slug: 'subsets-generation',
    title: 'Sinh Tất Cả Tập Con',
    description: 'Cho mảng n số nguyên phân biệt. Sinh tất cả tập con (power set). In mỗi tập con trên 1 dòng (sắp xếp tăng dần), các tập con sắp xếp theo thứ tự từ điển. Tập rỗng in dòng trống.',
    difficulty: 'hard',
    tags: ['Quay lui', 'Mảng'],
    acceptanceRate: 44,
    xp: 60,
    starterCode: 'n = int(input())\nnums = list(map(int, input().split()))\n# Sinh tất cả tập con\n',
    testCases: [
      { input: '3\n1 2 3', expectedOutput: '\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3', isHidden: false },
      { input: '2\n0 1', expectedOutput: '\n0\n0 1\n1', isHidden: false },
      { input: '1\n5', expectedOutput: '\n5', isHidden: true },
    ],
    hints: ['Dùng backtracking: với mỗi phần tử, chọn hoặc không chọn', 'Sắp xếp mảng trước để kết quả theo thứ tự từ điển', 'Mỗi node trong cây đệ quy là một tập con hợp lệ'],
    editorial: {
      approach: 'Backtracking: sắp xếp mảng, duyệt từ chỉ số hiện tại, mỗi bước thêm phần tử hoặc bỏ qua.',
      code: 'n = int(input())\nnums = sorted(list(map(int, input().split())))\nresults = []\ndef backtrack(start, path):\n    results.append(list(path))\n    for i in range(start, n):\n        path.append(nums[i])\n        backtrack(i + 1, path)\n        path.pop()\nbacktrack(0, [])\nresults.sort()\nfor r in results:\n    print(*r)',
      complexity: 'Time: O(2^n), Space: O(n)',
    },
  },
  {
    id: 248,
    slug: 'permutations',
    title: 'Sinh Tất Cả Hoán Vị',
    description: 'Cho mảng n số nguyên phân biệt. Sinh tất cả hoán vị. In mỗi hoán vị trên 1 dòng theo thứ tự từ điển.',
    difficulty: 'hard',
    tags: ['Quay lui', 'Mảng'],
    acceptanceRate: 45,
    xp: 60,
    starterCode: 'n = int(input())\nnums = list(map(int, input().split()))\n# Sinh tất cả hoán vị\n',
    testCases: [
      { input: '3\n1 2 3', expectedOutput: '1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1', isHidden: false },
      { input: '2\n0 1', expectedOutput: '0 1\n1 0', isHidden: false },
      { input: '1\n5', expectedOutput: '5', isHidden: true },
    ],
    hints: ['Dùng backtracking với mảng visited đánh dấu phần tử đã dùng', 'Hoặc dùng swap để sinh hoán vị tại chỗ', 'Sắp xếp mảng trước để kết quả theo thứ tự từ điển'],
    editorial: {
      approach: 'Backtracking: dùng mảng used đánh dấu, mỗi bước chọn phần tử chưa dùng.',
      code: 'n = int(input())\nnums = sorted(list(map(int, input().split())))\nresults = []\nused = [False] * n\ndef backtrack(path):\n    if len(path) == n:\n        results.append(list(path))\n        return\n    for i in range(n):\n        if not used[i]:\n            used[i] = True\n            path.append(nums[i])\n            backtrack(path)\n            path.pop()\n            used[i] = False\nbacktrack([])\nfor r in results:\n    print(*r)',
      complexity: 'Time: O(n!), Space: O(n)',
    },
  },
  {
    id: 249,
    slug: 'number-of-islands',
    title: 'Đếm Số Đảo',
    description: 'Cho lưới m×n gồm "1" (đất) và "0" (nước). Đếm số đảo. Đảo là vùng đất liên thông theo 4 hướng (trên, dưới, trái, phải) được bao quanh bởi nước.',
    difficulty: 'hard',
    tags: ['Đồ thị', 'BFS', 'DFS'],
    acceptanceRate: 40,
    xp: 70,
    starterCode: 'm, n = map(int, input().split())\ngrid = []\nfor _ in range(m):\n    grid.append(list(input().split()))\n# Đếm số đảo\n',
    testCases: [
      { input: '4 5\n1 1 1 1 0\n1 1 0 1 0\n1 1 0 0 0\n0 0 0 0 0', expectedOutput: '1', isHidden: false },
      { input: '4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1', expectedOutput: '3', isHidden: false },
      { input: '1 1\n0', expectedOutput: '0', isHidden: true },
      { input: '3 3\n1 0 1\n0 1 0\n1 0 1', expectedOutput: '5', isHidden: true },
    ],
    hints: ['Duyệt từng ô, khi gặp "1" chưa thăm thì BFS/DFS để đánh dấu toàn bộ đảo', 'Mỗi lần BFS/DFS hoàn thành = 1 đảo', 'Đánh dấu ô đã thăm bằng cách đổi "1" thành "0"'],
    editorial: {
      approach: 'BFS/DFS: duyệt lưới, mỗi khi gặp "1", tăng count và BFS/DFS đánh dấu toàn bộ đảo.',
      code: 'from collections import deque\nm, n = map(int, input().split())\ngrid = []\nfor _ in range(m):\n    grid.append(list(input().split()))\ncount = 0\nfor i in range(m):\n    for j in range(n):\n        if grid[i][j] == "1":\n            count += 1\n            queue = deque([(i, j)])\n            grid[i][j] = "0"\n            while queue:\n                x, y = queue.popleft()\n                for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:\n                    nx, ny = x+dx, y+dy\n                    if 0 <= nx < m and 0 <= ny < n and grid[nx][ny] == "1":\n                        grid[nx][ny] = "0"\n                        queue.append((nx, ny))\nprint(count)',
      complexity: 'Time: O(m*n), Space: O(m*n)',
    },
  },
  {
    id: 250,
    slug: 'shortest-path-binary-matrix',
    title: 'Đường Đi Ngắn Nhất Trong Ma Trận Nhị Phân',
    description: 'Cho ma trận n×n nhị phân (0 = đi được, 1 = chặn). Tìm độ dài đường đi ngắn nhất từ (0,0) đến (n-1,n-1). Được đi 8 hướng. Nếu không thể, in -1. Độ dài = số ô đi qua.',
    difficulty: 'hard',
    tags: ['BFS', 'Đồ thị', 'Ma trận'],
    acceptanceRate: 36,
    xp: 75,
    starterCode: 'n = int(input())\ngrid = []\nfor _ in range(n):\n    grid.append(list(map(int, input().split())))\n# Tìm đường đi ngắn nhất 8 hướng\n',
    testCases: [
      { input: '3\n0 0 0\n1 1 0\n1 1 0', expectedOutput: '4', isHidden: false },
      { input: '3\n0 1 0\n0 1 0\n0 0 0', expectedOutput: '4', isHidden: false },
      { input: '2\n0 0\n0 0', expectedOutput: '2', isHidden: true },
      { input: '2\n0 1\n1 0', expectedOutput: '-1', isHidden: true },
    ],
    hints: ['Dùng BFS vì tìm đường ngắn nhất trên lưới không trọng số', 'Đi 8 hướng: 4 hướng chính + 4 hướng chéo', 'Kiểm tra ô đầu và ô cuối có bị chặn không'],
    editorial: {
      approach: 'BFS 8 hướng: bắt đầu từ (0,0), mở rộng theo 8 hướng, đếm số bước đến (n-1,n-1).',
      code: 'from collections import deque\nn = int(input())\ngrid = []\nfor _ in range(n):\n    grid.append(list(map(int, input().split())))\nif grid[0][0] == 1 or grid[n-1][n-1] == 1:\n    print(-1)\nelse:\n    queue = deque([(0, 0, 1)])\n    grid[0][0] = 1\n    found = False\n    dirs = [(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)]\n    while queue:\n        x, y, dist = queue.popleft()\n        if x == n-1 and y == n-1:\n            print(dist)\n            found = True\n            break\n        for dx, dy in dirs:\n            nx, ny = x+dx, y+dy\n            if 0 <= nx < n and 0 <= ny < n and grid[nx][ny] == 0:\n                grid[nx][ny] = 1\n                queue.append((nx, ny, dist+1))\n    if not found:\n        print(-1)',
      complexity: 'Time: O(n²), Space: O(n²)',
    },
  },
];
