import type { Problem } from './problem-bank';

export const PROBLEM_BANK_3: Problem[] = [
  // ==================== EASY: REAL-WORLD PROBLEMS (251-265) ====================
  {
    id: 251,
    slug: 'tinh-tien-dien-bac-thang',
    title: 'Tính Tiền Điện Bậc Thang',
    description: 'Cho số kWh điện tiêu thụ trong tháng. Tính tiền điện theo bậc thang:\n- Bậc 1 (0-50 kWh): 1678 đ/kWh\n- Bậc 2 (51-100 kWh): 1734 đ/kWh\n- Bậc 3 (101-200 kWh): 2014 đ/kWh\n- Bậc 4 (201-300 kWh): 2536 đ/kWh\n- Bậc 5 (301-400 kWh): 2834 đ/kWh\n- Bậc 6 (>400 kWh): 2927 đ/kWh\nIn ra tổng tiền điện (làm tròn đến hàng đơn vị).',
    difficulty: 'easy',
    tags: ['Điều kiện', 'Thực tế'],
    acceptanceRate: 72,
    xp: 15,
    starterCode: 'kwh = int(input())\n# Tính tiền điện bậc thang\n',
    testCases: [
      { input: '50', expectedOutput: '83900', isHidden: false },
      { input: '150', expectedOutput: '254500', isHidden: false },
      { input: '350', expectedOutput: '773100', isHidden: true },
    ],
    hints: [
      'Tính từng bậc: nếu kWh > 50, tính 50 kWh đầu theo bậc 1, phần còn lại tính bậc tiếp theo.',
      'Dùng biến tổng tiền, cộng dồn từng bậc cho đến khi hết kWh.',
    ],
    editorial: {
      approach: 'Tính lần lượt từng bậc, mỗi bậc lấy min(kwh còn lại, số kWh tối đa của bậc) nhân với đơn giá.',
      code: 'kwh = int(input())\nbacs = [(50,1678),(50,1734),(100,2014),(100,2536),(100,2834),(float("inf"),2927)]\ntotal = 0\nfor limit, price in bacs:\n    used = min(kwh, limit)\n    total += used * price\n    kwh -= used\n    if kwh <= 0:\n        break\nprint(total)',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  {
    id: 252,
    slug: 'kiem-tra-mat-khau-manh',
    title: 'Kiểm Tra Mật Khẩu Mạnh',
    description: 'Cho một chuỗi mật khẩu. Kiểm tra xem mật khẩu có mạnh không. Mật khẩu mạnh cần thỏa mãn TẤT CẢ:\n- Ít nhất 8 ký tự\n- Có ít nhất 1 chữ hoa\n- Có ít nhất 1 chữ thường\n- Có ít nhất 1 chữ số\n- Có ít nhất 1 ký tự đặc biệt (!@#$%^&*)\nIn "STRONG" nếu mạnh, "WEAK" nếu yếu.',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Thực tế'],
    acceptanceRate: 68,
    xp: 15,
    starterCode: 'password = input()\n# Kiểm tra mật khẩu mạnh\n',
    testCases: [
      { input: 'Abc12345!', expectedOutput: 'STRONG', isHidden: false },
      { input: 'abc123', expectedOutput: 'WEAK', isHidden: false },
      { input: 'ABCDEFGH1!', expectedOutput: 'WEAK', isHidden: true },
      { input: 'aB3!xyzw', expectedOutput: 'STRONG', isHidden: true },
    ],
    hints: [
      'Dùng các hàm isupper(), islower(), isdigit() để kiểm tra từng ký tự.',
      'Kiểm tra ký tự đặc biệt bằng cách so sánh với chuỗi "!@#$%^&*".',
    ],
    editorial: {
      approach: 'Duyệt qua từng ký tự, đánh dấu các điều kiện đã thỏa mãn. Cuối cùng kiểm tra tất cả điều kiện.',
      code: 'password = input()\nhas_upper = any(c.isupper() for c in password)\nhas_lower = any(c.islower() for c in password)\nhas_digit = any(c.isdigit() for c in password)\nhas_special = any(c in "!@#$%^&*" for c in password)\nif len(password) >= 8 and has_upper and has_lower and has_digit and has_special:\n    print("STRONG")\nelse:\n    print("WEAK")',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 253,
    slug: 'dem-ngay-giua-hai-ngay',
    title: 'Đếm Ngày Giữa Hai Ngày',
    description: 'Cho hai ngày theo định dạng DD/MM/YYYY (mỗi ngày trên một dòng). Tính số ngày giữa hai ngày đó (giá trị tuyệt đối). Lưu ý năm nhuận: chia hết cho 4 nhưng không chia hết cho 100, hoặc chia hết cho 400.',
    difficulty: 'easy',
    tags: ['Toán', 'Thực tế'],
    acceptanceRate: 55,
    xp: 20,
    starterCode: 'date1 = input()  # DD/MM/YYYY\ndate2 = input()  # DD/MM/YYYY\n# Tính số ngày giữa hai ngày\n',
    testCases: [
      { input: '01/01/2024\n31/01/2024', expectedOutput: '30', isHidden: false },
      { input: '28/02/2024\n01/03/2024', expectedOutput: '2', isHidden: false },
      { input: '01/01/2023\n01/01/2024', expectedOutput: '365', isHidden: true },
    ],
    hints: [
      'Chuyển mỗi ngày thành số ngày kể từ một mốc cố định (ví dụ 01/01/0001).',
      'Nhớ xử lý năm nhuận khi tính số ngày trong tháng 2.',
    ],
    editorial: {
      approach: 'Dùng thư viện datetime để parse và tính hiệu hai ngày, hoặc tự tính bằng cách chuyển về số ngày từ mốc.',
      code: 'from datetime import datetime\ndate1 = input()\ndate2 = input()\nd1 = datetime.strptime(date1, "%d/%m/%Y")\nd2 = datetime.strptime(date2, "%d/%m/%Y")\nprint(abs((d2 - d1).days))',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  {
    id: 254,
    slug: 'mo-phong-atm-rut-tien',
    title: 'Mô Phỏng ATM Rút Tiền',
    description: 'Mô phỏng máy ATM. Cho số tiền cần rút (đơn vị nghìn đồng). ATM chỉ có các tờ: 500, 200, 100, 50, 20, 10 (nghìn đồng). Tìm cách rút ít tờ nhất. In ra số lượng mỗi loại tờ tiền (chỉ in loại có số lượng > 0), mỗi dòng gồm "mệnh_giá: số_lượng". Nếu không rút được (số tiền không chia hết cho 10), in "INVALID".',
    difficulty: 'easy',
    tags: ['Tham lam', 'Thực tế'],
    acceptanceRate: 65,
    xp: 15,
    starterCode: 'amount = int(input())  # Số tiền cần rút (nghìn đồng)\n# Mô phỏng ATM\n',
    testCases: [
      { input: '1370', expectedOutput: '500: 2\n200: 1\n100: 1\n50: 1\n20: 1', isHidden: false },
      { input: '50', expectedOutput: '50: 1', isHidden: false },
      { input: '15', expectedOutput: 'INVALID', isHidden: true },
    ],
    hints: [
      'Dùng thuật toán tham lam: luôn chọn tờ lớn nhất có thể.',
      'Chia lấy phần nguyên cho mệnh giá lớn nhất, rồi lấy phần dư tiếp tục.',
    ],
    editorial: {
      approach: 'Greedy: lần lượt chia cho các mệnh giá từ lớn đến nhỏ, lấy số tờ tối đa có thể.',
      code: 'amount = int(input())\nif amount % 10 != 0:\n    print("INVALID")\nelse:\n    bills = [500, 200, 100, 50, 20, 10]\n    for b in bills:\n        count = amount // b\n        if count > 0:\n            print(f"{b}: {count}")\n            amount %= b',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  {
    id: 255,
    slug: 'tinh-diem-trung-binh-gpa',
    title: 'Tính Điểm Trung Bình GPA',
    description: 'Cho n môn học, mỗi môn gồm: tên môn, số tín chỉ, và điểm số (thang 10). Tính GPA theo thang 4:\n- 8.5-10: 4.0\n- 7.0-8.4: 3.0\n- 5.5-6.9: 2.0\n- 4.0-5.4: 1.0\n- <4.0: 0.0\nGPA = Σ(điểm_4 × tín_chỉ) / Σ(tín_chỉ). In GPA làm tròn 2 chữ số thập phân.',
    difficulty: 'easy',
    tags: ['Toán', 'Thực tế'],
    acceptanceRate: 70,
    xp: 15,
    starterCode: 'n = int(input())\n# Mỗi dòng tiếp theo: tên_môn số_tín_chỉ điểm_10\n# Tính GPA thang 4\n',
    testCases: [
      { input: '3\nToan 3 8.5\nLy 2 7.0\nHoa 3 5.0', expectedOutput: '2.63', isHidden: false },
      { input: '2\nLTW 4 9.0\nCTDL 3 8.0', expectedOutput: '3.57', isHidden: false },
      { input: '1\nAV 2 3.5', expectedOutput: '0.00', isHidden: true },
    ],
    hints: [
      'Chuyển điểm thang 10 sang thang 4 theo bảng quy đổi.',
      'GPA = tổng(điểm_4 * tín_chỉ) / tổng(tín_chỉ).',
    ],
    editorial: {
      approach: 'Duyệt từng môn, chuyển điểm sang thang 4, tính tổng có trọng số rồi chia cho tổng tín chỉ.',
      code: 'n = int(input())\ntotal_weighted = 0\ntotal_credits = 0\nfor _ in range(n):\n    parts = input().split()\n    credits = int(parts[-2])\n    score = float(parts[-1])\n    if score >= 8.5: gpa4 = 4.0\n    elif score >= 7.0: gpa4 = 3.0\n    elif score >= 5.5: gpa4 = 2.0\n    elif score >= 4.0: gpa4 = 1.0\n    else: gpa4 = 0.0\n    total_weighted += gpa4 * credits\n    total_credits += credits\nprint(f"{total_weighted / total_credits:.2f}")',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 256,
    slug: 'game-oan-tu-ti',
    title: 'Game Oẳn Tù Tì',
    description: 'Mô phỏng game oẳn tù tì giữa 2 người chơi. Cho n lượt chơi, mỗi lượt gồm lựa chọn của 2 người (R=Búa, P=Bao, S=Kéo). Tính kết quả: in số lần thắng của người 1, người 2, và số lần hòa, cách nhau bởi dấu cách.',
    difficulty: 'easy',
    tags: ['Logic', 'Thực tế'],
    acceptanceRate: 75,
    xp: 10,
    starterCode: 'n = int(input())\n# Mỗi dòng tiếp theo: lựa_chọn_1 lựa_chọn_2 (R/P/S)\n',
    testCases: [
      { input: '3\nR S\nP P\nS R', expectedOutput: '2 0 1', isHidden: false },
      { input: '2\nR P\nS P', expectedOutput: '0 2 0', isHidden: false },
      { input: '4\nR R\nP P\nS S\nR S', expectedOutput: '1 0 3', isHidden: true },
    ],
    hints: [
      'R thắng S, S thắng P, P thắng R.',
      'Dùng dict hoặc if-else để xác định ai thắng mỗi lượt.',
    ],
    editorial: {
      approach: 'Duyệt từng lượt, so sánh lựa chọn theo luật để xác định thắng/thua/hòa.',
      code: 'n = int(input())\nw1 = w2 = draw = 0\nwins = {"RS", "SP", "PR"}\nfor _ in range(n):\n    a, b = input().split()\n    if a == b:\n        draw += 1\n    elif a + b in wins:\n        w1 += 1\n    else:\n        w2 += 1\nprint(w1, w2, draw)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 257,
    slug: 'ma-hoa-rot13',
    title: 'Mã Hóa/Giải Mã ROT13',
    description: 'Cho một chuỗi và lệnh (ENCODE hoặc DECODE). Thực hiện mã hóa/giải mã ROT13: dịch mỗi chữ cái đi 13 vị trí trong bảng chữ cái (a→n, b→o, ..., z→m). Giữ nguyên ký tự không phải chữ cái. Lưu ý: ROT13 là đối xứng nên ENCODE và DECODE cho cùng kết quả.',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Mã hóa'],
    acceptanceRate: 70,
    xp: 15,
    starterCode: 'command = input()  # ENCODE hoặc DECODE\ntext = input()\n# Thực hiện ROT13\n',
    testCases: [
      { input: 'ENCODE\nHello World!', expectedOutput: 'Uryyb Jbeyq!', isHidden: false },
      { input: 'DECODE\nUryyb Jbeyq!', expectedOutput: 'Hello World!', isHidden: false },
      { input: 'ENCODE\nabc XYZ 123', expectedOutput: 'nop KLM 123', isHidden: true },
    ],
    hints: [
      'ROT13 dịch mỗi chữ cái đi 13 vị trí, quay vòng khi vượt quá z/Z.',
      'Dùng ord() và chr() để tính toán vị trí mới.',
    ],
    editorial: {
      approach: 'Duyệt từng ký tự, nếu là chữ cái thì dịch đi 13 vị trí (mod 26), giữ nguyên hoa/thường.',
      code: 'command = input()\ntext = input()\nresult = []\nfor c in text:\n    if c.isalpha():\n        base = ord("A") if c.isupper() else ord("a")\n        result.append(chr((ord(c) - base + 13) % 26 + base))\n    else:\n        result.append(c)\nprint("".join(result))',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 258,
    slug: 'kiem-tra-email-hop-le',
    title: 'Kiểm Tra Email Hợp Lệ',
    description: 'Cho một chuỗi email. Kiểm tra xem email có hợp lệ không theo các quy tắc:\n- Có đúng 1 ký tự @\n- Phần trước @ (local): chỉ chứa chữ cái, số, dấu chấm, gạch dưới; không rỗng; không bắt đầu/kết thúc bằng dấu chấm\n- Phần sau @ (domain): chứa ít nhất 1 dấu chấm; chỉ chứa chữ cái, số, dấu chấm, gạch ngang; phần sau dấu chấm cuối ít nhất 2 ký tự\nIn "VALID" hoặc "INVALID".',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Thực tế'],
    acceptanceRate: 58,
    xp: 20,
    starterCode: 'email = input()\n# Kiểm tra email hợp lệ\n',
    testCases: [
      { input: 'user@example.com', expectedOutput: 'VALID', isHidden: false },
      { input: 'invalid@.com', expectedOutput: 'INVALID', isHidden: false },
      { input: '.user@domain.co', expectedOutput: 'INVALID', isHidden: true },
      { input: 'a.b_c@sub.domain.vn', expectedOutput: 'VALID', isHidden: true },
    ],
    hints: [
      'Tách chuỗi theo @ trước, kiểm tra có đúng 2 phần.',
      'Kiểm tra từng phần theo quy tắc riêng.',
    ],
    editorial: {
      approach: 'Tách email theo @, kiểm tra local part và domain part theo từng quy tắc.',
      code: 'email = input()\nif email.count("@") != 1:\n    print("INVALID")\nelse:\n    local, domain = email.split("@")\n    valid_local = len(local) > 0 and not local.startswith(".") and not local.endswith(".")\n    valid_local = valid_local and all(c.isalnum() or c in "._" for c in local)\n    valid_domain = "." in domain and all(c.isalnum() or c in ".-" for c in domain)\n    valid_domain = valid_domain and len(domain.split(".")[-1]) >= 2\n    valid_domain = valid_domain and not domain.startswith(".") and not domain.startswith("-")\n    print("VALID" if valid_local and valid_domain else "INVALID")',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 259,
    slug: 'chuyen-so-la-ma',
    title: 'Chuyển Số La Mã Sang Số Thường',
    description: 'Cho một chuỗi số La Mã hợp lệ (I, V, X, L, C, D, M). Chuyển sang số nguyên thập phân.\nQuy tắc: I=1, V=5, X=10, L=50, C=100, D=500, M=1000. Nếu ký tự nhỏ đứng trước ký tự lớn thì trừ (IV=4, IX=9, XL=40, XC=90, CD=400, CM=900).',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Toán'],
    acceptanceRate: 72,
    xp: 15,
    starterCode: 'roman = input()\n# Chuyển số La Mã sang số thường\n',
    testCases: [
      { input: 'XIV', expectedOutput: '14', isHidden: false },
      { input: 'MCMXCIV', expectedOutput: '1994', isHidden: false },
      { input: 'LVIII', expectedOutput: '58', isHidden: true },
    ],
    hints: [
      'Duyệt từ trái sang phải, nếu giá trị hiện tại < giá trị kế tiếp thì trừ, ngược lại thì cộng.',
      'Dùng dict để map ký tự La Mã sang giá trị số.',
    ],
    editorial: {
      approach: 'Duyệt chuỗi, so sánh giá trị hiện tại với giá trị tiếp theo để quyết định cộng hay trừ.',
      code: 'roman = input()\nvalues = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}\nresult = 0\nfor i in range(len(roman)):\n    if i + 1 < len(roman) and values[roman[i]] < values[roman[i+1]]:\n        result -= values[roman[i]]\n    else:\n        result += values[roman[i]]\nprint(result)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 260,
    slug: 'tinh-tien-taxi',
    title: 'Tính Tiền Taxi Theo Km',
    description: 'Tính tiền taxi theo quãng đường (km, số thực):\n- Mở cửa (0.5 km đầu): 12000 đ\n- 0.5-30 km: 15000 đ/km\n- Trên 30 km: 11000 đ/km\nNếu tổng tiền > 200000 thì được giảm 10% trên phần vượt 200000.\nIn tổng tiền (làm tròn đến hàng nghìn).',
    difficulty: 'easy',
    tags: ['Toán', 'Thực tế'],
    acceptanceRate: 65,
    xp: 15,
    starterCode: 'km = float(input())\n# Tính tiền taxi\n',
    testCases: [
      { input: '5.0', expectedOutput: '79000', isHidden: false },
      { input: '35.0', expectedOutput: '510000', isHidden: false },
      { input: '0.3', expectedOutput: '12000', isHidden: true },
    ],
    hints: [
      'Tính từng đoạn: mở cửa, 0.5-30km, trên 30km.',
      'Nhớ áp dụng giảm giá 10% cho phần vượt 200000.',
    ],
    editorial: {
      approach: 'Tính tiền từng đoạn, cộng lại, áp dụng giảm giá nếu cần, làm tròn.',
      code: 'import math\nkm = float(input())\ntotal = 12000\nif km > 0.5:\n    if km <= 30:\n        total += (km - 0.5) * 15000\n    else:\n        total += 29.5 * 15000 + (km - 30) * 11000\nif total > 200000:\n    total = 200000 + (total - 200000) * 0.9\ntotal = round(total / 1000) * 1000\nprint(int(total))',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  {
    id: 261,
    slug: 'dem-tu-xuat-hien-nhieu-nhat',
    title: 'Đếm Từ Xuất Hiện Nhiều Nhất',
    description: 'Cho một đoạn văn bản (một dòng). Tìm từ xuất hiện nhiều nhất (không phân biệt hoa thường). Nếu có nhiều từ cùng tần suất cao nhất, in từ xuất hiện đầu tiên trong văn bản. In ra từ đó (chữ thường) và số lần xuất hiện, cách nhau bởi dấu cách.',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Hash Map'],
    acceptanceRate: 62,
    xp: 15,
    starterCode: 'text = input()\n# Tìm từ xuất hiện nhiều nhất\n',
    testCases: [
      { input: 'the cat sat on the mat the', expectedOutput: 'the 3', isHidden: false },
      { input: 'Hello hello HELLO world', expectedOutput: 'hello 3', isHidden: false },
      { input: 'a b c a b a', expectedOutput: 'a 3', isHidden: true },
    ],
    hints: [
      'Tách chuỗi thành danh sách từ, chuyển về chữ thường.',
      'Dùng dict đếm tần suất, sau đó tìm max.',
    ],
    editorial: {
      approach: 'Tách từ, đếm tần suất bằng dict, tìm từ có tần suất cao nhất (ưu tiên xuất hiện đầu).',
      code: 'text = input()\nwords = text.lower().split()\ncount = {}\norder = []\nfor w in words:\n    if w not in count:\n        count[w] = 0\n        order.append(w)\n    count[w] += 1\nmax_word = max(order, key=lambda w: count[w])\nprint(max_word, count[max_word])',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 262,
    slug: 'nen-chuoi-rle',
    title: 'Nén Chuỗi (Run-Length Encoding)',
    description: 'Cho một chuỗi chỉ gồm chữ cái. Thực hiện nén Run-Length Encoding: thay mỗi nhóm ký tự liên tiếp giống nhau bằng ký tự đó + số lần lặp. Nếu ký tự chỉ xuất hiện 1 lần liên tiếp thì không ghi số.\nVí dụ: "aaabbc" → "a3b2c"',
    difficulty: 'easy',
    tags: ['Chuỗi', 'Thuật toán'],
    acceptanceRate: 68,
    xp: 15,
    starterCode: 's = input()\n# Nén chuỗi bằng Run-Length Encoding\n',
    testCases: [
      { input: 'aaabbc', expectedOutput: 'a3b2c', isHidden: false },
      { input: 'abcd', expectedOutput: 'abcd', isHidden: false },
      { input: 'aaaaaa', expectedOutput: 'a6', isHidden: true },
    ],
    hints: [
      'Duyệt chuỗi, đếm số ký tự liên tiếp giống nhau.',
      'Khi gặp ký tự khác hoặc hết chuỗi, ghi kết quả.',
    ],
    editorial: {
      approach: 'Duyệt chuỗi, đếm nhóm liên tiếp, nối ký tự + số đếm (bỏ số 1).',
      code: 's = input()\nresult = []\ni = 0\nwhile i < len(s):\n    count = 1\n    while i + count < len(s) and s[i + count] == s[i]:\n        count += 1\n    result.append(s[i] + (str(count) if count > 1 else ""))\n    i += count\nprint("".join(result))',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 263,
    slug: 'kiem-tra-so-armstrong',
    title: 'Kiểm Tra Số Armstrong',
    description: 'Cho số nguyên dương n. Kiểm tra xem n có phải là số Armstrong không. Số Armstrong là số có k chữ số mà tổng lũy thừa bậc k của từng chữ số bằng chính nó.\nVí dụ: 153 = 1³ + 5³ + 3³ = 153 (Armstrong)\nIn "YES" hoặc "NO".',
    difficulty: 'easy',
    tags: ['Toán', 'Vòng lặp'],
    acceptanceRate: 78,
    xp: 10,
    starterCode: 'n = int(input())\n# Kiểm tra số Armstrong\n',
    testCases: [
      { input: '153', expectedOutput: 'YES', isHidden: false },
      { input: '123', expectedOutput: 'NO', isHidden: false },
      { input: '9474', expectedOutput: 'YES', isHidden: true },
      { input: '1', expectedOutput: 'YES', isHidden: true },
    ],
    hints: [
      'Đếm số chữ số k = len(str(n)).',
      'Tính tổng mỗi chữ số mũ k, so sánh với n.',
    ],
    editorial: {
      approach: 'Tách từng chữ số, tính tổng lũy thừa bậc k, so sánh với số ban đầu.',
      code: 'n = int(input())\ndigits = str(n)\nk = len(digits)\ntotal = sum(int(d) ** k for d in digits)\nprint("YES" if total == n else "NO")',
      complexity: 'Time: O(k), Space: O(k)',
    },
  },
  {
    id: 264,
    slug: 'tim-ngay-trong-tuan',
    title: 'Tìm Ngày Trong Tuần',
    description: 'Cho ngày theo định dạng DD/MM/YYYY. Xác định ngày đó là thứ mấy trong tuần. In ra tên thứ bằng tiếng Việt: "Thu Hai", "Thu Ba", "Thu Tu", "Thu Nam", "Thu Sau", "Thu Bay", "Chu Nhat".',
    difficulty: 'easy',
    tags: ['Toán', 'Thực tế'],
    acceptanceRate: 60,
    xp: 15,
    starterCode: 'date = input()  # DD/MM/YYYY\n# Tìm ngày trong tuần\n',
    testCases: [
      { input: '01/01/2024', expectedOutput: 'Thu Hai', isHidden: false },
      { input: '25/12/2024', expectedOutput: 'Thu Tu', isHidden: false },
      { input: '14/02/2024', expectedOutput: 'Thu Tu', isHidden: true },
    ],
    hints: [
      'Dùng công thức Zeller hoặc thư viện datetime.',
      'weekday() trả về 0=Monday, 6=Sunday.',
    ],
    editorial: {
      approach: 'Dùng datetime để parse ngày và lấy weekday, map sang tên tiếng Việt.',
      code: 'from datetime import datetime\ndate = input()\nd = datetime.strptime(date, "%d/%m/%Y")\ndays = ["Thu Hai","Thu Ba","Thu Tu","Thu Nam","Thu Sau","Thu Bay","Chu Nhat"]\nprint(days[d.weekday()])',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  {
    id: 265,
    slug: 'tinh-lai-suat-kep',
    title: 'Tính Lãi Suất Kép',
    description: 'Cho số tiền gốc P, lãi suất năm r (%), số lần ghép lãi trong năm n, và số năm t. Tính số tiền cuối cùng theo công thức lãi kép: A = P × (1 + r/(100×n))^(n×t). In kết quả làm tròn đến hàng đơn vị.',
    difficulty: 'easy',
    tags: ['Toán', 'Thực tế'],
    acceptanceRate: 75,
    xp: 10,
    starterCode: 'P = float(input())  # Tiền gốc\nr = float(input())  # Lãi suất năm (%)\nn = int(input())    # Số lần ghép lãi/năm\nt = int(input())    # Số năm\n# Tính lãi kép\n',
    testCases: [
      { input: '1000000\n8.0\n12\n5', expectedOutput: '1489846', isHidden: false },
      { input: '5000000\n10.0\n4\n3', expectedOutput: '6724445', isHidden: false },
      { input: '100000\n5.0\n1\n10', expectedOutput: '162889', isHidden: true },
    ],
    hints: [
      'Áp dụng trực tiếp công thức A = P * (1 + r/(100*n))^(n*t).',
      'Dùng toán tử ** để tính lũy thừa.',
    ],
    editorial: {
      approach: 'Áp dụng công thức lãi kép trực tiếp.',
      code: 'P = float(input())\nr = float(input())\nn = int(input())\nt = int(input())\nA = P * (1 + r / (100 * n)) ** (n * t)\nprint(round(A))',
      complexity: 'Time: O(1), Space: O(1)',
    },
  },
  // ==================== MEDIUM: COMPETITIVE PROGRAMMING BASICS (266-285) ====================
  {
    id: 266,
    slug: 'prefix-sum-range-query',
    title: 'Prefix Sum - Truy Vấn Tổng Đoạn',
    description: 'Cho mảng n số nguyên và q truy vấn. Mỗi truy vấn gồm 2 số l, r (1-indexed). Với mỗi truy vấn, in ra tổng các phần tử từ vị trí l đến r.',
    difficulty: 'medium',
    tags: ['Prefix Sum', 'Mảng'],
    acceptanceRate: 55,
    xp: 30,
    starterCode: 'n, q = map(int, input().split())\narr = list(map(int, input().split()))\n# Xử lý q truy vấn tổng đoạn\n',
    testCases: [
      { input: '5 3\n1 2 3 4 5\n1 3\n2 5\n1 5', expectedOutput: '6\n14\n15', isHidden: false },
      { input: '4 2\n10 20 30 40\n1 1\n1 4', expectedOutput: '10\n100', isHidden: false },
      { input: '3 1\n-5 10 -3\n1 3', expectedOutput: '2', isHidden: true },
    ],
    hints: [
      'Xây dựng mảng prefix sum: prefix[i] = tổng arr[0..i-1].',
      'Tổng đoạn [l,r] = prefix[r] - prefix[l-1].',
      'Tiền xử lý O(n), mỗi truy vấn O(1).',
    ],
    editorial: {
      approach: 'Xây dựng mảng prefix sum, trả lời mỗi truy vấn trong O(1).',
      code: 'n, q = map(int, input().split())\narr = list(map(int, input().split()))\nprefix = [0] * (n + 1)\nfor i in range(n):\n    prefix[i + 1] = prefix[i] + arr[i]\nfor _ in range(q):\n    l, r = map(int, input().split())\n    print(prefix[r] - prefix[l - 1])',
      complexity: 'Time: O(n + q), Space: O(n)',
    },
  },
  {
    id: 267,
    slug: 'kadane-max-subarray-advanced',
    title: 'Kadane Nâng Cao - Mảng Con Tổng Lớn Nhất Có Vị Trí',
    description: 'Cho mảng n số nguyên. Tìm mảng con liên tiếp có tổng lớn nhất. In ra 3 số: tổng lớn nhất, chỉ số bắt đầu và chỉ số kết thúc (0-indexed). Nếu có nhiều đáp án, in đáp án có chỉ số bắt đầu nhỏ nhất.',
    difficulty: 'medium',
    tags: ['Mảng', 'Quy hoạch động'],
    acceptanceRate: 48,
    xp: 35,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm mảng con tổng lớn nhất kèm vị trí\n',
    testCases: [
      { input: '8\n-2 1 -3 4 -1 2 1 -5', expectedOutput: '6 3 6', isHidden: false },
      { input: '5\n-1 -2 -3 -4 -5', expectedOutput: '-1 0 0', isHidden: false },
      { input: '3\n5 -2 5', expectedOutput: '8 0 2', isHidden: true },
    ],
    hints: [
      'Dùng thuật toán Kadane: duy trì tổng hiện tại và tổng lớn nhất.',
      'Khi tổng hiện tại < 0, reset về 0 và cập nhật vị trí bắt đầu mới.',
      'Cập nhật vị trí kết thúc khi tìm được tổng mới lớn hơn.',
    ],
    editorial: {
      approach: 'Kadane algorithm mở rộng: theo dõi thêm chỉ số bắt đầu tạm và chỉ số bắt đầu/kết thúc tốt nhất.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nmax_sum = arr[0]\ncur_sum = arr[0]\nstart = end = temp_start = 0\nfor i in range(1, n):\n    if cur_sum + arr[i] < arr[i]:\n        cur_sum = arr[i]\n        temp_start = i\n    else:\n        cur_sum += arr[i]\n    if cur_sum > max_sum:\n        max_sum = cur_sum\n        start = temp_start\n        end = i\nprint(max_sum, start, end)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 268,
    slug: 'dem-bit-1',
    title: 'Đếm Số Bit 1 (Popcount)',
    description: 'Cho n số nguyên không âm. Với mỗi số, đếm số bit 1 trong biểu diễn nhị phân. In kết quả mỗi số trên một dòng.',
    difficulty: 'medium',
    tags: ['Bit Manipulation', 'Toán'],
    acceptanceRate: 65,
    xp: 25,
    starterCode: 'n = int(input())\n# Với mỗi số, đếm số bit 1\nfor _ in range(n):\n    x = int(input())\n    # Đếm bit 1 của x\n',
    testCases: [
      { input: '3\n5\n7\n0', expectedOutput: '2\n3\n0', isHidden: false },
      { input: '2\n255\n1024', expectedOutput: '8\n1', isHidden: false },
      { input: '1\n2147483647', expectedOutput: '31', isHidden: true },
    ],
    hints: [
      'Dùng phép AND bit: x & 1 cho bit cuối, rồi dịch phải x >> 1.',
      'Hoặc dùng trick: x & (x-1) xóa bit 1 cuối cùng.',
    ],
    editorial: {
      approach: 'Dùng Brian Kernighan trick: x & (x-1) xóa bit 1 thấp nhất, đếm số lần thực hiện.',
      code: 'n = int(input())\nfor _ in range(n):\n    x = int(input())\n    count = 0\n    while x:\n        x &= x - 1\n        count += 1\n    print(count)',
      complexity: 'Time: O(n × k) với k là số bit 1, Space: O(1)',
    },
  },
  {
    id: 269,
    slug: 'greedy-scheduling',
    title: 'Lập Lịch Tham Lam - Nhiều Công Việc Nhất',
    description: 'Cho n công việc, mỗi công việc có thời gian bắt đầu và kết thúc. Tìm số lượng công việc nhiều nhất có thể thực hiện sao cho không có 2 công việc nào chồng chéo thời gian.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Sắp xếp'],
    acceptanceRate: 52,
    xp: 30,
    starterCode: 'n = int(input())\n# Mỗi dòng tiếp theo: start end\n# Tìm số công việc nhiều nhất không chồng chéo\n',
    testCases: [
      { input: '4\n1 3\n2 5\n4 7\n6 8', expectedOutput: '3', isHidden: false },
      { input: '3\n1 10\n2 3\n4 5', expectedOutput: '2', isHidden: false },
      { input: '5\n1 2\n2 3\n3 4\n4 5\n5 6', expectedOutput: '5', isHidden: true },
    ],
    hints: [
      'Sắp xếp công việc theo thời gian kết thúc tăng dần.',
      'Chọn công việc kết thúc sớm nhất mà không xung đột với công việc đã chọn.',
    ],
    editorial: {
      approach: 'Greedy: sắp xếp theo end time, luôn chọn công việc kết thúc sớm nhất không xung đột.',
      code: 'n = int(input())\njobs = []\nfor _ in range(n):\n    s, e = map(int, input().split())\n    jobs.append((s, e))\njobs.sort(key=lambda x: x[1])\ncount = 0\nlast_end = -1\nfor s, e in jobs:\n    if s >= last_end:\n        count += 1\n        last_end = e\nprint(count)',
      complexity: 'Time: O(n log n), Space: O(n)',
    },
  },
  {
    id: 270,
    slug: 'matrix-rotation-90',
    title: 'Xoay Ma Trận 90 Độ',
    description: 'Cho ma trận vuông n×n. Xoay ma trận 90 độ theo chiều kim đồng hồ. In ma trận kết quả, mỗi hàng trên một dòng, các phần tử cách nhau bởi dấu cách.',
    difficulty: 'medium',
    tags: ['Ma trận', 'Mảng'],
    acceptanceRate: 50,
    xp: 30,
    starterCode: 'n = int(input())\nmatrix = []\nfor _ in range(n):\n    row = list(map(int, input().split()))\n    matrix.append(row)\n# Xoay 90 độ theo chiều kim đồng hồ\n',
    testCases: [
      { input: '3\n1 2 3\n4 5 6\n7 8 9', expectedOutput: '7 4 1\n8 5 2\n9 6 3', isHidden: false },
      { input: '2\n1 2\n3 4', expectedOutput: '3 1\n4 2', isHidden: false },
      { input: '4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16', expectedOutput: '13 9 5 1\n14 10 6 2\n15 11 7 3\n16 12 8 4', isHidden: true },
    ],
    hints: [
      'Xoay 90 độ CW = transpose + reverse mỗi hàng.',
      'Hoặc: phần tử [i][j] mới = phần tử [n-1-j][i] cũ.',
    ],
    editorial: {
      approach: 'Transpose ma trận rồi đảo ngược mỗi hàng, hoặc tạo ma trận mới với công thức ánh xạ.',
      code: 'n = int(input())\nmatrix = []\nfor _ in range(n):\n    matrix.append(list(map(int, input().split())))\nrotated = [[matrix[n-1-j][i] for j in range(n)] for i in range(n)]\nfor row in rotated:\n    print(" ".join(map(str, row)))',
      complexity: 'Time: O(n²), Space: O(n²)',
    },
  },
  {
    id: 271,
    slug: 'spiral-matrix',
    title: 'In Ma Trận Xoắn Ốc',
    description: 'Cho ma trận m×n. In các phần tử theo thứ tự xoắn ốc (từ ngoài vào trong, theo chiều kim đồng hồ). In trên một dòng, cách nhau bởi dấu cách.',
    difficulty: 'medium',
    tags: ['Ma trận', 'Mảng'],
    acceptanceRate: 42,
    xp: 35,
    starterCode: 'm, n = map(int, input().split())\nmatrix = []\nfor _ in range(m):\n    row = list(map(int, input().split()))\n    matrix.append(row)\n# In ma trận theo thứ tự xoắn ốc\n',
    testCases: [
      { input: '3 3\n1 2 3\n4 5 6\n7 8 9', expectedOutput: '1 2 3 6 9 8 7 4 5', isHidden: false },
      { input: '2 4\n1 2 3 4\n5 6 7 8', expectedOutput: '1 2 3 4 8 7 6 5', isHidden: false },
      { input: '3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12', expectedOutput: '1 2 3 4 8 12 11 10 9 5 6 7', isHidden: true },
    ],
    hints: [
      'Dùng 4 biến biên: top, bottom, left, right.',
      'Duyệt theo 4 hướng: phải, xuống, trái, lên. Thu hẹp biên sau mỗi lượt.',
    ],
    editorial: {
      approach: 'Dùng 4 biên, duyệt lần lượt 4 cạnh của hình chữ nhật, thu hẹp dần.',
      code: 'm, n = map(int, input().split())\nmatrix = [list(map(int, input().split())) for _ in range(m)]\nresult = []\ntop, bottom, left, right = 0, m - 1, 0, n - 1\nwhile top <= bottom and left <= right:\n    for i in range(left, right + 1): result.append(matrix[top][i])\n    top += 1\n    for i in range(top, bottom + 1): result.append(matrix[i][right])\n    right -= 1\n    if top <= bottom:\n        for i in range(right, left - 1, -1): result.append(matrix[bottom][i])\n        bottom -= 1\n    if left <= right:\n        for i in range(bottom, top - 1, -1): result.append(matrix[i][left])\n        left += 1\nprint(" ".join(map(str, result)))',
      complexity: 'Time: O(m×n), Space: O(m×n)',
    },
  },
  {
    id: 272,
    slug: 'zigzag-conversion',
    title: 'Chuyển Đổi Zigzag',
    description: 'Cho chuỗi s và số hàng numRows. Viết chuỗi theo dạng zigzag trên numRows hàng, rồi đọc lại theo từng hàng. In chuỗi kết quả.\nVí dụ: "PAYPALISHIRING" với 3 hàng:\nP   A   H   N\nA P L S I I G\nY   I   R\nĐọc: "PAHNAPLSIIGYIR"',
    difficulty: 'medium',
    tags: ['Chuỗi', 'Mô phỏng'],
    acceptanceRate: 45,
    xp: 30,
    starterCode: 's = input()\nnumRows = int(input())\n# Chuyển đổi zigzag\n',
    testCases: [
      { input: 'PAYPALISHIRING\n3', expectedOutput: 'PAHNAPLSIIGYIR', isHidden: false },
      { input: 'PAYPALISHIRING\n4', expectedOutput: 'PINALSIGYAHRPI', isHidden: false },
      { input: 'AB\n1', expectedOutput: 'AB', isHidden: true },
    ],
    hints: [
      'Tạo numRows chuỗi rỗng, phân phối ký tự theo pattern zigzag.',
      'Di chuyển xuống rồi lên (đổi hướng khi chạm biên).',
    ],
    editorial: {
      approach: 'Mô phỏng: tạo mảng hàng, duyệt chuỗi và phân phối ký tự theo hướng lên/xuống.',
      code: 's = input()\nnumRows = int(input())\nif numRows == 1 or numRows >= len(s):\n    print(s)\nelse:\n    rows = [""] * numRows\n    cur_row = 0\n    going_down = False\n    for c in s:\n        rows[cur_row] += c\n        if cur_row == 0 or cur_row == numRows - 1:\n            going_down = not going_down\n        cur_row += 1 if going_down else -1\n    print("".join(rows))',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 273,
    slug: 'string-multiplication',
    title: 'Nhân Hai Số Lớn (Chuỗi)',
    description: 'Cho hai số nguyên không âm rất lớn dưới dạng chuỗi (có thể lên đến 200 chữ số). Tính tích của chúng và in kết quả dưới dạng chuỗi. Không được dùng kiểu số lớn có sẵn.',
    difficulty: 'medium',
    tags: ['Chuỗi', 'Toán'],
    acceptanceRate: 38,
    xp: 40,
    starterCode: 'num1 = input()\nnum2 = input()\n# Nhân hai số lớn dạng chuỗi\n',
    testCases: [
      { input: '123\n456', expectedOutput: '56088', isHidden: false },
      { input: '999\n999', expectedOutput: '998001', isHidden: false },
      { input: '0\n12345', expectedOutput: '0', isHidden: true },
    ],
    hints: [
      'Mô phỏng phép nhân tay: nhân từng chữ số rồi cộng dồn vào vị trí tương ứng.',
      'Kết quả tại vị trí [i+j] và [i+j+1] khi nhân num1[i] × num2[j].',
    ],
    editorial: {
      approach: 'Nhân từng cặp chữ số, cộng dồn vào mảng kết quả, xử lý nhớ.',
      code: 'num1 = input()\nnum2 = input()\nif num1 == "0" or num2 == "0":\n    print("0")\nelse:\n    m, n = len(num1), len(num2)\n    result = [0] * (m + n)\n    for i in range(m - 1, -1, -1):\n        for j in range(n - 1, -1, -1):\n            mul = int(num1[i]) * int(num2[j])\n            p1, p2 = i + j, i + j + 1\n            total = mul + result[p2]\n            result[p2] = total % 10\n            result[p1] += total // 10\n    res = "".join(map(str, result)).lstrip("0")\n    print(res if res else "0")',
      complexity: 'Time: O(m×n), Space: O(m+n)',
    },
  },
  {
    id: 274,
    slug: 'pow-x-n',
    title: 'Tính x Mũ n (Nhanh)',
    description: 'Cho số thực x và số nguyên n (có thể âm). Tính x^n bằng thuật toán lũy thừa nhanh (binary exponentiation). In kết quả làm tròn 5 chữ số thập phân. Không dùng hàm pow() có sẵn.',
    difficulty: 'medium',
    tags: ['Toán', 'Chia để trị'],
    acceptanceRate: 50,
    xp: 30,
    starterCode: 'x = float(input())\nn = int(input())\n# Tính x^n bằng lũy thừa nhanh\n',
    testCases: [
      { input: '2.0\n10', expectedOutput: '1024.00000', isHidden: false },
      { input: '2.0\n-2', expectedOutput: '0.25000', isHidden: false },
      { input: '0.5\n3', expectedOutput: '0.12500', isHidden: true },
    ],
    hints: [
      'Lũy thừa nhanh: x^n = (x^(n/2))^2 nếu n chẵn, x × x^(n-1) nếu n lẻ.',
      'Nếu n < 0, tính x^(-n) rồi lấy nghịch đảo.',
    ],
    editorial: {
      approach: 'Binary exponentiation: chia n cho 2 mỗi bước, nhân kết quả khi bit = 1.',
      code: 'x = float(input())\nn = int(input())\ndef fast_pow(base, exp):\n    if exp < 0:\n        base = 1 / base\n        exp = -exp\n    result = 1.0\n    while exp > 0:\n        if exp % 2 == 1:\n            result *= base\n        base *= base\n        exp //= 2\n    return result\nprint(f"{fast_pow(x, n):.5f}")',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 275,
    slug: 'sqrt-without-lib',
    title: 'Tính Căn Bậc Hai Không Dùng Thư Viện',
    description: 'Cho số nguyên không âm n. Tính phần nguyên của căn bậc hai (floor(sqrt(n))) mà không dùng hàm sqrt hay toán tử **. Dùng phương pháp tìm kiếm nhị phân.',
    difficulty: 'medium',
    tags: ['Tìm kiếm', 'Toán'],
    acceptanceRate: 55,
    xp: 30,
    starterCode: 'n = int(input())\n# Tính floor(sqrt(n)) bằng binary search\n',
    testCases: [
      { input: '16', expectedOutput: '4', isHidden: false },
      { input: '8', expectedOutput: '2', isHidden: false },
      { input: '2147483647', expectedOutput: '46340', isHidden: true },
    ],
    hints: [
      'Binary search trong khoảng [0, n]: tìm số lớn nhất mid sao cho mid*mid <= n.',
      'Cẩn thận overflow khi tính mid*mid với số lớn.',
    ],
    editorial: {
      approach: 'Binary search: tìm giá trị lớn nhất x sao cho x² ≤ n.',
      code: 'n = int(input())\nif n == 0:\n    print(0)\nelse:\n    lo, hi = 1, n\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if mid * mid == n:\n            print(mid)\n            break\n        elif mid * mid < n:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    else:\n        print(hi)',
      complexity: 'Time: O(log n), Space: O(1)',
    },
  },
  {
    id: 276,
    slug: 'jump-game',
    title: 'Jump Game - Có Thể Nhảy Đến Cuối?',
    description: 'Cho mảng n số nguyên không âm, mỗi phần tử biểu thị số bước nhảy tối đa từ vị trí đó. Bắt đầu từ vị trí 0, xác định xem có thể nhảy đến vị trí cuối cùng không. In "YES" hoặc "NO".',
    difficulty: 'medium',
    tags: ['Tham lam', 'Mảng'],
    acceptanceRate: 52,
    xp: 30,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Kiểm tra có thể nhảy đến cuối\n',
    testCases: [
      { input: '5\n2 3 1 1 4', expectedOutput: 'YES', isHidden: false },
      { input: '5\n3 2 1 0 4', expectedOutput: 'NO', isHidden: false },
      { input: '1\n0', expectedOutput: 'YES', isHidden: true },
    ],
    hints: [
      'Duy trì biến max_reach: vị trí xa nhất có thể đến được.',
      'Duyệt từ trái sang phải, cập nhật max_reach = max(max_reach, i + arr[i]).',
      'Nếu tại vị trí i mà i > max_reach thì không thể đi tiếp.',
    ],
    editorial: {
      approach: 'Greedy: duy trì vị trí xa nhất có thể đến, dừng nếu vị trí hiện tại vượt quá max_reach.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nmax_reach = 0\nfor i in range(n):\n    if i > max_reach:\n        print("NO")\n        break\n    max_reach = max(max_reach, i + arr[i])\nelse:\n    print("YES")',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 277,
    slug: 'gas-station',
    title: 'Trạm Xăng - Đi Vòng Tròn',
    description: 'Có n trạm xăng trên đường tròn. Trạm i có gas[i] lít xăng và chi phí đi đến trạm tiếp theo là cost[i] lít. Xe bắt đầu với bình rỗng. Tìm trạm xuất phát để đi được trọn vòng. In chỉ số trạm (0-indexed). Nếu không thể, in -1. Đảm bảo nếu có đáp án thì duy nhất.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Mảng'],
    acceptanceRate: 45,
    xp: 35,
    starterCode: 'n = int(input())\ngas = list(map(int, input().split()))\ncost = list(map(int, input().split()))\n# Tìm trạm xuất phát\n',
    testCases: [
      { input: '5\n1 2 3 4 5\n3 4 5 1 2', expectedOutput: '3', isHidden: false },
      { input: '3\n2 3 4\n3 4 3', expectedOutput: '-1', isHidden: false },
      { input: '4\n5 1 2 3\n4 4 1 5', expectedOutput: '0', isHidden: true },
    ],
    hints: [
      'Nếu tổng gas < tổng cost thì không có đáp án.',
      'Duyệt một lượt: nếu tank < 0 tại vị trí i, thì trạm xuất phát phải sau i.',
    ],
    editorial: {
      approach: 'Greedy: nếu tổng gas >= tổng cost thì có đáp án. Tìm bằng cách reset khi tank < 0.',
      code: 'n = int(input())\ngas = list(map(int, input().split()))\ncost = list(map(int, input().split()))\nif sum(gas) < sum(cost):\n    print(-1)\nelse:\n    start = 0\n    tank = 0\n    for i in range(n):\n        tank += gas[i] - cost[i]\n        if tank < 0:\n            start = i + 1\n            tank = 0\n    print(start)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 278,
    slug: 'task-scheduler',
    title: 'Lập Lịch CPU - Thời Gian Tối Thiểu',
    description: 'Cho danh sách n tác vụ (ký tự A-Z) và thời gian chờ cooldown k. Cùng một tác vụ phải cách nhau ít nhất k đơn vị thời gian. Mỗi tác vụ mất 1 đơn vị. CPU có thể idle. Tìm thời gian tối thiểu để hoàn thành tất cả tác vụ.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Hash Map'],
    acceptanceRate: 42,
    xp: 40,
    starterCode: 'tasks = input().split()\nk = int(input())\n# Tìm thời gian tối thiểu\n',
    testCases: [
      { input: 'A A A B B B\n2', expectedOutput: '8', isHidden: false },
      { input: 'A A A B B B\n0', expectedOutput: '6', isHidden: false },
      { input: 'A A A A B B C C\n2', expectedOutput: '10', isHidden: true },
    ],
    hints: [
      'Tác vụ xuất hiện nhiều nhất quyết định thời gian tối thiểu.',
      'Công thức: (max_freq - 1) × (k + 1) + count_of_max_freq.',
      'Kết quả = max(công thức trên, tổng số tác vụ).',
    ],
    editorial: {
      approach: 'Đếm tần suất, tính theo công thức dựa trên tác vụ có tần suất cao nhất.',
      code: 'from collections import Counter\ntasks = input().split()\nk = int(input())\nfreq = Counter(tasks)\nmax_f = max(freq.values())\ncount_max = sum(1 for v in freq.values() if v == max_f)\nresult = max(len(tasks), (max_f - 1) * (k + 1) + count_max)\nprint(result)',
      complexity: 'Time: O(n), Space: O(1) (tối đa 26 ký tự)',
    },
  },
  {
    id: 279,
    slug: 'meeting-rooms-min',
    title: 'Phòng Họp - Số Phòng Tối Thiểu',
    description: 'Cho n cuộc họp với thời gian bắt đầu và kết thúc. Tìm số phòng họp tối thiểu cần thiết để tất cả cuộc họp đều diễn ra (các cuộc họp chồng thời gian cần phòng riêng).',
    difficulty: 'medium',
    tags: ['Sắp xếp', 'Tham lam'],
    acceptanceRate: 48,
    xp: 35,
    starterCode: 'n = int(input())\n# Mỗi dòng: start end\n# Tìm số phòng họp tối thiểu\n',
    testCases: [
      { input: '3\n0 30\n5 10\n15 20', expectedOutput: '2', isHidden: false },
      { input: '2\n7 10\n2 4', expectedOutput: '1', isHidden: false },
      { input: '4\n1 5\n2 6\n3 7\n4 8', expectedOutput: '4', isHidden: true },
    ],
    hints: [
      'Tách thời gian bắt đầu và kết thúc thành 2 mảng riêng, sắp xếp.',
      'Dùng 2 con trỏ: khi start < end thì cần thêm phòng, ngược lại giải phóng phòng.',
    ],
    editorial: {
      approach: 'Tách events: +1 khi bắt đầu, -1 khi kết thúc. Sắp xếp và tìm max overlap.',
      code: 'n = int(input())\nevents = []\nfor _ in range(n):\n    s, e = map(int, input().split())\n    events.append((s, 1))\n    events.append((e, -1))\nevents.sort()\nrooms = max_rooms = 0\nfor _, typ in events:\n    rooms += typ\n    max_rooms = max(max_rooms, rooms)\nprint(max_rooms)',
      complexity: 'Time: O(n log n), Space: O(n)',
    },
  },
  {
    id: 280,
    slug: 'interval-merge-advanced',
    title: 'Gộp Khoảng Nâng Cao',
    description: 'Cho n khoảng [start, end]. Gộp tất cả khoảng chồng lấn. In số khoảng sau khi gộp trên dòng đầu, sau đó in từng khoảng (start end) trên mỗi dòng, sắp xếp theo start tăng dần.',
    difficulty: 'medium',
    tags: ['Sắp xếp', 'Mảng'],
    acceptanceRate: 50,
    xp: 30,
    starterCode: 'n = int(input())\n# Mỗi dòng: start end\n# Gộp khoảng chồng lấn\n',
    testCases: [
      { input: '4\n1 3\n2 6\n8 10\n15 18', expectedOutput: '3\n1 6\n8 10\n15 18', isHidden: false },
      { input: '2\n1 4\n4 5', expectedOutput: '1\n1 5', isHidden: false },
      { input: '3\n1 10\n2 3\n4 5', expectedOutput: '1\n1 10', isHidden: true },
    ],
    hints: [
      'Sắp xếp khoảng theo start.',
      'Duyệt: nếu khoảng hiện tại chồng với khoảng trước (start <= prev_end), gộp lại.',
    ],
    editorial: {
      approach: 'Sắp xếp theo start, duyệt và gộp khoảng chồng lấn.',
      code: 'n = int(input())\nintervals = []\nfor _ in range(n):\n    s, e = map(int, input().split())\n    intervals.append((s, e))\nintervals.sort()\nmerged = [intervals[0]]\nfor s, e in intervals[1:]:\n    if s <= merged[-1][1]:\n        merged[-1] = (merged[-1][0], max(merged[-1][1], e))\n    else:\n        merged.append((s, e))\nprint(len(merged))\nfor s, e in merged:\n    print(s, e)',
      complexity: 'Time: O(n log n), Space: O(n)',
    },
  },
  {
    id: 281,
    slug: 'longest-valid-parentheses',
    title: 'Dãy Ngoặc Hợp Lệ Dài Nhất',
    description: 'Cho chuỗi chỉ gồm ký tự "(" và ")". Tìm độ dài dãy ngoặc hợp lệ liên tiếp dài nhất.',
    difficulty: 'medium',
    tags: ['Stack', 'Chuỗi'],
    acceptanceRate: 38,
    xp: 40,
    starterCode: 's = input()\n# Tìm dãy ngoặc hợp lệ dài nhất\n',
    testCases: [
      { input: '(()', expectedOutput: '2', isHidden: false },
      { input: ')()())', expectedOutput: '4', isHidden: false },
      { input: '()(())', expectedOutput: '6', isHidden: true },
    ],
    hints: [
      'Dùng stack lưu chỉ số. Push chỉ số của "(" vào stack.',
      'Khi gặp ")", pop stack. Nếu stack rỗng, push chỉ số hiện tại làm mốc mới.',
      'Độ dài = chỉ số hiện tại - đỉnh stack.',
    ],
    editorial: {
      approach: 'Dùng stack lưu chỉ số, tính độ dài dãy hợp lệ khi pop thành công.',
      code: 's = input()\nstack = [-1]\nmax_len = 0\nfor i, c in enumerate(s):\n    if c == "(":\n        stack.append(i)\n    else:\n        stack.pop()\n        if not stack:\n            stack.append(i)\n        else:\n            max_len = max(max_len, i - stack[-1])\nprint(max_len)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 282,
    slug: 'trapping-rain-water-simple',
    title: 'Hứng Nước Mưa (Đơn Giản)',
    description: 'Cho mảng n số nguyên không âm biểu thị chiều cao các cột. Tính tổng lượng nước có thể hứng được giữa các cột sau khi mưa.',
    difficulty: 'medium',
    tags: ['Mảng', 'Two Pointers'],
    acceptanceRate: 40,
    xp: 40,
    starterCode: 'n = int(input())\nheight = list(map(int, input().split()))\n# Tính lượng nước hứng được\n',
    testCases: [
      { input: '6\n0 1 0 2 1 0', expectedOutput: '1', isHidden: false },
      { input: '12\n0 1 0 2 1 0 1 3 2 1 2 1', expectedOutput: '6', isHidden: false },
      { input: '3\n3 0 3', expectedOutput: '3', isHidden: true },
    ],
    hints: [
      'Nước tại vị trí i = min(max_left, max_right) - height[i].',
      'Tính trước mảng max_left và max_right.',
      'Hoặc dùng two pointers để tối ưu không gian.',
    ],
    editorial: {
      approach: 'Prefix max: tính max bên trái và max bên phải cho mỗi vị trí, nước = min(left, right) - height.',
      code: 'n = int(input())\nheight = list(map(int, input().split()))\nif n < 3:\n    print(0)\nelse:\n    left_max = [0] * n\n    right_max = [0] * n\n    left_max[0] = height[0]\n    for i in range(1, n):\n        left_max[i] = max(left_max[i-1], height[i])\n    right_max[n-1] = height[n-1]\n    for i in range(n-2, -1, -1):\n        right_max[i] = max(right_max[i+1], height[i])\n    water = sum(min(left_max[i], right_max[i]) - height[i] for i in range(n))\n    print(water)',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 283,
    slug: 'stock-buy-sell-multiple',
    title: 'Mua Bán Cổ Phiếu - Nhiều Giao Dịch',
    description: 'Cho mảng giá cổ phiếu n ngày. Bạn có thể mua và bán nhiều lần (nhưng phải bán trước khi mua lại). Tìm lợi nhuận tối đa có thể đạt được.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Mảng'],
    acceptanceRate: 58,
    xp: 25,
    starterCode: 'n = int(input())\nprices = list(map(int, input().split()))\n# Tìm lợi nhuận tối đa\n',
    testCases: [
      { input: '6\n7 1 5 3 6 4', expectedOutput: '7', isHidden: false },
      { input: '5\n1 2 3 4 5', expectedOutput: '4', isHidden: false },
      { input: '5\n7 6 4 3 1', expectedOutput: '0', isHidden: true },
    ],
    hints: [
      'Greedy: cộng tất cả các đoạn tăng liên tiếp.',
      'Nếu prices[i] > prices[i-1], cộng hiệu vào lợi nhuận.',
    ],
    editorial: {
      approach: 'Greedy: cộng tất cả chênh lệch dương liên tiếp.',
      code: 'n = int(input())\nprices = list(map(int, input().split()))\nprofit = 0\nfor i in range(1, n):\n    if prices[i] > prices[i-1]:\n        profit += prices[i] - prices[i-1]\nprint(profit)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 284,
    slug: 'partition-labels',
    title: 'Chia Chuỗi Thành Nhiều Phần',
    description: 'Cho chuỗi s chỉ gồm chữ cái thường. Chia chuỗi thành nhiều phần nhất có thể sao cho mỗi ký tự chỉ xuất hiện trong đúng một phần. In độ dài các phần, cách nhau bởi dấu cách.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Chuỗi'],
    acceptanceRate: 52,
    xp: 30,
    starterCode: 's = input()\n# Chia chuỗi thành nhiều phần nhất\n',
    testCases: [
      { input: 'ababcbacadefegdehijhklij', expectedOutput: '9 7 8', isHidden: false },
      { input: 'eccbbbbdec', expectedOutput: '10', isHidden: false },
      { input: 'abcabc', expectedOutput: '6', isHidden: true },
    ],
    hints: [
      'Tìm vị trí xuất hiện cuối cùng của mỗi ký tự.',
      'Duyệt chuỗi, mở rộng phần hiện tại đến vị trí cuối cùng của ký tự gặp.',
      'Khi chỉ số hiện tại = biên phải của phần, cắt phần đó.',
    ],
    editorial: {
      approach: 'Ghi nhận last occurrence, duyệt và mở rộng partition cho đến khi i == end.',
      code: 's = input()\nlast = {c: i for i, c in enumerate(s)}\nparts = []\nstart = end = 0\nfor i, c in enumerate(s):\n    end = max(end, last[c])\n    if i == end:\n        parts.append(end - start + 1)\n        start = i + 1\nprint(" ".join(map(str, parts)))',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  {
    id: 285,
    slug: 'minimum-jumps',
    title: 'Số Bước Nhảy Tối Thiểu',
    description: 'Cho mảng n số nguyên không âm, mỗi phần tử biểu thị số bước nhảy tối đa từ vị trí đó. Tìm số bước nhảy tối thiểu để đi từ vị trí 0 đến vị trí cuối. Đảm bảo luôn có cách đi đến cuối.',
    difficulty: 'medium',
    tags: ['Tham lam', 'Mảng'],
    acceptanceRate: 45,
    xp: 35,
    starterCode: 'n = int(input())\narr = list(map(int, input().split()))\n# Tìm số bước nhảy tối thiểu\n',
    testCases: [
      { input: '5\n2 3 1 1 4', expectedOutput: '2', isHidden: false },
      { input: '6\n2 3 0 1 4 1', expectedOutput: '2', isHidden: false },
      { input: '1\n0', expectedOutput: '0', isHidden: true },
    ],
    hints: [
      'Greedy: tại mỗi bước, chọn vị trí tiếp theo cho phép nhảy xa nhất.',
      'Duy trì biến: jumps, current_end, farthest.',
    ],
    editorial: {
      approach: 'BFS/Greedy: mỗi "level" là một bước nhảy, tìm farthest reach trong level hiện tại.',
      code: 'n = int(input())\narr = list(map(int, input().split()))\nif n <= 1:\n    print(0)\nelse:\n    jumps = 0\n    cur_end = 0\n    farthest = 0\n    for i in range(n - 1):\n        farthest = max(farthest, i + arr[i])\n        if i == cur_end:\n            jumps += 1\n            cur_end = farthest\n            if cur_end >= n - 1:\n                break\n    print(jumps)',
      complexity: 'Time: O(n), Space: O(1)',
    },
  },
  // ==================== HARD: UNIVERSITY PREP (286-300) ====================
  {
    id: 286,
    slug: 'lru-cache-simplified',
    title: 'LRU Cache Đơn Giản',
    description: 'Thiết kế LRU Cache với dung lượng capacity. Hỗ trợ 2 thao tác:\n- GET key: trả về value nếu key tồn tại, ngược lại trả về -1\n- PUT key value: thêm/cập nhật cặp key-value. Nếu đầy, xóa phần tử ít được dùng gần đây nhất.\nDòng đầu: capacity và số thao tác q. Mỗi dòng tiếp theo là một thao tác. In kết quả mỗi GET trên một dòng.',
    difficulty: 'hard',
    tags: ['Hash Map', 'Thiết kế'],
    acceptanceRate: 35,
    xp: 50,
    starterCode: 'capacity, q = map(int, input().split())\n# Thiết kế LRU Cache\n',
    testCases: [
      { input: '2 6\nPUT 1 10\nPUT 2 20\nGET 1\nPUT 3 30\nGET 2\nGET 3', expectedOutput: '10\n-1\n30', isHidden: false },
      { input: '1 4\nPUT 1 1\nPUT 2 2\nGET 1\nGET 2', expectedOutput: '-1\n2', isHidden: false },
      { input: '2 5\nPUT 1 1\nGET 1\nPUT 2 2\nPUT 3 3\nGET 1', expectedOutput: '1\n-1', isHidden: true },
    ],
    hints: [
      'Dùng OrderedDict hoặc kết hợp dict + doubly linked list.',
      'GET cũng cập nhật thứ tự sử dụng (move to end).',
      'Khi PUT đầy, xóa phần tử đầu tiên (least recently used).',
    ],
    editorial: {
      approach: 'Dùng OrderedDict: GET move_to_end, PUT thêm cuối và popitem(last=False) khi đầy.',
      code: 'from collections import OrderedDict\ncapacity, q = map(int, input().split())\ncache = OrderedDict()\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "GET":\n        key = int(parts[1])\n        if key in cache:\n            cache.move_to_end(key)\n            print(cache[key])\n        else:\n            print(-1)\n    else:\n        key, val = int(parts[1]), int(parts[2])\n        if key in cache:\n            cache.move_to_end(key)\n        cache[key] = val\n        if len(cache) > capacity:\n            cache.popitem(last=False)',
      complexity: 'Time: O(1) per operation, Space: O(capacity)',
    },
  },
  {
    id: 287,
    slug: 'implement-trie',
    title: 'Cài Đặt Trie (Cây Tiền Tố)',
    description: 'Cài đặt cấu trúc dữ liệu Trie hỗ trợ 3 thao tác:\n- INSERT word: thêm từ vào trie\n- SEARCH word: kiểm tra từ có tồn tại trong trie không (YES/NO)\n- PREFIX prefix: kiểm tra có từ nào bắt đầu bằng prefix không (YES/NO)\nDòng đầu: số thao tác q. In kết quả SEARCH và PREFIX.',
    difficulty: 'hard',
    tags: ['Trie', 'Thiết kế'],
    acceptanceRate: 40,
    xp: 50,
    starterCode: 'q = int(input())\n# Cài đặt Trie\n',
    testCases: [
      { input: '5\nINSERT apple\nSEARCH apple\nSEARCH app\nPREFIX app\nINSERT app', expectedOutput: 'YES\nNO\nYES', isHidden: false },
      { input: '4\nINSERT hello\nINSERT help\nSEARCH hel\nPREFIX hel', expectedOutput: 'NO\nYES', isHidden: false },
      { input: '3\nSEARCH abc\nINSERT abc\nSEARCH abc', expectedOutput: 'NO\nYES', isHidden: true },
    ],
    hints: [
      'Mỗi node trong Trie có dict children và flag is_end.',
      'INSERT: duyệt từng ký tự, tạo node mới nếu chưa có.',
      'SEARCH: duyệt đến cuối từ, kiểm tra is_end. PREFIX: chỉ cần duyệt được hết prefix.',
    ],
    editorial: {
      approach: 'Cài đặt Trie bằng dict lồng nhau, mỗi node có children và is_end flag.',
      code: 'class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n\nroot = TrieNode()\n\ndef insert(word):\n    node = root\n    for c in word:\n        if c not in node.children:\n            node.children[c] = TrieNode()\n        node = node.children[c]\n    node.is_end = True\n\ndef search(word):\n    node = root\n    for c in word:\n        if c not in node.children:\n            return False\n        node = node.children[c]\n    return node.is_end\n\ndef starts_with(prefix):\n    node = root\n    for c in prefix:\n        if c not in node.children:\n            return False\n        node = node.children[c]\n    return True\n\nq = int(input())\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "INSERT":\n        insert(parts[1])\n    elif parts[0] == "SEARCH":\n        print("YES" if search(parts[1]) else "NO")\n    else:\n        print("YES" if starts_with(parts[1]) else "NO")',
      complexity: 'Time: O(L) per operation (L = word length), Space: O(N×L)',
    },
  },
  {
    id: 288,
    slug: 'regex-basic-match',
    title: 'Regex Cơ Bản - Pattern Matching',
    description: 'Cài đặt regex matching đơn giản hỗ trợ "." (match 1 ký tự bất kỳ) và "*" (match 0 hoặc nhiều ký tự trước đó). Pattern phải match toàn bộ chuỗi.\nDòng 1: chuỗi s. Dòng 2: pattern p. In "YES" nếu match, "NO" nếu không.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Chuỗi'],
    acceptanceRate: 28,
    xp: 60,
    starterCode: 's = input()\np = input()\n# Regex matching với . và *\n',
    testCases: [
      { input: 'aa\na', expectedOutput: 'NO', isHidden: false },
      { input: 'aa\na*', expectedOutput: 'YES', isHidden: false },
      { input: 'aab\nc*a*b', expectedOutput: 'YES', isHidden: true },
      { input: 'mississippi\nmis*is*p*.', expectedOutput: 'NO', isHidden: true },
    ],
    hints: [
      'Dùng DP 2D: dp[i][j] = s[0..i-1] match p[0..j-1].',
      'Nếu p[j-1] == "*": dp[i][j] = dp[i][j-2] (0 lần) hoặc dp[i-1][j] (nhiều lần, nếu ký tự match).',
      'Nếu p[j-1] == "." hoặc p[j-1] == s[i-1]: dp[i][j] = dp[i-1][j-1].',
    ],
    editorial: {
      approach: 'DP 2D: xây bảng dp[i][j] biểu thị s[:i] có match p[:j] không.',
      code: 's = input()\np = input()\nm, n = len(s), len(p)\ndp = [[False] * (n + 1) for _ in range(m + 1)]\ndp[0][0] = True\nfor j in range(1, n + 1):\n    if p[j-1] == "*":\n        dp[0][j] = dp[0][j-2]\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if p[j-1] == "*":\n            dp[i][j] = dp[i][j-2]\n            if p[j-2] == "." or p[j-2] == s[i-1]:\n                dp[i][j] = dp[i][j] or dp[i-1][j]\n        elif p[j-1] == "." or p[j-1] == s[i-1]:\n            dp[i][j] = dp[i-1][j-1]\nprint("YES" if dp[m][n] else "NO")',
      complexity: 'Time: O(m×n), Space: O(m×n)',
    },
  },
  {
    id: 289,
    slug: 'serialize-deserialize-tree',
    title: 'Serialize/Deserialize Cây Nhị Phân',
    description: 'Cho cây nhị phân biểu diễn bằng level-order (BFS), dùng "null" cho node rỗng. Thực hiện:\n- Dòng 1: "SERIALIZE" hoặc "DESERIALIZE"\n- Nếu SERIALIZE: dòng 2 là cây dạng preorder (giá trị cách nhau bởi dấu cách, "N" cho null). In ra dạng level-order.\n- Nếu DESERIALIZE: dòng 2 là cây dạng level-order. In ra dạng preorder.\nBỏ các null ở cuối khi in level-order.',
    difficulty: 'hard',
    tags: ['Cây', 'BFS'],
    acceptanceRate: 32,
    xp: 50,
    starterCode: 'command = input()\ndata = input().split()\n# Serialize/Deserialize cây nhị phân\n',
    testCases: [
      { input: 'DESERIALIZE\n1 2 3 N N 4 5', expectedOutput: '1 2 N N 3 4 N N 5 N N', isHidden: false },
      { input: 'SERIALIZE\n1 2 N N 3 N N', expectedOutput: '1 2 3', isHidden: false },
      { input: 'DESERIALIZE\n1 N 2 N 3', expectedOutput: '1 N 2 N 3 N N', isHidden: true },
    ],
    hints: [
      'Dùng queue (BFS) để xây dựng cây từ level-order.',
      'Preorder: root → left → right (đệ quy).',
      'Serialize: từ preorder xây cây rồi BFS ra level-order.',
    ],
    editorial: {
      approach: 'Xây cây từ input format, rồi traverse theo output format.',
      code: 'from collections import deque\n\nclass Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = self.right = None\n\ndef build_from_level(data):\n    if not data or data[0] == "N": return None\n    root = Node(data[0])\n    q = deque([root])\n    i = 1\n    while q and i < len(data):\n        node = q.popleft()\n        if i < len(data) and data[i] != "N":\n            node.left = Node(data[i])\n            q.append(node.left)\n        i += 1\n        if i < len(data) and data[i] != "N":\n            node.right = Node(data[i])\n            q.append(node.right)\n        i += 1\n    return root\n\ndef preorder(node, res):\n    if not node:\n        res.append("N")\n        return\n    res.append(node.val)\n    preorder(node.left, res)\n    preorder(node.right, res)\n\ndef build_from_preorder(data):\n    it = iter(data)\n    def helper():\n        val = next(it)\n        if val == "N": return None\n        node = Node(val)\n        node.left = helper()\n        node.right = helper()\n        return node\n    return helper()\n\ndef level_order(root):\n    if not root: return []\n    res = []\n    q = deque([root])\n    while q:\n        node = q.popleft()\n        if node:\n            res.append(node.val)\n            q.append(node.left)\n            q.append(node.right)\n        else:\n            res.append("N")\n    while res and res[-1] == "N": res.pop()\n    return res\n\ncommand = input()\ndata = input().split()\nif command == "DESERIALIZE":\n    tree = build_from_level(data)\n    res = []\n    preorder(tree, res)\n    print(" ".join(res))\nelse:\n    tree = build_from_preorder(data)\n    res = level_order(tree)\n    print(" ".join(res))',
      complexity: 'Time: O(n), Space: O(n)',
    },
  },
  {
    id: 290,
    slug: 'design-hashmap',
    title: 'Thiết Kế HashMap',
    description: 'Thiết kế HashMap không dùng thư viện hash có sẵn. Hỗ trợ:\n- PUT key value: thêm/cập nhật\n- GET key: trả về value hoặc -1\n- REMOVE key: xóa key\nKey và value là số nguyên (0 ≤ key ≤ 10^6). Dòng đầu: số thao tác q. In kết quả mỗi GET.',
    difficulty: 'hard',
    tags: ['Hash Map', 'Thiết kế'],
    acceptanceRate: 42,
    xp: 45,
    starterCode: 'q = int(input())\n# Thiết kế HashMap\n',
    testCases: [
      { input: '5\nPUT 1 100\nPUT 2 200\nGET 1\nREMOVE 1\nGET 1', expectedOutput: '100\n-1', isHidden: false },
      { input: '4\nGET 5\nPUT 5 50\nGET 5\nPUT 5 99', expectedOutput: '-1\n50', isHidden: false },
      { input: '3\nPUT 1000000 1\nGET 1000000\nGET 999999', expectedOutput: '1\n-1', isHidden: true },
    ],
    hints: [
      'Dùng mảng bucket với hàm hash đơn giản (key % size).',
      'Mỗi bucket là linked list để xử lý collision.',
      'Chọn size là số nguyên tố (ví dụ 1009) để giảm collision.',
    ],
    editorial: {
      approach: 'Chaining: mảng bucket, mỗi bucket là list các cặp (key, value).',
      code: 'class MyHashMap:\n    def __init__(self):\n        self.size = 1009\n        self.buckets = [[] for _ in range(self.size)]\n    def _hash(self, key):\n        return key % self.size\n    def put(self, key, val):\n        h = self._hash(key)\n        for i, (k, v) in enumerate(self.buckets[h]):\n            if k == key:\n                self.buckets[h][i] = (key, val)\n                return\n        self.buckets[h].append((key, val))\n    def get(self, key):\n        h = self._hash(key)\n        for k, v in self.buckets[h]:\n            if k == key: return v\n        return -1\n    def remove(self, key):\n        h = self._hash(key)\n        self.buckets[h] = [(k,v) for k,v in self.buckets[h] if k != key]\n\nhm = MyHashMap()\nq = int(input())\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "PUT":\n        hm.put(int(parts[1]), int(parts[2]))\n    elif parts[0] == "GET":\n        print(hm.get(int(parts[1])))\n    else:\n        hm.remove(int(parts[1]))',
      complexity: 'Time: O(n/k) average per operation, Space: O(n)',
    },
  },
  {
    id: 291,
    slug: 'stack-with-max',
    title: 'Stack Hỗ Trợ Tìm Max O(1)',
    description: 'Cài đặt Stack hỗ trợ các thao tác trong O(1):\n- PUSH x: đẩy x vào stack\n- POP: lấy phần tử trên cùng ra (in giá trị)\n- MAX: in giá trị lớn nhất hiện tại trong stack\nNếu POP hoặc MAX khi stack rỗng, in "EMPTY". Dòng đầu: số thao tác q.',
    difficulty: 'hard',
    tags: ['Stack', 'Thiết kế'],
    acceptanceRate: 45,
    xp: 45,
    starterCode: 'q = int(input())\n# Stack hỗ trợ tìm Max O(1)\n',
    testCases: [
      { input: '7\nPUSH 5\nPUSH 3\nPUSH 8\nMAX\nPOP\nMAX\nPOP', expectedOutput: '8\n8\n5\n5', isHidden: false },
      { input: '4\nMAX\nPUSH 10\nMAX\nPOP', expectedOutput: 'EMPTY\n10\n10', isHidden: false },
      { input: '5\nPUSH 1\nPUSH 2\nPOP\nPOP\nPOP', expectedOutput: '2\n1\nEMPTY', isHidden: true },
    ],
    hints: [
      'Dùng stack phụ lưu max tại mỗi thời điểm.',
      'Khi push x, push max(x, max_stack[-1]) vào max_stack.',
      'Khi pop, pop cả 2 stack.',
    ],
    editorial: {
      approach: 'Dùng 2 stack: stack chính và stack max song song.',
      code: 'q = int(input())\nstack = []\nmax_stack = []\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "PUSH":\n        x = int(parts[1])\n        stack.append(x)\n        max_stack.append(max(x, max_stack[-1] if max_stack else x))\n    elif parts[0] == "POP":\n        if not stack:\n            print("EMPTY")\n        else:\n            print(stack.pop())\n            max_stack.pop()\n    else:  # MAX\n        if not stack:\n            print("EMPTY")\n        else:\n            print(max_stack[-1])',
      complexity: 'Time: O(1) per operation, Space: O(n)',
    },
  },
  {
    id: 292,
    slug: 'circular-queue',
    title: 'Hàng Đợi Vòng (Circular Queue)',
    description: 'Cài đặt Circular Queue với kích thước cố định k. Hỗ trợ:\n- ENQUEUE x: thêm x vào cuối. In "SUCCESS" hoặc "FULL"\n- DEQUEUE: lấy phần tử đầu ra. In giá trị hoặc "EMPTY"\n- FRONT: in phần tử đầu hoặc "EMPTY"\n- SIZE: in số phần tử hiện tại\nDòng đầu: k và số thao tác q.',
    difficulty: 'hard',
    tags: ['Queue', 'Thiết kế'],
    acceptanceRate: 48,
    xp: 45,
    starterCode: 'k, q = map(int, input().split())\n# Cài đặt Circular Queue\n',
    testCases: [
      { input: '3 7\nENQUEUE 1\nENQUEUE 2\nENQUEUE 3\nENQUEUE 4\nDEQUEUE\nENQUEUE 4\nFRONT', expectedOutput: 'SUCCESS\nSUCCESS\nSUCCESS\nFULL\n1\nSUCCESS\n2', isHidden: false },
      { input: '2 4\nDEQUEUE\nENQUEUE 5\nSIZE\nFRONT', expectedOutput: 'EMPTY\nSUCCESS\n1\n5', isHidden: false },
      { input: '1 3\nENQUEUE 10\nENQUEUE 20\nDEQUEUE', expectedOutput: 'SUCCESS\nFULL\n10', isHidden: true },
    ],
    hints: [
      'Dùng mảng cố định kích thước k, 2 con trỏ head và tail.',
      'Dùng biến count để biết queue đầy hay rỗng.',
      'Cập nhật con trỏ: (pointer + 1) % k.',
    ],
    editorial: {
      approach: 'Mảng vòng với head, tail, count. Enqueue tại tail, dequeue tại head.',
      code: 'k, q = map(int, input().split())\nbuf = [0] * k\nhead = tail = count = 0\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "ENQUEUE":\n        if count == k:\n            print("FULL")\n        else:\n            buf[tail] = int(parts[1])\n            tail = (tail + 1) % k\n            count += 1\n            print("SUCCESS")\n    elif parts[0] == "DEQUEUE":\n        if count == 0:\n            print("EMPTY")\n        else:\n            print(buf[head])\n            head = (head + 1) % k\n            count -= 1\n    elif parts[0] == "FRONT":\n        print("EMPTY" if count == 0 else buf[head])\n    else:\n        print(count)',
      complexity: 'Time: O(1) per operation, Space: O(k)',
    },
  },
  {
    id: 293,
    slug: 'priority-queue-simulation',
    title: 'Mô Phỏng Priority Queue',
    description: 'Cài đặt Priority Queue (min-heap) hỗ trợ:\n- INSERT x: thêm x vào PQ\n- EXTRACT_MIN: lấy và in phần tử nhỏ nhất. In "EMPTY" nếu rỗng\n- PEEK: in phần tử nhỏ nhất mà không xóa. In "EMPTY" nếu rỗng\n- SIZE: in số phần tử\nDòng đầu: số thao tác q.',
    difficulty: 'hard',
    tags: ['Heap', 'Thiết kế'],
    acceptanceRate: 42,
    xp: 50,
    starterCode: 'q = int(input())\n# Mô phỏng Priority Queue (min-heap)\n',
    testCases: [
      { input: '7\nINSERT 5\nINSERT 3\nINSERT 8\nPEEK\nEXTRACT_MIN\nEXTRACT_MIN\nSIZE', expectedOutput: '3\n3\n5\n1', isHidden: false },
      { input: '4\nEXTRACT_MIN\nINSERT 1\nINSERT 2\nEXTRACT_MIN', expectedOutput: 'EMPTY\n1', isHidden: false },
      { input: '5\nINSERT 10\nINSERT 1\nINSERT 5\nEXTRACT_MIN\nPEEK', expectedOutput: '1\n5', isHidden: true },
    ],
    hints: [
      'Cài đặt heap bằng mảng: parent = (i-1)//2, children = 2i+1, 2i+2.',
      'INSERT: thêm cuối rồi sift_up.',
      'EXTRACT_MIN: swap root với cuối, pop, rồi sift_down.',
    ],
    editorial: {
      approach: 'Cài đặt min-heap thủ công với sift_up và sift_down.',
      code: 'class MinHeap:\n    def __init__(self):\n        self.heap = []\n    def insert(self, x):\n        self.heap.append(x)\n        i = len(self.heap) - 1\n        while i > 0:\n            parent = (i - 1) // 2\n            if self.heap[i] < self.heap[parent]:\n                self.heap[i], self.heap[parent] = self.heap[parent], self.heap[i]\n                i = parent\n            else: break\n    def extract_min(self):\n        if not self.heap: return None\n        val = self.heap[0]\n        self.heap[0] = self.heap[-1]\n        self.heap.pop()\n        i = 0\n        while True:\n            smallest = i\n            l, r = 2*i+1, 2*i+2\n            if l < len(self.heap) and self.heap[l] < self.heap[smallest]: smallest = l\n            if r < len(self.heap) and self.heap[r] < self.heap[smallest]: smallest = r\n            if smallest != i:\n                self.heap[i], self.heap[smallest] = self.heap[smallest], self.heap[i]\n                i = smallest\n            else: break\n        return val\n\npq = MinHeap()\nq = int(input())\nfor _ in range(q):\n    parts = input().split()\n    if parts[0] == "INSERT":\n        pq.insert(int(parts[1]))\n    elif parts[0] == "EXTRACT_MIN":\n        r = pq.extract_min()\n        print("EMPTY" if r is None else r)\n    elif parts[0] == "PEEK":\n        print("EMPTY" if not pq.heap else pq.heap[0])\n    else:\n        print(len(pq.heap))',
      complexity: 'Time: O(log n) insert/extract, O(1) peek, Space: O(n)',
    },
  },
  {
    id: 294,
    slug: 'topological-sort-advanced',
    title: 'Sắp Xếp Topo - Phát Hiện Chu Trình',
    description: 'Cho đồ thị có hướng n đỉnh, m cạnh. Thực hiện sắp xếp topo (topological sort). Nếu đồ thị có chu trình, in "CYCLE". Ngược lại in thứ tự topo (nếu nhiều đáp án, in thứ tự từ điển nhỏ nhất).',
    difficulty: 'hard',
    tags: ['Đồ thị', 'BFS'],
    acceptanceRate: 35,
    xp: 50,
    starterCode: 'n, m = map(int, input().split())\n# Mỗi dòng tiếp theo: u v (cạnh u → v)\n# Sắp xếp topo hoặc phát hiện chu trình\n',
    testCases: [
      { input: '4 4\n1 2\n1 3\n2 4\n3 4', expectedOutput: '1 2 3 4', isHidden: false },
      { input: '3 3\n1 2\n2 3\n3 1', expectedOutput: 'CYCLE', isHidden: false },
      { input: '5 4\n5 1\n4 2\n5 3\n4 3', expectedOutput: '4 5 1 2 3', isHidden: true },
    ],
    hints: [
      'Dùng thuật toán Kahn (BFS): bắt đầu từ đỉnh có in-degree = 0.',
      'Dùng min-heap thay vì queue để đảm bảo thứ tự từ điển nhỏ nhất.',
      'Nếu kết quả có ít hơn n đỉnh → có chu trình.',
    ],
    editorial: {
      approach: 'Kahn algorithm với min-heap để đảm bảo thứ tự từ điển.',
      code: 'import heapq\nn, m = map(int, input().split())\nadj = [[] for _ in range(n + 1)]\nin_deg = [0] * (n + 1)\nfor _ in range(m):\n    u, v = map(int, input().split())\n    adj[u].append(v)\n    in_deg[v] += 1\nheap = []\nfor i in range(1, n + 1):\n    if in_deg[i] == 0:\n        heapq.heappush(heap, i)\nresult = []\nwhile heap:\n    u = heapq.heappop(heap)\n    result.append(u)\n    for v in adj[u]:\n        in_deg[v] -= 1\n        if in_deg[v] == 0:\n            heapq.heappush(heap, v)\nif len(result) == n:\n    print(" ".join(map(str, result)))\nelse:\n    print("CYCLE")',
      complexity: 'Time: O((V+E) log V), Space: O(V+E)',
    },
  },
  {
    id: 295,
    slug: 'strongly-connected-simplified',
    title: 'Thành Phần Liên Thông Mạnh (Đơn Giản)',
    description: 'Cho đồ thị có hướng n đỉnh, m cạnh. Tìm số lượng thành phần liên thông mạnh (SCC). Hai đỉnh thuộc cùng SCC nếu có đường đi từ u đến v VÀ từ v đến u.',
    difficulty: 'hard',
    tags: ['Đồ thị', 'DFS'],
    acceptanceRate: 30,
    xp: 55,
    starterCode: 'n, m = map(int, input().split())\n# Mỗi dòng: u v (cạnh u → v)\n# Tìm số SCC\n',
    testCases: [
      { input: '5 5\n1 2\n2 3\n3 1\n3 4\n4 5', expectedOutput: '3', isHidden: false },
      { input: '4 4\n1 2\n2 3\n3 4\n4 1', expectedOutput: '1', isHidden: false },
      { input: '3 0', expectedOutput: '3', isHidden: true },
    ],
    hints: [
      'Dùng thuật toán Kosaraju: 2 lần DFS.',
      'Lần 1: DFS trên đồ thị gốc, ghi nhận thứ tự finish.',
      'Lần 2: DFS trên đồ thị đảo theo thứ tự finish giảm dần.',
    ],
    editorial: {
      approach: 'Kosaraju: DFS gốc lấy finish order, DFS đồ thị đảo theo reverse finish order.',
      code: 'import sys\nsys.setrecursionlimit(100000)\nn, m = map(int, input().split())\nadj = [[] for _ in range(n + 1)]\nradj = [[] for _ in range(n + 1)]\nfor _ in range(m):\n    u, v = map(int, input().split())\n    adj[u].append(v)\n    radj[v].append(u)\nvisited = [False] * (n + 1)\norder = []\ndef dfs1(u):\n    visited[u] = True\n    for v in adj[u]:\n        if not visited[v]: dfs1(v)\n    order.append(u)\nfor i in range(1, n + 1):\n    if not visited[i]: dfs1(i)\nvisited = [False] * (n + 1)\nscc_count = 0\ndef dfs2(u):\n    visited[u] = True\n    for v in radj[u]:\n        if not visited[v]: dfs2(v)\nfor u in reversed(order):\n    if not visited[u]:\n        dfs2(u)\n        scc_count += 1\nprint(scc_count)',
      complexity: 'Time: O(V+E), Space: O(V+E)',
    },
  },
  {
    id: 296,
    slug: 'segment-tree-query',
    title: 'Segment Tree - Truy Vấn Tổng Đoạn Có Cập Nhật',
    description: 'Cho mảng n số nguyên. Xử lý q truy vấn:\n- UPDATE i x: cập nhật arr[i] = x (1-indexed)\n- QUERY l r: in tổng arr[l..r] (1-indexed)\nDùng Segment Tree để đạt O(log n) mỗi thao tác.',
    difficulty: 'hard',
    tags: ['Segment Tree', 'Mảng'],
    acceptanceRate: 28,
    xp: 60,
    starterCode: 'n, q = map(int, input().split())\narr = list(map(int, input().split()))\n# Segment Tree - truy vấn tổng có cập nhật\n',
    testCases: [
      { input: '5 4\n1 2 3 4 5\nQUERY 1 3\nUPDATE 2 10\nQUERY 1 3\nQUERY 1 5', expectedOutput: '6\n14\n23', isHidden: false },
      { input: '3 3\n10 20 30\nQUERY 1 3\nUPDATE 1 0\nQUERY 1 3', expectedOutput: '60\n50', isHidden: false },
      { input: '4 2\n1 1 1 1\nUPDATE 3 5\nQUERY 2 4', expectedOutput: '7', isHidden: true },
    ],
    hints: [
      'Segment Tree: mảng kích thước 4n, build từ dưới lên.',
      'Update: cập nhật lá rồi propagate lên root.',
      'Query: chia đoạn [l,r] thành các đoạn con trong cây.',
    ],
    editorial: {
      approach: 'Cài đặt Segment Tree cơ bản với build, update point, query range.',
      code: 'n, q_count = map(int, input().split())\narr = list(map(int, input().split()))\ntree = [0] * (4 * n)\n\ndef build(node, start, end):\n    if start == end:\n        tree[node] = arr[start]\n        return\n    mid = (start + end) // 2\n    build(2*node, start, mid)\n    build(2*node+1, mid+1, end)\n    tree[node] = tree[2*node] + tree[2*node+1]\n\ndef update(node, start, end, idx, val):\n    if start == end:\n        tree[node] = val\n        arr[idx] = val\n        return\n    mid = (start + end) // 2\n    if idx <= mid:\n        update(2*node, start, mid, idx, val)\n    else:\n        update(2*node+1, mid+1, end, idx, val)\n    tree[node] = tree[2*node] + tree[2*node+1]\n\ndef query(node, start, end, l, r):\n    if r < start or end < l: return 0\n    if l <= start and end <= r: return tree[node]\n    mid = (start + end) // 2\n    return query(2*node, start, mid, l, r) + query(2*node+1, mid+1, end, l, r)\n\nbuild(1, 0, n-1)\nfor _ in range(q_count):\n    parts = input().split()\n    if parts[0] == "UPDATE":\n        i, x = int(parts[1]) - 1, int(parts[2])\n        update(1, 0, n-1, i, x)\n    else:\n        l, r = int(parts[1]) - 1, int(parts[2]) - 1\n        print(query(1, 0, n-1, l, r))',
      complexity: 'Time: O(n) build + O(log n) per query/update, Space: O(n)',
    },
  },
  {
    id: 297,
    slug: 'binary-indexed-tree',
    title: 'Binary Indexed Tree (Fenwick Tree)',
    description: 'Cho mảng n số nguyên. Xử lý q truy vấn:\n- ADD i x: cộng x vào arr[i] (1-indexed)\n- SUM l r: in tổng arr[l..r] (1-indexed)\nDùng Binary Indexed Tree (BIT/Fenwick Tree).',
    difficulty: 'hard',
    tags: ['BIT', 'Mảng'],
    acceptanceRate: 30,
    xp: 55,
    starterCode: 'n, q = map(int, input().split())\narr = list(map(int, input().split()))\n# Binary Indexed Tree\n',
    testCases: [
      { input: '5 4\n1 2 3 4 5\nSUM 1 3\nADD 2 5\nSUM 1 3\nSUM 2 5', expectedOutput: '6\n11\n19', isHidden: false },
      { input: '3 2\n10 20 30\nSUM 1 3\nADD 1 -5', expectedOutput: '60', isHidden: false },
      { input: '4 3\n0 0 0 0\nADD 1 5\nADD 3 3\nSUM 1 4', expectedOutput: '8', isHidden: true },
    ],
    hints: [
      'BIT: mảng bit[] kích thước n+1, hỗ trợ prefix sum và point update.',
      'Update: cộng x vào các vị trí i, i + lowbit(i), ...',
      'Query prefix sum: cộng bit[i], bit[i - lowbit(i)], ...',
      'Sum(l,r) = prefix(r) - prefix(l-1).',
    ],
    editorial: {
      approach: 'Fenwick Tree: update O(log n), prefix sum O(log n), range sum = prefix(r) - prefix(l-1).',
      code: 'n, q_count = map(int, input().split())\narr = list(map(int, input().split()))\nbit = [0] * (n + 1)\n\ndef update(i, delta):\n    while i <= n:\n        bit[i] += delta\n        i += i & (-i)\n\ndef prefix_sum(i):\n    s = 0\n    while i > 0:\n        s += bit[i]\n        i -= i & (-i)\n    return s\n\n# Build BIT\nfor i in range(n):\n    update(i + 1, arr[i])\n\nfor _ in range(q_count):\n    parts = input().split()\n    if parts[0] == "ADD":\n        i, x = int(parts[1]), int(parts[2])\n        update(i, x)\n        arr[i-1] += x\n    else:\n        l, r = int(parts[1]), int(parts[2])\n        print(prefix_sum(r) - prefix_sum(l - 1))',
      complexity: 'Time: O(n log n) build + O(log n) per operation, Space: O(n)',
    },
  },
  {
    id: 298,
    slug: 'matrix-chain-multiplication',
    title: 'Nhân Chuỗi Ma Trận',
    description: 'Cho n ma trận cần nhân liên tiếp. Ma trận thứ i có kích thước p[i-1] × p[i]. Tìm số phép nhân vô hướng tối thiểu để nhân tất cả ma trận. In số phép nhân tối thiểu.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Ma trận'],
    acceptanceRate: 32,
    xp: 55,
    starterCode: 'n = int(input())\np = list(map(int, input().split()))  # n+1 phần tử\n# Tìm số phép nhân tối thiểu\n',
    testCases: [
      { input: '3\n10 30 5 60', expectedOutput: '4500', isHidden: false },
      { input: '4\n40 20 30 10 30', expectedOutput: '26000', isHidden: false },
      { input: '3\n10 20 30 40', expectedOutput: '18000', isHidden: true },
    ],
    hints: [
      'DP: dp[i][j] = chi phí tối thiểu nhân ma trận i đến j.',
      'dp[i][j] = min(dp[i][k] + dp[k+1][j] + p[i-1]*p[k]*p[j]) với i ≤ k < j.',
      'Duyệt theo độ dài chuỗi tăng dần.',
    ],
    editorial: {
      approach: 'DP interval: tính chi phí tối thiểu cho mỗi đoạn [i,j], mở rộng dần.',
      code: 'n = int(input())\np = list(map(int, input().split()))\ndp = [[0] * (n + 1) for _ in range(n + 1)]\nfor length in range(2, n + 1):\n    for i in range(1, n - length + 2):\n        j = i + length - 1\n        dp[i][j] = float("inf")\n        for k in range(i, j):\n            cost = dp[i][k] + dp[k+1][j] + p[i-1] * p[k] * p[j]\n            dp[i][j] = min(dp[i][j], cost)\nprint(dp[1][n])',
      complexity: 'Time: O(n³), Space: O(n²)',
    },
  },
  {
    id: 299,
    slug: 'traveling-salesman-simplified',
    title: 'Bài Toán Người Bán Hàng (TSP Nhỏ)',
    description: 'Cho n thành phố (n ≤ 15) và ma trận khoảng cách n×n. Tìm đường đi ngắn nhất xuất phát từ thành phố 0, đi qua tất cả thành phố đúng 1 lần rồi quay về thành phố 0. In chi phí tối thiểu.',
    difficulty: 'hard',
    tags: ['Quy hoạch động', 'Bitmask'],
    acceptanceRate: 25,
    xp: 60,
    starterCode: 'n = int(input())\ndist = []\nfor _ in range(n):\n    row = list(map(int, input().split()))\n    dist.append(row)\n# TSP - tìm đường đi ngắn nhất\n',
    testCases: [
      { input: '4\n0 10 15 20\n10 0 35 25\n15 35 0 30\n20 25 30 0', expectedOutput: '80', isHidden: false },
      { input: '3\n0 1 10\n1 0 1\n10 1 0', expectedOutput: '4', isHidden: false },
      { input: '4\n0 1 2 3\n1 0 4 5\n2 4 0 6\n3 5 6 0', expectedOutput: '12', isHidden: true },
    ],
    hints: [
      'Dùng DP bitmask: dp[mask][i] = chi phí tối thiểu đi qua các thành phố trong mask, kết thúc tại i.',
      'mask là bitmask biểu diễn tập thành phố đã thăm.',
      'Kết quả: min(dp[full_mask][i] + dist[i][0]) với mọi i.',
    ],
    editorial: {
      approach: 'DP bitmask: dp[mask][i] = min cost visiting cities in mask, ending at i.',
      code: 'n = int(input())\ndist = [list(map(int, input().split())) for _ in range(n)]\nINF = float("inf")\ndp = [[INF] * n for _ in range(1 << n)]\ndp[1][0] = 0  # Start at city 0\nfor mask in range(1 << n):\n    for u in range(n):\n        if dp[mask][u] == INF: continue\n        if not (mask & (1 << u)): continue\n        for v in range(n):\n            if mask & (1 << v): continue\n            new_mask = mask | (1 << v)\n            dp[new_mask][v] = min(dp[new_mask][v], dp[mask][u] + dist[u][v])\nfull = (1 << n) - 1\nans = min(dp[full][i] + dist[i][0] for i in range(n))\nprint(ans)',
      complexity: 'Time: O(2^n × n²), Space: O(2^n × n)',
    },
  },
  {
    id: 300,
    slug: 'a-star-pathfinding',
    title: 'A* Pathfinding - Tìm Đường Trên Lưới',
    description: 'Cho lưới m×n, ô "." là đi được, ô "#" là vật cản. Tìm đường đi ngắn nhất từ ô S (start) đến ô E (end), chỉ đi 4 hướng (lên/xuống/trái/phải). In số bước tối thiểu. Nếu không có đường, in -1.',
    difficulty: 'hard',
    tags: ['Đồ thị', 'A*'],
    acceptanceRate: 35,
    xp: 55,
    starterCode: 'm, n = map(int, input().split())\ngrid = []\nfor _ in range(m):\n    grid.append(input())\n# A* tìm đường ngắn nhất từ S đến E\n',
    testCases: [
      { input: '5 5\nS....\n.###.\n.#...\n.#.#.\n...#E', expectedOutput: '8', isHidden: false },
      { input: '3 3\nS..\n###\n..E', expectedOutput: '-1', isHidden: false },
      { input: '3 3\nS..\n...\n..E', expectedOutput: '4', isHidden: true },
    ],
    hints: [
      'A* dùng heuristic Manhattan distance: h = |x1-x2| + |y1-y2|.',
      'Priority queue với f = g + h (g = chi phí thực, h = ước lượng).',
      'Mở rộng node có f nhỏ nhất, cập nhật g cho neighbors.',
    ],
    editorial: {
      approach: 'A* với Manhattan distance heuristic, priority queue sắp xếp theo f = g + h.',
      code: 'import heapq\nm, n = map(int, input().split())\ngrid = [input() for _ in range(m)]\nstart = end = None\nfor i in range(m):\n    for j in range(n):\n        if grid[i][j] == "S": start = (i, j)\n        elif grid[i][j] == "E": end = (i, j)\n\ndef heuristic(a, b):\n    return abs(a[0]-b[0]) + abs(a[1]-b[1])\n\ndist = [[float("inf")]*n for _ in range(m)]\ndist[start[0]][start[1]] = 0\npq = [(heuristic(start, end), 0, start[0], start[1])]\ndirs = [(0,1),(0,-1),(1,0),(-1,0)]\nwhile pq:\n    f, g, x, y = heapq.heappop(pq)\n    if (x, y) == end:\n        print(g)\n        break\n    if g > dist[x][y]: continue\n    for dx, dy in dirs:\n        nx, ny = x+dx, y+dy\n        if 0 <= nx < m and 0 <= ny < n and grid[nx][ny] != "#":\n            ng = g + 1\n            if ng < dist[nx][ny]:\n                dist[nx][ny] = ng\n                heapq.heappush(pq, (ng + heuristic((nx,ny), end), ng, nx, ny))\nelse:\n    print(-1)',
      complexity: 'Time: O(m×n×log(m×n)), Space: O(m×n)',
    },
  },
];
